### ISSUE TITLE
Help Wanted: Deploying a compiled contract

### ISSUE THREAD

**Issue by NellyWhadsDev** [juanfranblanco/vscode-solidity#1]
Once I have compiled a contract using this VSCode extension, I seem to be having difficulty deploying it to a local blockchain ([Blockapps ](https://github.com/blockapps/bloc) installed locally). When using the [Visual Studio extension](https://visualstudiogallery.msdn.microsoft.com/96221853-33c4-4531-bdd5-d2ea5acc4799), deploying a contract brings up a web browser providing GUI for calling the contract on the local blockchain. Can we achieve this in some other way while using this VSCode extension?

~~I have tried compiling a contract and adding it to the local blockchain using bloc, but I still can't seem to find a way to test the contract through the browser or CLI (without installing the Mix IDE or Visual Studion + the Extension by ConsenSys).~~
Edit: Derp. Solved by adding the html extension to the URL.

Any guidance/pointer in the right direction would be helpful

Many thanks,
NellyWhads

PS. Great work in bringing solidity to VSCode - I love the lightweight editor and now love using it for this new language thanks to your efforts :)

**Comment by juanfranblanco** [comment]
No problem, I have been busy with other features
