### ISSUE TITLE
1.cannot output the abi & bin file. 2.problem when I try to use a localversion

### ISSUE THREAD

**Issue by gaozhenGo** [juanfranblanco/vscode-solidity#100]
environment：manjaro linux 17.1.7 
1.when I press ctrl+F5,it noticed me compiled successfully ,and also generated the bin directory.but the bin directory was empty,nothing is there,neighter abi file  nor bin file.but in my Windows 10, the plugin works well,all the files generated correctly.
2. How to use a local version? I notice that I need to set the attribute:solidity.compileUsingLocalVersion,but in my linux ,I set the path "/usr/bin/solc" and it didn't work,and I cannot find the file such as example "C:\\Users\\JuanFran\\Downloads\\soljson-v0.4.15%2Bcommit.bbb8e64f.js", how could I fix it?

**Comment by juanfranblanco** [comment]
@gaozhenGo you can find all the versions of solidity here https://github.com/ethereum/solc-bin/tree/gh-pages/bin so just download the one you want and reference it locally

Regarding your other issue, have you open a workspace in vscode?

**Comment by gaozhenGo** [comment]
thanks a lot.I've already settled the problems thank to your prompt.and for the issue that cannot generate abi & bin I solved it by create the src direcoty and put the *sol files into it. @juanfranblanco
