### ISSUE TITLE
[Request] Add "installation" to readme

### ISSUE THREAD

**Issue by mesqueeb** [juanfranblanco/vscode-solidity#101]
It's not 100% sure if this library is installable by purely adding a VSCode plugin from the VSCode plugin library.

I would love to have a small "installation" section to the readme that says if I can add it through VSCode plugin library and what you should search there. 😃

**Comment by obernardovieira** [comment]
how so?
There is an **Instructions** section. Should this be changed to something like **Install**? Maybe a different name because it may be misunderstood by other people thinking that is related to package installation.

Maybe a section named **Requirements** ?

**Comment by mesqueeb** [comment]
@obernardovieira
I'm sorry I was unclear.

In the "instructions" section now it just says:
- Remote download
- Using Local file
- Npm / node installation

Maybe you should add a section called "VSCode plugin" and write how we can install it via just the VSCode interface for installing plugins.
Now I wouldn't know what to look for.

Cheers!

**Comment by obernardovieira** [comment]
I think you are still unclear.
First, you install the extension using the respective panel on vscode, then you choose to use a local npm installation (inside project) or use a local installation somewhere on your machine or you use a remote installation. But you have to use one of them.

I still don't see what you want exactly, sorry.

**Comment by juanfranblanco** [comment]
So the request is, if you find the solidity extension by an external source to describe how to install the plugin in vscode. One issue is that the readme is also used by vscode to describe the plugin, so it will be rather redundant in that scenario. Thoughts?

**Comment by juanfranblanco** [comment]
Also note that changing the compiler is another specific area of the plugin, nothing to do with the installation, by default it uses the embedded version.

**Comment by mesqueeb** [comment]
@juanfranblanco oh I didn't know this same readme was used by the VSCode plugin store!!! That's why I was so confused, because I found this plugin through google through github. And I kept looking for instructions on what name to type in the VSCode plugin store to find it. 

Now I see where all the miscommunication came from lol 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by juanfranblanco** [comment]
@mesqueeb  oh don't worry and good point, so that is the strange conundrum who do we confuse the vscode user or the external user.

**Comment by obernardovieira** [comment]
Is this issue solved?

**Comment by mesqueeb** [comment]
@obernardovieira I don't know. It's not so much as an issue I guess. It's just my personal opinion maybe that some people might be confused how to install this plugin when they come here through google → github.com. instead of directly reading it in the VSCode plugin store.

But I guess it's not such a big deal so yeah. : D

**Comment by rocky** [comment]
@mesqueeb A first cut at some developer docs has been merged into master. It could use some nice looking gifs of screenshots. 

Are you up for looking over those instructions, seeing if they are correct and adding maybe a couple of screenshots to show what is meant by the blue versus orange border, or a picture of the play versus pause buttons, or the debug dropdown?

**Comment by juanfranblanco** [comment]
Closing this now, I think vscode is highly know now so people know how to install extensions
