### ISSUE TITLE
Possible bug in indentation detection

### ISSUE THREAD

**Issue by cat-j** [juanfranblanco/vscode-solidity#104]
This is a really minor thing, I know, but it's mildly annoying.

![highlight](https://user-images.githubusercontent.com/5105531/47794700-b36f7f00-dcff-11e8-9a15-5f57faa57e8b.png)

See how the first characters of `bytes32` and `getSuperblockInfo` are underlined? The message displayed when you hover over `getSuperblockInfo` is

> ```Expected indentation of 12 spaces but found 67 [indent]```

which seems to indicate that the linter treats everything before the first alphanumeric character as whitespace.

The same thing happens every time a line starts with a bracket. Is this intended behaviour?

**Comment by obernardovieira** [comment]
Hi,
What linter are you using?

**Comment by juanfranblanco** [comment]
@cat-j  are you using the default linter "solium" or "solhint"

**Comment by cat-j** [comment]
I was using Solhint, turns out switching to Solium fixed it. I'll consider this fixed and crosspost it to the Solhint repo!
