### ISSUE TITLE
[WIP] Notify extension server about linters file change

### ISSUE THREAD

**Issue by obernardovieira** [juanfranblanco/vscode-solidity#106]
Citing @juanfranblanco on #105 it's good to make the extension server be aware of linters file changes, so with this, it's possible to lint without the need of reopening files.

> One thing that it could be used, is for the client to notify the server of those file changes. So that will be probably the direction to use. That way it could be reused for any other type of file.
> 
> So the client will have something like:
> 
> ```js
>     // Options to control the language client
>     let clientOptions: LanguageClientOptions = {
>         // Register the server for plain text documents
>         documentSelector: [{ scheme: 'file', language: 'plaintext' }],
>         synchronize: {
>             // Notify the server about file changes to '.clientrc files contained in the workspace
>             fileEvents: workspace.createFileSystemWatcher('**/.clientrc')
>         }
>     };
> ```
> 
> and the server this:
> 
> ```js
> connection.onDidChangeWatchedFiles(_change => {
>     // Monitored files have change in VSCode
>     connection.console.log('We received an file change event');
> });
> ```
> 
> From the docs
> https://code.visualstudio.com/docs/extensions/example-language-server

**Comment by obernardovieira** [comment]
what happens exactly when I save the file .soliumrc ?
or better, what happens when I save any file ?
because I think it runs a validation even by just changing any file ( if so, show we change it o run a verification only when a .sol file is changed? )
so It's working just like if I already have a watcher, but I don't :bowtie:

**Comment by juanfranblanco** [comment]
```javascript
documents.onDidChangeContent(event => {
    const document = event.document;
    if (!validatingDocument && !validatingAllDocuments) {
        validatingDocument = true; // control the flag at a higher level
        // slow down, give enough time to type (1.5 seconds?)
        setTimeout(() =>  validate(document), validationDelay);
    }
});

```

I believe all changes are getting caught in the language server, I don't think you can check this in the client for specific sol files. So most probably the simplest solution will be to check the extension here before continuing with validation. Now.. that may solved your problem too, as you will want to run a validation when the .soliumrc file has changed.

**Comment by juanfranblanco** [comment]
Closing this now
