### ISSUE TITLE
pragma error

### ISSUE THREAD

**Issue by zzj0402** [juanfranblanco/vscode-solidity#111]
pragma solidity ^0.4.24;
extension keeps alarming me to use 0.5.

**Comment by juanfranblanco** [comment]
Yes the included compiler is now upgraded to 0.5. You can point to another version if wanted.

**Comment by wschae** [comment]
I added  "solidity.compileUsingRemoteVersion": "v0.4.24+commit.e67f0147" into my "user settings" and errors are gone 👍 

![image](https://user-images.githubusercontent.com/4300700/48918777-a39d1380-ee43-11e8-9b63-df228771b42b.png)

**Comment by zzj0402** [comment]
Yeah how very smart. Exactly where to find user setting?

**Comment by juanfranblanco** [comment]
@zzj0402 press F1 and type user settings. Then in the window, navigate to extensions, solidity and / or just select any up the options to edit the json file.

**Comment by juanfranblanco** [comment]
@pmmax I have just released another version with optimisation on, set to 200. After moving to the new compiler input, this was not included.

**Comment by pmmax** [comment]
@juanfranblanco Thank you very much for the quick fix!

I can confirm that all my contracts compiled with npm downloaded solcjs for Solidity v0.4.24 are working again the way they worked when were compiled with v0.0.46 regarding the gas usage.

Also noticed you bumped the vscode to 1.1.22, so no issues with the hacked flatmap-stream!

**Comment by juanfranblanco** [comment]
@pmmax  yeah vscode was the only package with the issue, rather surprised they did the quick fix.
