### ISSUE TITLE
How to find the version of solidity compiler the extension uses?

### ISSUE THREAD

**Issue by kombos** [juanfranblanco/vscode-solidity#112]
First I want to know if there is an in-built solidity compiler that comes packaged with this solidity extension for vscode? And if so, where can i see the version number of the compiler? Thanks.

**Comment by juanfranblanco** [comment]
Yes, there is, when compiling in the output window you can see the version used. Also you can configure vscode with a different version of the compiler, check the readme for settings.

**Comment by kombos** [comment]
> Yes, there is, when compiling in the output window you can see the version used. Also you can configure vscode with a different version of the compiler, check the readme for settings.

Thanks for clarifying it Juan.
