### ISSUE TITLE
0.49 produces incorrectly formatted json file, and wrapper generation fails

### ISSUE THREAD

**Issue by inukaeth** [juanfranblanco/vscode-solidity#119]
Attempting to generate the wrapper file from the generated JSON file from a contract results in the error "combinedInput.abi.split is not a function". JSON file abi attribute value is JSON and not a JSON array as before.  
Thanks

**Comment by juanfranblanco** [comment]
@inukaeth can you post a screenshot? Just to get an understanding of the area you mean

**Comment by inukaeth** [comment]
Hitting a different issue, I will post on gitter, since I am not second guessing my setup, even though this the plugin work great before updating VS code.

After several attempts to install/reinstall my whole build process gets appears to not work. Tried on a different machine still the same.

cntrl-p -> build current contract  results in the message start compile being shown and then nothing, no completion message. No output files generated. 

Closing and posting on gitter
