### ISSUE TITLE
would like to see all the solidity types autocomplete

### ISSUE THREAD

**Issue by inigo-montoya** [juanfranblanco/vscode-solidity#12]
from uint, bytes32[] to struct, map etc.

**Comment by juanfranblanco** [comment]
Reminder to add this to the autocompletion elements

**Comment by juanfranblanco** [comment]
Added types, units, global variables, global methods. Dot notation.
Missing: Types identification of variables to provide completion of methods / properties. (structs, addresses)

**Comment by juanfranblanco** [comment]
Autocomplete is working, but it could be better. 

On struct, identify the type declared or returrned by a method and do a dot completion on properties.
On contract, identify the type declared or returrned by a method and do a dot completion on properties.
Methods need to identify the type returned.

**Comment by juanfranblanco** [comment]
Closing and adding a specific issue
https://github.com/juanfranblanco/vscode-solidity/issues/58
