### ISSUE TITLE
Error parsing payable address when compiling

### ISSUE THREAD

**Issue by CarlosLanderas** [juanfranblanco/vscode-solidity#124]
Hello, I have a contract that is properly compiling in Remix using version 0.5.0+commit.1d4f565a and whenever I try to compile using vscode extension I get the following error:

```
Compiling using default compiler, solidity version: 0.5.0+commit.1d4f565a.Emscripten.clang 

[Error - 7:48:19 PM] solium error: SyntaxError: An error occured while parsing the source code: Expected ";", "=", comment, end of line, or whitespace but "o" found. Line: 5, Column: 21
```

It seems to be crashing whenever it finds a payable address:

Like this:

```
pragma solidity ^0.5.0;

contract Concert {
    
    address payable owner;  
```

Also here:

` function refundTicketToAccount(address payable _to) public validAccount(_to) {`

I tried to increase compiler version using  compileUsingRemoteVersion with no luck.

Any idea?

Thanks

**Comment by juanfranblanco** [comment]
Sorry I missed that.. 
I have not issues here 
![image](https://user-images.githubusercontent.com/562371/56150299-801b6680-5fa6-11e9-8647-ecf5a4cacfc1.png)

**Comment by mattaereal** [comment]
It may be that solium does not support 0.5.x? Zeppelin migrated to solhint.

Either way, I'm having exactly the same issue using solhint.

**Comment by mattaereal** [comment]
I realized I had solidity-solhint extension installed as well (redundant it seems?). Removing it and reloading vscode did the trick.
