### ISSUE TITLE
What does this green line means?

### ISSUE THREAD

**Issue by chnejohnson** [juanfranblanco/vscode-solidity#137]
Sorry, I'm new. I don't understand why all of my require() highlighted with green line. Is this extension's problem? or others?

<img width="901" alt="螢幕快照 2019-05-07 上午11 53 50" src="https://user-images.githubusercontent.com/31992185/57270773-4cbc8b00-70bf-11e9-9353-0c853fcadee5.png">

**Comment by juanfranblanco** [comment]
Hi, the issue is a warning highlight, as it is recommended to specify the reason of failure for the "require"

**Comment by chnejohnson** [comment]
oh...the warning highlight doesn't appear in the past. The code can work on the Remix, I think it's not really a problem, right? How can I fix it?

**Comment by juanfranblanco** [comment]
It is not really a problem, you can just add a another parameter including the message. 

For example require(....,"error message");

**Comment by chnejohnson** [comment]
Got it! Thanks.
