### ISSUE TITLE
Compiler version error

### ISSUE THREAD

**Issue by npattarone** [juanfranblanco/vscode-solidity#138]
ParserError: Source file requires different compiler version (current compiler is 0.5.8+commit.23d335f2.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.5.0;
^--------------------^

Addding `"solidity.compileUsingRemoteVersion": "0.5.0+commit.1d4f565a"` to the setting on VSCODE is not working. When pressing F5 to compile the current contract it shows an error: 

![image](https://user-images.githubusercontent.com/19308167/57308141-2ba66b00-70bc-11e9-8641-eb16a524951a.png)

**Comment by juanfranblanco** [comment]
@npattarone it is missing the "v" prefix "v0.5.0+commit.1d4f565a". I will ask the solidity team to consider to force the "v" prefix in the future if not set.

**Comment by npattarone** [comment]
You're a genius 🙏 thanks!!
