### ISSUE TITLE
Generated *Definition.cs very slow to open when long BYTECODE generated...

### ISSUE THREAD

**Issue by ts5678** [juanfranblanco/vscode-solidity#139]
After generating C# code, the *Definition.cs file is very slow to open when the `public static string BYTECODE =` Hex string is really long.  Is there any way around this? (I realize this may not be a problem specific to the extension, but it may be mitigated by some sort of change)

**Comment by juanfranblanco** [comment]
Hi @ts5678 yes, I have that issue as well, that specific of the csharp extension

**Comment by juanfranblanco** [comment]
@ts5678 have some time to play around with it, the only solution is to split the string multiple times. The issue with this is that it adds more "noise" to the class and makes it very difficult to copy and paste (if wanted) the bytecode.

**Comment by juanfranblanco** [comment]
This is sadly still an issue with vscode, closing the issue.
