### ISSUE TITLE
after updating extension do not produce output

### ISSUE THREAD

**Issue by paradise** [juanfranblanco/vscode-solidity#14]
I've updated to last version and now extension alerts that contract compiled successful but do not produce .abi or .bin files.

**Comment by paradise** [comment]
I found the problem in file compiler.js
The problem line is `if (child.name === 'Contract')`
now it should be `if (child.name === 'ContractDefinition')`
maybe they updated filed name in new version of solc compiler

I changed this file as I wrote above and my contract compiles successfully and produces output in /bin folder.

**Comment by juanfranblanco** [comment]
Checked in the fixt, Thanks!!!
