### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Iggy17** [juanfranblanco/vscode-solidity#140]
- Issue Type: `Performance`
- Extension Name: `solidity`
- Extension Version: `0.0.56`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Iggy.Phiri\JuanBlanco.solidity-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kombos** [comment]
getting the same issue

**Comment by juanfranblanco** [comment]
I am closing this for now, please reopen if anyone experience the same issues and can provide some details
