### ISSUE TITLE
Cannot use different solc version projects in same workspace

### ISSUE THREAD

**Issue by sebastiantf** [juanfranblanco/vscode-solidity#143]
I find that `compiler.ts` uses `vscode.workspace.rootPath` which is actually [deprecated](https://code.visualstudio.com/api/references/vscode-api#workspace).

I believe this causes the extension to always use the `solc` compiler of the first project folder in the workspace. This produces errors or warnings when having multiple projects that use different versions of Solidity Compiler in the same workspace.

Using [workspaceFolders](https://code.visualstudio.com/api/references/vscode-api#workspace) might give a better result.

**Comment by juanfranblanco** [comment]
Hi Sebastian,

Let me understand the issue, so you have multiple folders (workspaces) and each one of them want to use a different version of solidity solc. At the moment the only way to override this, is to use a node package installation, but also this is always driven as well by the user settings.

This is actually a very interesting change, but yes there are many points of failure as we move from user settings, folder settings to workspace settings. 

Ill do some research on this, but yeah a simple solution is that if you want to override a specific user setting you can use the npm package installation from the selected workspace folder.

But as a default fix on the deprecated usage of rootfolder i would just use workspaceFolders[0], which is root.

Thoughts?

**Comment by sebastiantf** [comment]
@juanfranblanco Appreciate your prompt response.

To be specific, I wasn't using a node package installation for `solc`. I was using Truffle and I let Truffle figure out and fetch the required solc by using `pragma` annotations and specifying the same version in `truffle-config.js`. I am a bit reluctant to install solc as a separate npm installation since it's already being taken care of by Truffle.

I was actually wondering whether there was a way to use `workspaceFolders[]` to let the extension find and use the appropriate `solc` depending on the active/selected folder/file being compiled. I haven't looked much into how we could use workspaceFolders[] for this purpose, or if that's even possible. Anyways, that was my thought.

**Comment by juanfranblanco** [comment]
ah yeah that is a completely different configuration, in vscode you have the user settings options, overriding with a npm package and the default solc packaged.

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/61950158-f287e380-afa4-11e9-80fa-ecb3e08d241a.png)

I think this is the best option, using workspace settings.

**Comment by juanfranblanco** [comment]
So yes, just use the workspace settings and that will do. The npm package is just mainly for local overrides (offline) the same as the offline setting to point to a solc.js file.

**Comment by sebastiantf** [comment]
But I do not see how I could use any of the three settings options to achieve the desired results.

I have multiple project folders in the same workspace. Each of those projects needs different versions of solc to compile. Please correct me if I'm wrong but, even if I use the workspace settings, it's going to get applied to the whole workspace and all the folders in it, right? I was looking for an option that could allow the extension to use the right `solc` for each folder in the same workspace. I don't think neither _user settings_ nor _workspace settings_ would help in doing that. And I don't want to do a separate npm installation.

**Comment by juanfranblanco** [comment]
Ok so we are talking about something completely different, not workspace settings but per folder settings in a workspace. This can mess up things big time, the best is to open each workspace separately (different window per folder), i guess vscode will support this eventually natively to allow to have multiple "projects" in a solution each one with their own settings.. ie C# project, Solidity project, etc..

**Comment by sebastiantf** [comment]
Yeah, this could mess up things a bit; could be a lot of work. But I do think `workspaceFolders[]` could be helpful in some way.

Hoping for such a feature to be added in the near future either by support from vscode or as a new feature from the extension.

**Comment by juanfranblanco** [comment]
Yes, my bet is on vscode to support it out of the box. I personally see myself needing those specific settings for those projects of different languages (solidity / c# / Nethereum) and funnily enough I guess common workspace setting for both for integration.
