### ISSUE TITLE
Disable implied order of preference

### ISSUE THREAD

**Issue by PaulRBerg** [juanfranblanco/vscode-solidity#145]
I love this extension, but I do spend a lot of time configuring it. Things get messy when a project scales, particularly when using a [yarn workspaces monorepo](https://github.com/sablierhq/sablier).

My suggestion is to let developers **set in stone the solidity compiler version** instead of always choosing the local version. This would be extremely helpful.

Dependencies have their own dependencies, and we all know that this is the deal with the devil every javascript developer does throughout their life. In my project, I use a few tools from the [0x monorepo](https://github.com/0xProject/0x-monorepo) which depend on solc@0.5.10.

This particular version is just an example, the problem in general is that I always end up doing some kind of workaround to remedy the mismatch:

1. Manually override the dependency by setting solc@0.5.11 in my own dependencies
2. Include all "solc" packages in the "nohoist" for yarn to not put them in the base folder

Unfortunately, with solc 0.5.10 and solc 0.5.11 and the recent dependencies I added, these strategies don't work anymore. I realised that the whole thing would be easily sorted out if there was a way to enforce a global compiler, either remote or local, preferably the one installed via homebrew due to its speed.

**Comment by juanfranblanco** [comment]
Have you tried setting a vscode namespace with the remote version number? This way you can choose the version you want for each "workspace", or if working offline just set the path in the workspace for that version.

**Comment by PaulRBerg** [comment]
Yup, I did this before and I did it again now, the version chosen is still the local one found in `node_modules`.

```
  "solidity.compileUsingRemoteVersion": "v0.5.11+commit.c082d0b4"
```

So the order of preference of the extension chooses the local dependency over this setting.

**Comment by juanfranblanco** [comment]
Ok, so your ask is to allow disabling the node modules one as it is included in one of your downloaded repos, correct?

**Comment by PaulRBerg** [comment]
Exactly! It's just a suggestion. Sort of like adding a new setting called `solidity.enforceCompilerVersion`.

**Comment by rocky** [comment]
@PaulRBerg I looked at  [yarn workspaces monorepo](https://github.com/sablierhq/sablier) and see that it is a truffle project. 

Suppose (in an experimental version) there were a configuration setting that noticed when you were working in a truffle project and used truffle's `truffle-conf.js` to get compiler settings?

**Comment by PaulRBerg** [comment]
Oh yes picking up the truffle version would be great for single repos, I suggested that in this thread: https://github.com/juanfranblanco/vscode-solidity/issues/120

But for monorepos, the truffle version of one particular package wouldn't do much. The best solution I come up with is to have the ability to enforce a global version, disregarding of the local dependencies.

**Comment by juanfranblanco** [comment]
So for simplicity sake to work as it stands but disable the node check as it is the current override. Check truffle version @rocky is not in the scope, as it is better to set the version per workspace vscode settings.

**Comment by juanfranblanco** [comment]
As we have seen here too many options breaks it, how many orders of preference can you put in place for a single user. What happens in the future when people don't use JavaScript as the preferred testing toolset.

**Comment by PaulRBerg** [comment]
Yes, setting the version per workspace vscode settings is more intuitive and easier to handle than the config file of an opinionated contract compiler.

**Comment by rocky** [comment]
Ok. This is useful information.

**Comment by PaulRBerg** [comment]
@juanfranblanco I updated to 0.062 and my node-based "solc" is not recognised anymore. I put this in the settings:

```json
"solidity.enableLocalNodeCompiler": true
```

**Comment by juanfranblanco** [comment]
"It worked on my pc!" Thanks Ill have a look today.

**Comment by juanfranblanco** [comment]
Many thanks, all fixed now and released. Issues with my testing configuration.

**Comment by PaulRBerg** [comment]
Haha great, thank you!

**Comment by juanfranblanco** [comment]
Thanks to you!
