### ISSUE TITLE
Avoid using workspace.rootPath

### ISSUE THREAD

**Issue by roblourens** [juanfranblanco/vscode-solidity#146]
This extension appears to be using the `workspace.rootPath` API. This is a deprecated property and may not work as expected. Please use `workspaceFolders` instead. More info:  https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath

https://github.com/microsoft/vscode/issues/69335

**Comment by juanfranblanco** [comment]
Thanks, that has been reported already, it will be "fixed" in the next release.

**Comment by juanfranblanco** [comment]
If you have any suggestions on best practices, please let me know. I am just going use the 0 index to get the root

**Comment by juanfranblanco** [comment]
This has been fixed already, thanks!
