### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by 78stevekim** [juanfranblanco/vscode-solidity#152]
- Issue Type: `Bug`
- Extension Name: `solidity`
- Extension Version: `0.0.59`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by juanfranblanco** [comment]
@78stevekim What is the issue?

**Comment by juanfranblanco** [comment]
Closing this as there is no more info.
