### ISSUE TITLE
Compilation is optimized?

### ISSUE THREAD

**Issue by brunoarruda** [juanfranblanco/vscode-solidity#153]
Hi,

On Remix we see an option to allow optimized compilation. I searched in preferences and didn't find anything related. I saw the list of possible compilers and that didn't give me any clue of it.

So, could you add to your documentation if your compilation is 'optimized' or not?

My regards,

**Comment by juanfranblanco** [comment]
It is and not in the documentation, although not configurable, ill add both :)

**Comment by juanfranblanco** [comment]
Now available
