### ISSUE TITLE
Node Module Imports Not Resolving

### ISSUE THREAD

**Issue by danforbes** [juanfranblanco/vscode-solidity#156]
Given the following directory structure...

```
Solution
└───.vscode
│   │
|   │   settings.json
│   
└───node_modules
|
└───truffle
│   │
|   └───contracts
|   |   │   xx.sol
```

...and a `settings.json` that contains `"solidity.packageDefaultDependenciesDirectory": "node_modules"`, I am getting the following error in `xx.sol`: `Source "module_name/path/Dependency.sol" not found: File import callback not supported`.

**Comment by Emobe** [comment]
I'm getting the same issue with importing openzeppelin

**Comment by danforbes** [comment]
I believe you need to add an additional entry to the `settings.json` file: `"solidity.packageDefaultDependenciesContractsDirectory": ""`. That seems to have gotten things working for me. Hope it helps you @Emobe :+1:

**Comment by Emobe** [comment]
Nope, did not fix anything for me. I had both of those set
