### ISSUE TITLE
Where do I set the compiler version

### ISSUE THREAD

**Issue by denismp** [juanfranblanco/vscode-solidity#161]
Your plugin for VSC instructions indicates that to set the compiler version to use:

"solidity.compileUsingRemoteVersion" : "lastest"

Where do you set this Visual Studio Code?

The instructions don't tell you where to set these values.

**Comment by juanfranblanco** [comment]
hi @denismp I believe this was solved already in gitter. 
But just in case.

Press F1 in vscode
Type settings
Select solidity settings
Open the settings file
Type: "solidity.compileUsingRemoteVersion" : "latest"

you will get autocomplete for all other settings

**Comment by denismp** [comment]
So on the mac vsc, I pressed fn-f1.  I typed in settings, but I do not see solidity settings.
