### ISSUE TITLE
Removed wrong keywords when auto-formatting

### ISSUE THREAD

**Issue by maxweng** [juanfranblanco/vscode-solidity#162]
The `address payable` keyword is wrongly corrected as `address` when using the helper contract `Address.sol` from OpenZeppelin. What I had in the smart contract was like

```
using Address for address payable;
```

But got wrongly auto-corrected as

```
using Address for address;
```

**Comment by juanfranblanco** [comment]
Thanks @maxweng, ll refer this to the prettier solidity project.
