### ISSUE TITLE
Using wrong solc dependency

### ISSUE THREAD

**Issue by maurelian** [juanfranblanco/vscode-solidity#163]
I'm seeing this error when looking at the code in [this repo:](https://github.com/arcadeum/niftyswap):

`Source file requires different compiler version (current compiler is 0.6.1+commit.e6f7d5a4.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version`

When I run `npm ls solc` in that directory, I see: 

```
$ npm ls solc
niftyswap@0.1.3 /Users/primary/Projects/Audits/horizon-games-audit-2020-02/code/niftyswap
├─┬ ganache-core@2.10.1
│ └── solc@0.6.1  extraneous
└── solc@0.5.16

npm ERR! extraneous: solc@0.6.1 /Users/primary/Projects/Audits/horizon-games-audit-2020-02/code/niftyswap/node_modules/ganache-core/node_modules/solc
```

I can't find solidity 0.6.1 installed anywhere else on my machine. It seems that you're somehow finding the wrong solc dependency.

**Comment by juanfranblanco** [comment]
It looks like it's picking the installed version by the extension. 

Can you make sure that the node compiler is enabled using this setting?

https://github.com/juanfranblanco/vscode-solidity/blob/master/package.json#L101

This can be found in user settings or work space settings in vscode.

**Comment by miohtama** [comment]
I have the same issue. I have nuked every possible solc binary I find on my system and it is still somehow pulling in 0.6.x. 

How can I check within Visual Studio Code which version and path of solc the extension picks up?

**Comment by juanfranblanco** [comment]
@miohtama the extension uses by default the current packaged version. 

At the time of writing is 0.6.1. You can configure the extension to compile downloading an specific version like "latest" or just using the number you require. 

You can get the version number from here https://github.com/ethereum/solc-bin/tree/gh-pages/bin.

If you install a solc as a module you can enable / disable this using the user setting described here: https://github.com/juanfranblanco/vscode-solidity/blob/master/package.json#L101

Maybe you have done all this, is there any other setting that you may have?

**Comment by miohtama** [comment]
I would recommend adding, for example, a command palette command that shows the current active version the extension is using. This would reduce the need to blindly poke settings and hope it works.

**Comment by juanfranblanco** [comment]
Ahh good sugestion, i actually do that on compilation but surely much better also on a context menu and command. I will add it in the next release ASAP.

**Comment by maurelian** [comment]
Would it be possible to also allow choosing the compiler version from a dropdown in the command pallete?

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/77673431-11020c80-6f82-11ea-971c-b88672416ee8.png)

Hopefully this makes it easier.. you get the information, you can change the workspace and global setttings for "remote" compiler (ie download a specific version using solc)

**Comment by juanfranblanco** [comment]
Closing this now, although there are thoughts to create an auto detect the version for the current contract selected.

**Comment by maurelian** [comment]
Thanks FWIW, I've found the dropdown selector super helpful since you added it. :)

**Comment by juanfranblanco** [comment]
Thanks @maurelian !! :)
