### ISSUE TITLE
Issue with Compilation of the current contract

### ISSUE THREAD

**Issue by gabrielkasten** [juanfranblanco/vscode-solidity#165]
Hello, I used to press F1 on Visual Code and the options of:
Compile Current Solidity Contract
Compile all Solidity Contracts

Used to appear but not anymore.
I need help please, I am trying to compile my .sol file.

![image](https://user-images.githubusercontent.com/55507103/77368282-802cf600-6d21-11ea-93cf-029a6c13bd71.png)

**Comment by juanfranblanco** [comment]
@gabrielkasten Right click and you can compile the current contract from the context menu or press F5, I will restore it in the next release. 
![image](https://user-images.githubusercontent.com/562371/77413599-81a8fd80-6db7-11ea-9836-ee3da243290b.png)

**Comment by gabrielkasten** [comment]
Thank you very much @juanfranblanco !

**Comment by juanfranblanco** [comment]
Thanks to you! @gabrielkasten :)
