### ISSUE TITLE
Formatter is incompatible with 0.6

### ISSUE THREAD

**Issue by WyseNynja** [juanfranblanco/vscode-solidity#167]
I am trying to code in solidity 0.6, but the linter keeps removing my "override" lines. How do I stop it?

Alternatively, it looks like I can use the "next" version: https://github.com/protofire/solhint/issues/170#issuecomment-578263770. Is there any way to do this? I don't see an option in settings.

**Comment by juanfranblanco** [comment]
Regarding the issue with override, this is a problem with prettier which is the formater https://github.com/prettier-solidity/prettier-plugin-solidity/issues/221

**Comment by juanfranblanco** [comment]
@WyseNynja  Regarding prettier the best way is to either:

"to avoid prettier to mess with an unsuported keyword is to add the comment ```prettier-ignore``` before the line" as per the prettier guys suggestion.

or I have added now the support to simply disable formatting using the following setting:
![image](https://user-images.githubusercontent.com/562371/78027092-ade2f200-7354-11ea-9c32-7c97dc7779b0.png)

Regarding the upgrade of Solhint I am awaiting confirmation that the package is ready to be integrated into vscode.

**Comment by WyseNynja** [comment]
Thank you! I've disabled the formatter for now since there are a lot of lines affected. Looking forward to that issue being closed on prettier.

**Comment by WyseNynja** [comment]
Actually, this shouldn't be closed yet. We should close it when prettier has fixed this issue and then vscode-solidity has been updated with their fix.

**Comment by petejkim** [comment]
Is it possible to make this plugin just use the prettier and solhint that are installed in the current project? as opposed to using what's bundled in the extension?

**Comment by fvictorio** [comment]
@juanfranblanco I think prettier-solidity should work with 0.6 now.

**Comment by juanfranblanco** [comment]
Thanks @fvictorio
