### ISSUE TITLE
How to disable Auto-Formatting in .sol files

### ISSUE THREAD

**Issue by gitpusha** [juanfranblanco/vscode-solidity#168]
Hi @juanfranblanco,

I have a problem that has been bugging me for some time now with` vscode-solidity`: somehow auto-formatting is configured for my solidity files, even though I never enabled an auto-formatter and even though I **never** **installed** or configured `prettier-solidity`.

As far as I understand, auto-format should only be an option if you intentionally configured it using prettier-solidity.

So my question: **Does some auto-formatting ship with vscode-solidity standalone and how can I disable it?**
 
Sometimes I accidentally `CMD + Alt + F`  which I am used to doing in my JS files to use Prettier. But I dont want any formatter to format my Solidity files. But somehow some Formatter is doing something. Even after I disabled Solidity language in the normal Prettier extension to be explicit, my Solidity files still had an auto-formatter configured somewhere. So I think it must be somewhere in the vscode-solidity extension.

The reason I do not want to use that formatter is because it does not adhere to the [Solidity Style Guide.](https://solidity.readthedocs.io/en/latest/style-guide.html) 

I would appreciate your help and input on how to disable all formatting for the solidity extension. 

Thank you!

**Comment by juanfranblanco** [comment]
Prettier formater was included as a default formater a while ago, you may have a setting to Format File on Save in VsCode this might be your issue. 

![image](https://user-images.githubusercontent.com/562371/78008593-bbd64a00-7337-11ea-8992-51b84525be55.png)

**Comment by juanfranblanco** [comment]
You can disable formatting for that workspace on File save if you want too.

**Comment by juanfranblanco** [comment]
I have just added also the following option to disable the Solidity formatting.

![image](https://user-images.githubusercontent.com/562371/78027204-e5519e80-7354-11ea-9ee6-980d62e851a1.png)

**Comment by gitpusha** [comment]
@juanfranblanco Nice! Thank you very much. I disabled the Solidity: Formatter in the new settings and now I have what I need!
Thanks for the quick response and fix. Amazing!

BTW, I use Prettier for my JS stuff. I just think that the Soldidity Prettier Formatter does not cut it for me because it does weird formatting when compared to the guidelines laid out in the official [Solidity Style Guide.](https://solidity.readthedocs.io/en/latest/style-guide.html)

Do you work on the Solidity-Prettier project too or should I go raise an issue somewhere else ?

**Comment by juanfranblanco** [comment]
@gitpusha no I don't work on that project, so yes please raise that issue there. I mentioned it in a comment, but it deserves an issue, and surely your feedback. It is early stages for the prettier Solidity, but I believe is going to be "pretty" good.

**Comment by gitpusha** [comment]
Thanks for the great work. I really like the vscode-solidity extension and I ve been using it pretty much every day of the last year.

**Comment by juanfranblanco** [comment]
Thanks @gitpusha much appreciated!!
