### ISSUE TITLE
Very slow git in VSCode when vscode-solidity is running

### ISSUE THREAD

**Issue by theoturner** [juanfranblanco/vscode-solidity#173]
When using a repo containing `.sol` files with this extension, any git operations completed in VS Code are very slow, to the point of being unusable.

The problem stops after uninstalling the extension. A reinstall fixes the problem until VS Code is closed and re-opened.

With the extension installed, there are no problems in repos with no `.sol` files.

This has been a problem for approx. 2 months.

I am running WSL Ubuntu 18.04.

**Comment by juanfranblanco** [comment]
Yes it seems to be an issue with WSL and the extension, are you just using the vscode extension or are you using other plugins like the Azure.

**Comment by j-mars** [comment]
Seems like the same issue as me

**Comment by theoturner** [comment]
Just using the VSCode extension. Plain VSCode with vscode-solidity on WSL.

**Comment by juanfranblanco** [comment]
Can you check the latest version (not released) https://github.com/juanfranblanco/vscode-solidity/blob/master/solidity-0.0.73.vsix. This mainly disables the check when changing settings to cache the current compiler, i think wsl it is forcing to reload the settings in each new window instance.

**Comment by juanfranblanco** [comment]
I am closing this now, please reopen if needed
