### ISSUE TITLE
Remove override keyword when format

### ISSUE THREAD

**Issue by FilipLaurentiu** [juanfranblanco/vscode-solidity#174]
It remove override keyword automatic when format.
This is very annoying

**Comment by abcoathup** [comment]
Formatting a contract with the override keyword results in the override keyword being removed
## Unformatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public override {}
}
```
## Formatted
```solidity
pragma solidity ^0.6.0;


contract A {
    function doStuff() public virtual {}
}


contract B is A {
    function doStuff() public {}
}
```

I assume that the issue is potentially with `prettier-solidity` 
https://github.com/prettier-solidity/prettier-plugin-solidity/issues/277

**Comment by juanfranblanco** [comment]
Closing this has been fixed for a while
