### ISSUE TITLE
sol files formatting

### ISSUE THREAD

**Issue by gnom1gnom** [juanfranblanco/vscode-solidity#18]
Please enable code formatting for .sol files

**Comment by stylehuan** [comment]
+1

**Comment by AisinGioroHanani** [comment]
Single-line comments (//) and multi-line comments (/*...*/) are possible.

There are special types of comments called natspec comments (documentation yet to be written). These are introduced by triple-slash comments (///) or using double asterisks (/** ... */). Right in front of function declarations or statements, you can use doxygen-style tags inside them to document functions, annotate conditions for formal verification and provide a confirmation text that is shown to users if they want to invoke a function.

**Comment by juanfranblanco** [comment]
Integrated with prettier now
