### ISSUE TITLE
Something happened just made the connection to server got closed

### ISSUE THREAD

**Issue by N1028YuKi** [juanfranblanco/vscode-solidity#180]
![image](https://user-images.githubusercontent.com/28054559/83258509-f69a1880-a1e8-11ea-9a3a-af1f2e881f09.png)

My node version is v10.19.0, will this make the problem happen?

**Comment by juanfranblanco** [comment]
@N1028YuKi that is strange, what are your settings?

**Comment by N1028YuKi** [comment]
> @N1028YuKi that is strange, what are your settings?

Could this be a problem of WSL？I just find the wslhost.exe occupies the port 6009

**Comment by N1028YuKi** [comment]
Thanks for your attention anyway, it works after I delete all the settings and clean my development environment
