### ISSUE TITLE
Support autocomplete for functions from imported abstract contracts

### ISSUE THREAD

**Issue by abcoathup** [juanfranblanco/vscode-solidity#181]
Autocomplete works for functions from imported non-abstract contracts but doesn't appear to work for functions from imported abstract contracts.

In the example below, when typing `d` in `MyContract` only `doA` is shown from contract A as contract B is abstract.

<img width="458" alt="autocomplete" src="https://user-images.githubusercontent.com/28278242/83598719-c8805400-a5ad-11ea-95eb-541d7f047963.png">

## A.sol
```
// contracts/A.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;


contract A {
    function doA() internal {}
}
```
## B.sol
```
// contracts/B.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;


abstract contract B {
    function doB() internal {}
}
```
## MyContract.sol
```
// contracts/MyContract.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "./A.sol";
import "./B.sol";


contract MyContract is A, B {
    function doStuff() public {
       d...
    }
}
```

This was raised by a community member in the OpenZeppelin Community Forum: 
https://forum.openzeppelin.com/t/problem-about-auto-complete-when-using-solidity-plugin-with-vs-code/2997

**Comment by josh-richardson** [comment]
This is because the dependency [solparse](https://github.com/juanfranblanco/vscode-solidity/blob/master/package.json#L68) doesn't support the `abstract` keyword, meaning that abstract contracts tend to crash the language server when you try to interact with them.

**Comment by juanfranblanco** [comment]
Thanks @josh-richardson, yes that is correct. I was awaiting for the solidity team to release support for the language code server.
Now sadly they are not going to be able to support not failing over when there are not syntax mistakes. So yes fixing solparse is truly the simplest solution.

**Comment by josh-richardson** [comment]
> Thanks @josh-richardson, yes that is correct. I was awaiting for the solidity team to release support for the language code server.
> Now sadly they are not going to be able to support not failing over when there are not syntax mistakes. So yes fixing solparse is truly the simplest solution.

I'm currently working on a fix in my fork of this repo, but it might not be ready for a while.

**Comment by juanfranblanco** [comment]
If you point me out the direction I can have a look too if you don't have time, it can be a pull for solparse and include it here in the mean time. It is so sad that ethlint and solparse stopped.

**Comment by juanfranblanco** [comment]
Ok I have fixed this in the latest versions, please let me know if you have any issues.

**Comment by faea726** [comment]
I'm using the extension with Foundry.

When import IERC20 from `openzeppelin-contracts/contracts/interfaces/IERC20.sol`, it **cannot** suggest functions. But when import IERC20 from `openzeppelin-contracts/contracts/token/ERC20/IERC20.sol`, it can suggest smoothly.

This is just an example. Many places happen like that. Don't know if it's Foundry's issue or extension's issue. But I think it's the same as this issue.

**Comment by juanfranblanco** [comment]
What are your settings? It is supposed to work with both.

**Comment by faea726** [comment]
> What are your settings? It is supposed to work with both.

My VSCode settings:
```
  "[solidity]": {
    "editor.defaultFormatter": "JuanBlanco.solidity"
  },
  "solidity.packageDefaultDependenciesContractsDirectory": "src",
  "solidity.packageDefaultDependenciesDirectory": "lib",
  "solidity.formatter": "forge",
  "solidity.compileUsingRemoteVersion": "v0.8.25",
```
Project layout is similar to Foundry's template.
