### ISSUE TITLE
Bug: Filepath displayed inside the bytecode

### ISSUE THREAD

**Issue by joaosantos15** [juanfranblanco/vscode-solidity#182]
While running the Metacoin contract with compiler version `0.4.23` I noticed that inside the `contracts["Metacoin.sol"].evm.bytecode.object` a portion of the file path was inside the bytecode and compiled bytecode. I tried this with some other 0.4.x versions of the compiler and had the same issue. Curiously, it happens way less often in 0.5.x versions.
See screenshot below taken from the vscode debug console.
![Screenshot 2020-06-08 at 12 14 49](https://user-images.githubusercontent.com/10178757/84154898-92384e00-aa5f-11ea-85b9-7be2b593f704.jpg)

OS: MacOS 10.15.4
NodeJS: v11.13.0 (with NVM) 
VSCode version: 1.45.1

**Comment by juanfranblanco** [comment]
@joaosantos15 this is due to referencing libraries, these need to be replaced later on with the library contract address

**Comment by Sharonbyrne** [comment]
Hi Juan would you be able to have a call tomorrow June 16th at 2pm GMT? Ping me on sharon.byrne-cotter@consensys.net. Txs so much !

**Comment by Sharonbyrne** [comment]
Hi @joaosantos15 would you be able to have a call tomorrow June 17th at 3pm GMT? Please ping me on sharon.byrne-cotter@consensys.net. Txs so much !
