### ISSUE TITLE
Calldata wrong syntax highlighting

### ISSUE THREAD

**Issue by rrodriguezreche** [juanfranblanco/vscode-solidity#185]
All of a sudden I am getting my calldata variables wrongly highlighted as errors.
Example:

```
function foo(bytes calldata bar) external {
        baz = bar;
    }
```

The keyword `calldata` is not being recognized, `memory` and `storage` are ok. The plugin believes calldata is actually a variable identifier, and throws a `Expected ',' but got identifier`.

**Comment by juanfranblanco** [comment]
This is working now. Thanks for the report.
