### ISSUE TITLE
SPDX license identifier warning

### ISSUE THREAD

**Issue by skiv71** [juanfranblanco/vscode-solidity#189]
Hi, I have a custom build process and I'd like a way to get the plugin to ignore this, as my deployed (and flattened source) has them inserted, as well as other build info.  I've checked the docs (and the running config) and it appears as if the plugin is using neither solhint or (the other one). Thanks

**Comment by juanfranblanco** [comment]
That is a warning / error of the solc compiler

**Comment by skiv71** [comment]
Ah, appreciate the feedback... I'll go looking to see if it permits a config to ignore this, thanks

**Comment by juanfranblanco** [comment]
No worries, I guess that a feature that could be added to the plugin is to "filter" those warnings from the compiler.

**Comment by JetDeveloping** [comment]
Hey there! Was this ever implemented?

**Comment by juanfranblanco** [comment]
@JetDeveloping no, I asked around and there was not much uptake on this feature.

**Comment by juanfranblanco** [comment]
Continuing with this thread, it could be interesting to filter some specific warnings from the compiler, defined by the user.
