### ISSUE TITLE
Possible issue compiling after VSCode 1.9.0 upgrade

### ISSUE THREAD

**Issue by mattcrooks** [juanfranblanco/vscode-solidity#19]
Hi,
I'm not sure if anyone else is experiencing this issue but following VSCode update to 1.9.0 the following issue appeared when compiling contracts that previously compiled.

`There was an error loading the remote version: undefined`

![image](https://cloud.githubusercontent.com/assets/2180781/22679324/663605c4-ed55-11e6-8df7-b1f0ebb53b60.png)

I fixed this by specifying the following (in user settings)
    "solidity.compileUsingRemoteVersion": "v0.4.4+commit.4633f3de" 
//v0.4.9+commit.364da425

Again not sure if this is something others are seeing but thought I'd note it.

**Comment by juanfranblanco** [comment]
Fixed on 21
