### ISSUE TITLE
carshed 5 times

### ISSUE THREAD

**Issue by nazariyv** [juanfranblanco/vscode-solidity#190]
This is the output of the language server

```
TypeError: soljson.cwrap is not a function
TypeError: soljson.cwrap is not a function
/Users/shredder/.vscode/extensions/juanblanco.solidity-0.0.76/node_modules/solc/soljson.js:1
null;var Module=typeof Module!=="undefined"?Module:{};var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var arguments_=[];var thisProgram="./this.program";var quit_=function(status,toThrow){throw toThrow};var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof process.versions==="object"&&typeof process.versions.node==="string";ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;var scriptDirectory="";function locateFile(path){if(Module["locateFile"]){return Module["locateFile"](path,scriptDirectory)}return scriptDirectory+path}var read_,readAsync,readBinary,setWindowTitle;var nodeFS;var nodePath;if(EN

RuntimeError: abort(TypeError: soljson.cwrap is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/shredder/.vscode/extensions/juanblanco.solidity-0.0.76/node_modules/solc/soljson.js:1:13938)
    at process.emit (events.js:223:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
[Info  - 11:42:41] Connection to server got closed. Server will restart.
```

**Comment by juanfranblanco** [comment]
@nazariyv what are your settings? Have you put the right version of solidity? Any other extensions installed?

**Comment by nazariyv** [comment]
wow, thank you so much for such a quick response!

the only settings (global; I have no local settings) I have:

```
  "solidity.enabledAsYouTypeCompilationErrorCheck": true,
  "solidity.validationDelay": 1500,
  "solidity.compileUsingRemoteVersion": "v0.6.6"
```

other extensions:
hosho.solidity-debugger
tintinweb.solidity-visual-auditor
tintinweb.vscode-solidity-flattener
tintinweb.vscode-ethover

**Comment by nazariyv** [comment]
and I have no globally installed solidity binary (I am on a Mac)

**Comment by nazariyv** [comment]
I can confirm that removing all those extensions does not resolve the issue

**Comment by juanfranblanco** [comment]
"wow, thank you so much for such a quick response!", I got a notification this time :). Normally i don't.

that is the wrong version as it needs the whole commit information  ```solidity.compileUsingRemoteVersion": "v0.6.6"``` 
check here: https://github.com/ethereum/solc-bin/tree/gh-pages/bin
```v0.6.6+commit.6c089d02```

the best way to change version is to right click on a solidity file and use the prompt to select the version you want.

**Comment by juanfranblanco** [comment]
https://github.com/juanfranblanco/vscode-solidity/issues/188#issuecomment-671414867

**Comment by nazariyv** [comment]
works :) Thank you! You have saved me a ton of time :) And thank you very much for this awesome extension :)

**Comment by wighawag** [comment]
I am getting a similar error with 0.7.3
it works with 0.7.1

Could it be related to solidity switching to static linked executable (no mor zip files) ?
