### ISSUE TITLE
"Visibility for constructor is ignored" yet removing the visibility causes compiler error

### ISSUE THREAD

**Issue by deluca-mike** [juanfranblanco/vscode-solidity#192]
`constructor() public {}`

`Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.`

Yet, if the constructor is changed to: `constructor() {}`, the warning goes away, but the compiler gives:

```
CompileError: ... SyntaxError: No visibility specified. Did you intend to add "public"?
  constructor() {}
  ^--------------^

Compilation failed. See above.
```

**Comment by juanfranblanco** [comment]
You need to add a visibility, this is an error of the compiler.
