### ISSUE TITLE
Source "truffle/Assert.sol" not found: File import callback not supported

### ISSUE THREAD

**Issue by zhouhanseng** [juanfranblanco/vscode-solidity#193]
I am learning solidity from https://www.trufflesuite.com/tutorials/pet-shop, I installed the vscode-solidity, it reflects a problem:

![image](https://user-images.githubusercontent.com/63733714/94820488-19586a00-0433-11eb-9ab7-e404e1bf5ee5.png)

But actually there's no problem:

![image](https://user-images.githubusercontent.com/63733714/94820545-2b3a0d00-0433-11eb-9efe-d5a39940774a.png)

**Comment by juanfranblanco** [comment]
Hi,

Yes Truffle embeds those supporting test contracts as part of their CLI tool, so the IDE cannot find them.

**Comment by zhouhanseng** [comment]
How about adding a workaround for Truffle？

**Comment by juanfranblanco** [comment]
Closing this, ideally Truffle will provide the Assert files but we have tried and is not a simple solution

**Comment by PatrickAlphaC** [comment]
Could we reopen this? We see the same issue with [brownie](https://github.com/eth-brownie/brownie) and it's really annoying.

Perhaps just add an "ignore" quick fix?

**Comment by juanfranblanco** [comment]
Ignore the whole file?

**Comment by PatrickAlphaC** [comment]
No, just add an option to ignore these red lines popping up with this specific error. Maybe an option in the settings to disable these warnings. 

IE:

```
Disable File import callback not supported: True
```

**Comment by juanfranblanco** [comment]
No, that would not work that is a generic error for all files that cannot be found. This is just the first error, as later on will not be able to identify other parts of the test contract like Assert.

**Comment by PatrickAlphaC** [comment]
Well this error will be for all truffle and brownie projects... And it will just always be there. It will never find the files in brownie. 

I don't use the solidity testing suite often, often we use the truffle or brownie javascript/python. I think it's fine for this purpose to ignore this error no?

**Comment by juanfranblanco** [comment]
What it can be done is to ignore all file. (Compilation / validation errors). Maybe a comment (vscode-solidity-compilation-check-ignore) Which will disregard the whole file, but allow for elements of autocomplete etc.

**Comment by PatrickAlphaC** [comment]
^^^ That sounds wonderful :D
