### ISSUE TITLE
Call to external contract via interface makes it impossible to go to import definitions

### ISSUE THREAD

**Issue by Orbsynated** [juanfranblanco/vscode-solidity#194]
As the title suggests, whenever I type a function call to external contract via an interface, it doesn't let me from that point forward to go to/peek any import definitions.
Consider this contract:

```
// SPDX-License-Identifier: NOLICENSE
pragma solidity ^0.7.2;
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

interface TestInterface {
    function testFunction(uint256 someVar) external payable returns (uint256 someVar2);
}

contract testContract is ERC20("TestToken", "TT") {

    constructor() public {}

    function testFunction() public {
        address testAddress = address(0);
        TestInterface(testAddress).testFunction{value: 1}(42);
    }
}
```

Now when I try to go to/peek the ERC20 definition it doesn't work and this is what is written in the logs:

`[Error - 17:49:01] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Expected "!=", "%", "%=", "&", "&&", "&=", "(", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", ".", "/", "/*", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", ">>>", "?", "[", "^", "^=", "|", "|=", "||", comment, end of line, or whitespace but "{" found. Line: 16, Column: 48
  Code: -32603 `

Is this a bug or am I doing something wrong?

OS: Windows 10 64 bit v2004
NodeJS: v11.16.3
VSCode version: 1.49.3

**Comment by juanfranblanco** [comment]
Yes this is an issue with new solidity keywords. I started the rewrite of the solidity language server to help on these issues, but the currently the solidity team are working on that too, so the fix has been postponed until they release their version as it will be universal for all IDEs (which is great :) )

**Comment by juanfranblanco** [comment]
I have fixed the parser and interfaces are supported now. Please let me know if you encounter other issues as I am using Peg.js instead of Antlr.
