### ISSUE TITLE
Compiling works, but no resulting files or directories

### ISSUE THREAD

**Issue by deluca-mike** [juanfranblanco/vscode-solidity#196]
As per title, despite compiling working, there are no resulting files or directories created within the project.

**Comment by juanfranblanco** [comment]
@deluca-mike Hi, have you opened a workspace or folder?

**Comment by deluca-mike** [comment]
Workspace.

**Comment by juanfranblanco** [comment]
Strange, what is your folder structure.. this is only an issue when no workspace or folder is open as it cannot allocate a compilation folder.

**Comment by juanfranblanco** [comment]
I have not been able to replicate this, please re-open if is still an issue.
