### ISSUE TITLE
Support solidity 0.7.0 format

### ISSUE THREAD

**Issue by thbourlove** [juanfranblanco/vscode-solidity#199]
https://github.com/prettier-solidity/prettier-plugin-solidity/issues/310

We should upgrade our prettier-plugin-solidity to 1.0.0-alpha.56 for supporting solidity 0.7.0 right now.

**Comment by juanfranblanco** [comment]
Sure, apologies I missed this.

**Comment by TransmissionsDev** [comment]
Bump!

**Comment by juanfranblanco** [comment]
Latest beta is there now
