### ISSUE TITLE
Seems to hijack F5 in non-Solidity projects

### ISSUE THREAD

**Issue by coreyog** [juanfranblanco/vscode-solidity#20]
I have a lot of projects I use VSCode for. Some Solidity/Ethereum, some not. For example if I'm in a Go project and hit F5 to debug it, I get the following warning:

![image](https://cloud.githubusercontent.com/assets/2836207/23630653/1b3b0f54-0279-11e7-929a-65869be19dea.png)

It seems your plugin hijacks F5 for all projects even those that have nothing to do with Solidity. The only approach I have is to disable your plugin for every workspace that isn't Solidity-based or going to the debug UI using the mouse. I would suggest finding a way to let VSCode's own task runner compile solidity instead of commandeering a pretty common hotkey.

**Comment by wojo** [comment]
Created a PR to get the binding to only match when the file open is a Solidity type. 

Looked into the task runners, but I don't think it's currently possible to execute code within the extension as a part of the tasks.json. Will take a look a little more later, but may need to split the code out and run it via node for example.

**Comment by juanfranblanco** [comment]
Thanks for the PR again :)
