### ISSUE TITLE
Vscode solidity can only prompt keywords

### ISSUE THREAD

**Issue by huwentao1** [juanfranblanco/vscode-solidity#200]
Vscode solidity can only prompt keywords
![image](https://user-images.githubusercontent.com/43719888/99752455-52ea4f00-2b1f-11eb-851c-eb6c19617e39.png)
this is my solidity config, my version is v0.0.76, is my config error ?
![image](https://user-images.githubusercontent.com/43719888/99752541-7d3c0c80-2b1f-11eb-8ff1-597ded2b0495.png)

**Comment by juanfranblanco** [comment]
Hi apologies for that, autocomplete is not working at the moment as I am awaiting to the new language server in solidity, to replace the current parser. cc @chriseth ;)

**Comment by huwentao1** [comment]
> Hi apologies for that, autocomplete is not working at the moment as I am awaiting to the new language server in solidity, to replace the current parser. cc @chriseth ;)

That's it~ For this situation, is there currently an auto-completion plugin available? Or how long does it take your plug-in to realize this function?

**Comment by juanfranblanco** [comment]
No there is not a plugin available, the whole point is that if this is done in solidity it will be available by other IDEs. For me to do this, it will take I guess a week or two.

**Comment by chriseth** [comment]
@juanfranblanco sorry to disappoint you, but we do not plan to make the LSP cope with incorrect source.

**Comment by juanfranblanco** [comment]
@chriseth ohhh so it wont work for autocomplete then? what features are you thinking?

**Comment by chriseth** [comment]
go to definition is the first goal we will implement

**Comment by juanfranblanco** [comment]
ah nice, i was half way through that in typescript, antlr is a slight pain as you cannot filter easily.

**Comment by juanfranblanco** [comment]
@chriseth huwentao1 I introduced an experimental package for solparse that includes abstract, receive and fallback statement support which were the ones breaking the plugin. My guess, is for now the best is to continue this way until the perfect solution is there, ill push fixes to solparse which is mainly pegjs. Obviously this retuns the idea of having constant support for pegjs, and looking at the current g4 file, I can see yul there too :). So this might require a conversation.

**Comment by chriseth** [comment]
I'm not sure I understand what you are talking about, but feel free to schedule a meeting.

**Comment by juanfranblanco** [comment]
Closing this as autcomplete is "working" now, there are many features missing, but those should be specific issues and resolve one by one. To name a few: dot autocompletion of struct properties, array support on library extensions.
