### ISSUE TITLE
Extension is not working on Ubuntu

### ISSUE THREAD

**Issue by Dmdv** [juanfranblanco/vscode-solidity#202]
Hi Juan, 
There's another issue

**VSCode Version**: 1.51.1
**OS Version: Ubuntu** 20.04.1 LTS
Steps to Reproduce:

1.Install VS Code on Ubuntu (via application hub or via snap)
2.Install extension: ```ext install JuanBlanco.solidity```

Symptoms are:

The extension is installed but shows no signs of life:
- No context menu
- No syntax highlighting

**Comment by juanfranblanco** [comment]
I need to recreate my vm to test this, i don't think running wsl2 will help on the test.

**Comment by juanfranblanco** [comment]
Brand new image 
![image](https://user-images.githubusercontent.com/562371/101775325-353d5380-3ae7-11eb-9834-97e2eb7789b1.png)

**Comment by Dmdv** [comment]
@juanfranblanco Yes, I restarted it
How did you install vscode? Through app hub or other?

**Comment by Dmdv** [comment]
@juanfranblanco 
I fixed it
I had to remove the while $HOME/.vscode folder and vs code
Then I installed vscode from snap and installed the extension again and it worked

**Comment by juanfranblanco** [comment]
@Dmdv I think i did it through app hub. But yes it seems that the installation was broken, somehow.
