### ISSUE TITLE
Does this plugin have a working linter?

### ISSUE THREAD

**Issue by stoplion** [juanfranblanco/vscode-solidity#203]
Does this plugin have a working linter?

I've followed the instructions and I'm not seeing anything in VSCode.

**Comment by juanfranblanco** [comment]
@stoplion some shots, that might help
![image](https://user-images.githubusercontent.com/562371/102696934-e94a8700-4229-11eb-9046-fe59ede5cc54.png)
![image](https://user-images.githubusercontent.com/562371/102696939-f9fafd00-4229-11eb-9015-b9756f551578.png)
