### ISSUE TITLE
0.8.0 Errors

### ISSUE THREAD

**Issue by vSterlin** [juanfranblanco/vscode-solidity#205]
When I use default compiler version the error highlighting works, however when I switch to the latest it does not.
<img width="799" alt="Screen Shot 2021-01-06 at 12 29 50 AM" src="https://user-images.githubusercontent.com/49332792/103746801-82152c80-4fb6-11eb-89c6-26788ac997f4.png">
<img width="799" alt="Screen Shot 2021-01-06 at 12 30 56 AM" src="https://user-images.githubusercontent.com/49332792/103746803-83def000-4fb6-11eb-97b3-63b68319570b.png">

**Comment by juanfranblanco** [comment]
Should be fixed now, upgrade to latest
