### ISSUE TITLE
The Solidity Language Server server constantly crashes in VS Code

### ISSUE THREAD

**Issue by pcaversaccio** [juanfranblanco/vscode-solidity#206]
Whenever I open a solidity project in VS Code I get the following error:
`The Solidity Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.` - Does anyone experience the same behaviour?

**Comment by juanfranblanco** [comment]
@pcaversaccio have you got a workspace / folder open? Any shot of your environment?

**Comment by pcaversaccio** [comment]
@juanfranblanco what exactly do you need? I will try to provide all the information that gives you the best insights.

**Comment by pcaversaccio** [comment]
One repository I currently use is this one: https://github.com/pcaversaccio/startfeld-token-contract

**Comment by juanfranblanco** [comment]
cool ill have a look at that one

**Comment by pcaversaccio** [comment]
Are there any logs I can provide you?

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/104055197-406ac880-51e6-11eb-8677-dbac806e3e20.png)

**Comment by juanfranblanco** [comment]
@pcaversaccio  try disabling solium in the settings, mainly not using any linter.

**Comment by pcaversaccio** [comment]
![image](https://user-images.githubusercontent.com/25297591/104057115-dc4e0180-51f1-11eb-9a86-a67b624d0835.png)
How is this possible? Can't disable it somehow.

**Comment by juanfranblanco** [comment]
Select the empty option. Did you have solhint selected?

**Comment by pcaversaccio** [comment]
Disabled but still crashing. Yes solhint was selected previously and not Solium.

**Comment by juanfranblanco** [comment]
hmm the log just had items of solium and i guess azure workbench (blockchain)

**Comment by pcaversaccio** [comment]
could it be that another extension is triggering this problem?

**Comment by juanfranblanco** [comment]
It might be,  does it crash straight away?

**Comment by pcaversaccio** [comment]
No, it first loads the extension and then crashes. You see it here:
![image](https://user-images.githubusercontent.com/25297591/104057969-45824480-51f3-11eb-8219-3019c2e8bffd.png)

**Comment by juanfranblanco** [comment]
Yes, it takes to time to activate the language server.. i was testing it just yesterday in a low spec pc

**Comment by juanfranblanco** [comment]
Can you test it in another pc? or remove extra extensions?

**Comment by pcaversaccio** [comment]
I disabled all extensions except the solidity one. Still getting the error.
![image](https://user-images.githubusercontent.com/25297591/104059776-22a55f80-51f6-11eb-813a-283d38a83d2c.png)

**Comment by juanfranblanco** [comment]
Wow 30 extensions !! can you post your settings file? What compiler are you using?

**Comment by pcaversaccio** [comment]
yes, many different projects running - but I disabled all of them for the testing. I used the latest compiler always.

```
{
    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "node_modules",
    "git.autofetch": true,
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "python.pythonPath": "C:\\Users\\pasca\\Anaconda3",
    "workbench.colorTheme": "Solarized Dark",
    "beautify.config": "",
    "window.zoomLevel": 0,
    "yaml.schemas": {
        
    
    },
    "C_Cpp.default.browse.path": [],
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Pylance",
    "java.home": "",
    "java.project.importOnFirstTimeStartup": "automatic",
    "java.imports.gradle.wrapper.checksums": [
        {
            "sha256": "0bd54338d98c18b89bb7dd52103877bfef671267751e43d688680af6abf27428",
            "allowed": true
        }
    ],
    "solidity.compileUsingRemoteVersion": "latest",
    "solidity.compileUsingLocalVersion": "latest",
    "jupyter.askForKernelRestart": false,
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ]
}
```

**Comment by juanfranblanco** [comment]
ok "solidity.compileUsingLocalVersion": "latest" is incorrect

**Comment by pcaversaccio** [comment]
Seems to work now! Thanks a lot. Oh boy, VS Code settings are just a nightmare... 
![image](https://user-images.githubusercontent.com/25297591/104061977-df4cf000-51f9-11eb-8a7c-01fd3b014537.png)

**Comment by juanfranblanco** [comment]
Great!!! To change the compiler version just right click on the solidity file (only for remote, but it is much simpler now).

**Comment by pcaversaccio** [comment]
Ok perfect. Have a great weekend!
