### ISSUE TITLE
Issue with openzeppelin ERC721 contract when compiling to C#

### ISSUE THREAD

**Issue by siskender** [juanfranblanco/vscode-solidity#211]
GIVEN
```javasscript
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.6.0 <0.9.0;

import "../node_modules/@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract TstNonFungibleToken is ERC721 {   
    constructor() ERC721("Test","TST") {
    }
}
```
THEN "Compile and code generate CSharp contract definition"
WILL Give the following error in the generated service (TstNonFungibleTokenService.cs):
![image](https://user-images.githubusercontent.com/8503234/105706965-84620b00-5f12-11eb-810b-e20563c12704.png)
And the following error in the generated definition (TstNonFungibleTokenDeployment.cs):
![image](https://user-images.githubusercontent.com/8503234/105707089-b1aeb900-5f12-11eb-8167-3f7281c32fde.png)

**Comment by juanfranblanco** [comment]
Yes I am aware of that thanks!!

**Comment by siskender** [comment]
Any ideas whether these issues are fixable? If so when can we expect a fix? :-)

**Comment by juanfranblanco** [comment]
Yes there is a small fix implemented in a pull, but it needs further work before i release as it is a big breaking change. Once I release the first Nethereum templates I will get to work on that (as I want to add extra stuff for code generation)

**Comment by juanfranblanco** [comment]
Fixed now !!
