### ISSUE TITLE
Issue with openzeppelin contract when generating a function with return type as int and no modfier

### ISSUE THREAD

**Issue by siskender** [juanfranblanco/vscode-solidity#212]
GIVEN
```javascript
// SPDX-License-Identifier: GPL-3.0
pragma solidity >=0.6.0 <0.9.0;

import "../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract TstNonFungibleToken is ERC20 {   
    constructor() public ERC20("Bla", "BLA") {}

    function getWithView() public view returns (int)
    {
        return 1;
    }

    function getWithoutView() public returns (int)
    {
        return 1;
    }
}
```
THEN "Compile and code generate CSharp contract definition"
WILL generate the definitions with a **string** as return type for the get function without the **view** modifier:
![image](https://user-images.githubusercontent.com/8503234/105708993-719d0580-5f15-11eb-86f0-dccb1847c0b7.png)

**Comment by siskender** [comment]
Probably the function without view is seen as a transaction.

**Comment by juanfranblanco** [comment]
Yes, the service categorizes it as such, views are queries otherwise transactions (this avoids lots of noise) But you can use the Function Messages directly to do either.
