### ISSUE TITLE
add support for autocomplete

### ISSUE THREAD

**Issue by thegostep** [juanfranblanco/vscode-solidity#214]
Not sure how difficult this is to implement, but would be nice to have function / variables autocomplete based on default language + imports + libraries.

**Comment by juanfranblanco** [comment]
@thegostep  hi!! can you provide an example? Im a bit slow today :)

**Comment by juanfranblanco** [comment]
@thegostep you should get autocomplete for most stuff (if the parser does not break), structs, functions (inherited), using, smart contracts (declared), functions that return smart contracts..

There are some areas that are yet to be implemented, for example InterfaceContract(address).methodName won't autocomplete.

**Comment by thegostep** [comment]
Oh nice ! I'll have to debug why interface autocompletion is not showing up for me.

A related suggestion would be to display the function parameter name and types as a hint to avoid the need to refer back to the source file.

**Comment by juanfranblanco** [comment]
It does that too, you need to expand the method name. Although a tooltip will be good eventually on hover like go-to definition. But I guess the best would be to add extra discovery to go-to definition first.

**Comment by juanfranblanco** [comment]
@thegostep ah did you have multiple interface inheritance? interface inheriting interface? I believe I fixed that now.

**Comment by thegostep** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/15959632/106756724-907a5680-65fd-11eb-976d-df07261520d7.png">

**Comment by thegostep** [comment]
Yep - looks like it works now

**Comment by thegostep** [comment]
one more suggestion would be to look into node_modules for imports

so for example pick up the ERC20 and ERC20Burnable imports and fill 
<img width="535" alt="image" src="https://user-images.githubusercontent.com/15959632/106757033-e818c200-65fd-11eb-883e-0a4493442ada.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/15959632/106756959-d3d4c500-65fd-11eb-8a6a-e23dedaf2452.png">

**Comment by juanfranblanco** [comment]
@thegostep have you got it configured as follows?

![image](https://user-images.githubusercontent.com/562371/106757453-435faa00-6628-11eb-91da-b6fcca252b09.png)

**Comment by thegostep** [comment]
yes!

**Comment by juanfranblanco** [comment]
Ah, let me check your syntax it might be breaking the lookup.

**Comment by thegostep** [comment]
I wish it showed up in this list and I could press enter to populate the import

<img width="452" alt="image" src="https://user-images.githubusercontent.com/15959632/106761338-b6eec080-6602-11eb-8cd6-1e825d04f8a7.png">

**Comment by juanfranblanco** [comment]
@thegostep yes I got you, i think the best approach will be to populate the sol files for import, and then specify the contract name if wanted, as that will be autocompleted anyway. I will do it in the next round of vscode :)

**Comment by juanfranblanco** [comment]
@thegostep check the latest let me know how it goes.. import(space)Ctrl+Space

**Comment by thegostep** [comment]
looks good - one suggestion would be to allow for importing a specific contract from a file

```solidity
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
```

this is particularly useful to avoid file size bloat and makes using interfaces a joy

**Comment by juanfranblanco** [comment]
Yes, I cannot do that as it will mean parsing all the files (which it will be slower). What you can do is once you have typed the "file", that file will be parsed and the contract be part of the autocompletion list

**Comment by juanfranblanco** [comment]
I know is a bit of back and fordward

![importContract](https://user-images.githubusercontent.com/562371/107052728-e7328c80-67c5-11eb-86d1-15c5b5088c31.gif)

**Comment by smye** [comment]
Hello!

Would you happen to know why the autocompletion doesn't work for interfaces used in FlashLoanV2.sol from the Brownie mix?
https://github.com/brownie-mix/aave-flashloan-mix

Creating a minified file in the same directory:

![image](https://user-images.githubusercontent.com/17861005/120571267-a95f1100-c411-11eb-91e4-8eb516a28908.png)

Thank you

**Comment by juanfranblanco** [comment]
@smye maybe the parser is breaking there.. ill have a look.

**Comment by juanfranblanco** [comment]
Seems ok here:
![image](https://user-images.githubusercontent.com/562371/120637343-ae9a7b00-c466-11eb-8c29-b963d541085b.png)

**Comment by juanfranblanco** [comment]
@smye  ^^ have you got any other errors in the file?

**Comment by smye** [comment]
> @smye ^^ have you got any other errors in the file?

Hello thanks for the reply. After a bit of tweaking, I found the culprit. 
![image](https://user-images.githubusercontent.com/17861005/120651801-0f31b400-c477-11eb-96ee-07b25c0cf17e.png)
Appears it breaks when adding underscores to number literals

**Comment by juanfranblanco** [comment]
@smye Thank you!!

**Comment by juanfranblanco** [comment]
@smye should be fixed now, and also yesterday (although yesterday's was unintentional)

**Comment by smye** [comment]
> @smye should be fixed now, and also yesterday (although yesterday's was unintentional)

Awesome - thanks a lot!

Can confirm it's working on my end too

**Comment by juanfranblanco** [comment]
I am closing this now, as we have specific issues for Autocomplete
