### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by thegostep** [juanfranblanco/vscode-solidity#216]
https://docs.soliditylang.org/en/v0.7.6/types.html#unicode-literals

<img width="678" alt="image" src="https://user-images.githubusercontent.com/15959632/106761451-d5ed5280-6602-11eb-9a58-c1c8a75dca4d.png">

**Comment by juanfranblanco** [comment]
@thegostep it should be available (well the autocomplete in the latest), the solhint guys have fixed the linter now :)
