### ISSUE TITLE
Extension host terminates unexpectedly after upgrading to MACOS11.2 Big Sur

### ISSUE THREAD

**Issue by Prufio** [juanfranblanco/vscode-solidity#217]
VSCODE Version: 1.53.0-insider
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T15:54:30.646Z (23 hrs ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 20.3.0

Was on big sur 11.1, worked fine today. immediately after 11.2 upgrade , I get this when opening any .sol file :

workbench.desktop.main.js:1734 Extension host terminated unexpectedly. Code:  null  Signal:  SIGTRAP
_onExtensionHostCrashed @ workbench.desktop.main.js:1734
workbench.desktop.main.js:618   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, vscode.debug-auto-launch, vscode.git, ms-vscode.js-debug, vscode.github-authentication, vscode.github, vscode.emmet, vscode.merge-conflict, vscode.testing-editor-contributions, JuanBlanco.solidity

Tried installing different versions of the plugin going back 30 days- same result.

All other language etc extensions seem to work correctly (I uninstalled them for testing this though)

VSCODE mainline (x86) is working (slowly :/ ) under rosetta2 My issues with this were resolved by uninstalling, careful removal of all associated files, and reinstalling.

It is interesting though that the 11.2 big sur upgrade also broke this version, which was working fine prior to the change. I wonder if the reasons are related?

I Also tried the same cleanup and reinstall with insiders - no change. I have seen on forums that others are having similar issues.

THIS PART OF MY ORIGINAL REPORT IS NOT CORRECT (was resolved):
                        Tried different vscode insider installs (intel, universal, arm) versions - same result
                        
                        tried fresh install of vscode release Version: 1.52.1
                        Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
                        Date: 2020-12-16T16:30:02.420Z (1 mo ago)
                        Electron: 9.3.5
                        Chrome: 83.0.4103.122
                        Node.js: 12.14.1
                        V8: 8.3.110.13-electron.0
                        OS: Darwin x64 20.3.0
                        
                        This gets: The Solidity Language Server server crashed 5 times in the last 3
                         minutes. The server will not be restarted.

**Comment by juanfranblanco** [comment]
@Prufio can you go to .vscode/extensions/juanblanco.solidity-0.0.106 and delete your soljson files? Random thought.

**Comment by Prufio** [comment]
> @Prufio can you go to .vscode/extensions/juanblanco.solidity-0.0.106 and delete your soljson files? Random thought

running 107 now with arm-native insiders, tried deleting soljson files - still the same issue.

The extension host crashes only when opening solidity files, and crashes a couple of seconds after the syntax highlighting is done (colorized) without any further user action.

I am using 107 with mainline vscode (not insiders) and it is working, but very slow in comparison, of course (running under x86 emulation) 

The interesting thing to me is that it worked flawlessly (and very, very fast!) before the 11.2 upgrade :/

This is the dump I get from the dev console:

workbench.desktop.main.js:sourcemap:2658 Extension Host
workbench.desktop.main.js:sourcemap:2658 ## Fatal error in , line 0# ignored####FailureMessage Object: 0x16f23daf8 1: 0x1034908f8 node::MultiIsolatePlatform::CancelPendingDelayedTasks(v8::Isolate*) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 2: 0x10580e174 v8::internal::compiler::ZoneStats::GetCurrentAllocatedBytes() const [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 3: 0x1044350fc v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 4: 0x1018f8368 v8::internal::wasm::NativeModule::AddCodeSpace(v8::base::AddressRegion, v8::internal::wasm::WasmCodeAllocator::OptionalLock const&) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 5: 0x1044363f0 v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 6: 0x104443c0c v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 7: 0x104442524 v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 8: 0x10444338c v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework] 9: 0x104443458 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]10: 0x10348f3ac node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]11: 0x10348e340 node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]12: 0x100d1e32c uv_async_send [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]13: 0x100d2e6c8 uv_free_interface_addresses [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]14: 0x100d1e768 uv_run [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]15: 0x100ea1ea0 ElectronInitializeICUandStartNode [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]16: 0x100d2ed4c ElectronInitializeICUandStartNode [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]17: 0x100bba9f8  [/private/var/folders/5j/ntpy9gp15vq9kjzffkx5qpqr0000gn/T/AppTranslocation/7EAFE4F7-3B93-40A6-A0B3-7D071BF305A6/d/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/Code - Insiders Helper (Renderer)]18: 0x18ac3df34 start [/usr/lib/system/libdyld.dylib]
workbench.desktop.main.js:sourcemap:1734 Extension host terminated unexpectedly. Code:  null  Signal:  SIGTRAP
_onExtensionHostCrashed @ workbench.desktop.main.js:sourcemap:1734
workbench.desktop.main.js:sourcemap:618   ERR Extension host terminated unexpectedly. The following extensions were running: vscode.microsoft-authentication, JuanBlanco.solidity, vscode.debug-auto-launch, vscode.git, ms-vscode.js-debug, vscode.github-authentication, vscode.github, vscode.emmet, vscode.merge-conflict, vscode.testing-editor-contributions
workbench.desktop.main.js:sourcemap:738 Extension host terminated unexpectedly.
onDidChangeNotification @ workbench.desktop.main.js:sourcemap:738

**Comment by Prufio** [comment]
Still same issue with0.0.112

**Comment by Prufio** [comment]
Issue seems to have been resolved with vscode 1.55 MAC arm64

**Comment by juanfranblanco** [comment]
@Prufio fantastic, i was so confused as it was working on my Mac, I did not know about the issues with vscode and the specific version for arm64. Nice to know for future reference.
