### ISSUE TITLE
language server crash

### ISSUE THREAD

**Issue by hellodword** [juanfranblanco/vscode-solidity#218]
I followed the [quickstart](https://www.trufflesuite.com/docs/truffle/quickstart), but always got:

```
RuntimeError: abort(TypeError: soljson.cwrap is not a function). Build with -s ASSERTIONS=1 for more info.
    at process.abort ($.vscode\extensions\juanblanco.solidity-0.0.106\node_modules\solc\soljson.js:1:13939)
    at process.emit (events.js:315:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
[Error - 下午10:56:56] Connection to server got closed. Server will not be restarted.
```

```sh
npm install truffle -g
mkdir MetaCoin
cd MetaCoin
truffle unbox metacoin
code .
```

> truffle version
```
Truffle v5.1.65 (core: 5.1.65)
Solidity v0.5.16 (solc-js)
Node v12.18.4
Web3.js v1.2.9
```
> .vscode\settings.json

```json
{
    "workbench.colorCustomizations": {
        "activityBar.background": "#23311C",
        "titleBar.activeBackground": "#314527",
        "titleBar.activeForeground": "#FAFBF9"
    },
    "solidity.compileUsingRemoteVersion": "v0.6.11+commit.5ef660b1"
}
```

And I use `Solidity: Change workspace compiler version (Remote)` to switch version & restart vscode for several times, but it still got that.

**Comment by juanfranblanco** [comment]
Hi @hellodword, can you make sure that the setting solidity.enableLocalNodeCompiler": false is set to false?

**Comment by hellodword** [comment]
> Hi @hellodword, can you make sure that the setting solidity.enableLocalNodeCompiler": false is set to false?

Thanks @juanfranblanco. And yes I added this but it still crash.

```json
{
    "workbench.colorCustomizations": {
        "activityBar.background": "#23311C",
        "titleBar.activeBackground": "#314527",
        "titleBar.activeForeground": "#FAFBF9"
    },
    "solidity.compileUsingRemoteVersion": "v0.6.11+commit.5ef660b1",
    "solidity.enableLocalNodeCompiler": false
}
```

**Comment by hellodword** [comment]
I tried the `solidity.compileUsingLocalVersion`, here is the results:

- works fine with the `soljson.js` in truffle
```json
    "solidity.enableLocalNodeCompiler": true,
    "solidity.compileUsingLocalVersion": "C:\\Users\\PRIVATE\\.config\\truffle\\compilers\\node_modules\\soljson-v0.5.16+commit.9c3226ce.js",
```

- crash with remote version
```json
    "solidity.enableLocalNodeCompiler": false,
    "solidity.compileUsingRemoteVersion": "v0.5.16+commit.9c3226ce"
```

- crash with the local version but downloaded by `vscode-solidity`
```json
    "solidity.enableLocalNodeCompiler": true,
    "solidity.compileUsingLocalVersion": "C:\\Users\\PRIVATE\\.vscode\\extensions\\juanblanco.solidity-0.0.106\\soljson-v0.6.11+commit.5ef660b1.js",
```

**Comment by hellodword** [comment]
Got it! When I switch the remote version, it will create a file like `soljson-v0.6.9+commit.3e3065ac.js`, but it could not download it successfully (maybe because of my weird network, I dont know).

But the language server will use an empty `soljson.js` without check or prompt.

I think adding some check will be better, I'm not sure if the [keccak256](https://github.com/ethereum/solc-bin/blob/5facfa9955dd5271cdf261bb053baefafb260b3e/bin/list.json#L8993) is the hash of the file.

Thanks a lot! @juanfranblanco

**Comment by hellodword** [comment]
I think an option to decide where to fetch the list or download the bins is useful:

https://github.com/juanfranblanco/vscode-solidity/blob/3ad375087f0b484d42127d6b94af6d1b3546b7d9/src/compiler.ts#L52
https://github.com/juanfranblanco/vscode-solidity/blob/3ad375087f0b484d42127d6b94af6d1b3546b7d9/src/solcCompiler.ts#L171

For example, by default:
```json
"solidity.fetchListUrl": "https://solc-bin.ethereum.org/bin/list.json",
"solidity.downloadBinFrom": "https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/soljson-%s.js",
```

use jsdelivr (global CDN):
```json
"solidity.fetchListUrl": "https://cdn.jsdelivr.net/gh/ethereum/solc-bin@gh-pages/bin/list.json",
"solidity.downloadBinFrom": "https://cdn.jsdelivr.net/gh/ethereum/solc-bin@gh-pages/bin/soljson-%s.js",
```

And also, check and retry is needed here: 
https://github.com/juanfranblanco/vscode-solidity/blob/3ad375087f0b484d42127d6b94af6d1b3546b7d9/src/solcCompiler.ts#L208-L218

## Ref
[jsdelivr doc](https://www.jsdelivr.com/features)

**Comment by juanfranblanco** [comment]
Thanks.. @hellodword !! Great feedback.

**Comment by hellodword** [comment]
> Thanks.. @hellodword !! Great feedback.

:)

Maybe it's caused by `https.get`, I got `read ECONNRESET` every time.

I tested it alone:

```js
const https = require('https');
const fs = require('fs');

const file = fs.createWriteStream("soljson-v0.6.11+commit.5ef660b1.js");
const request = https.get("https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/soljson-v0.6.11+commit.5ef660b1.js", function(response) {
  response.pipe(file);
});
```

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Maybe related: [TLSWrap.onStreamRead issues](https://github.com/nodejs/node/issues?q=is%3Aissue+TLSWrap.onStreamRead)

Hope helpful!
