### ISSUE TITLE
Doesn't support assert(bool) and require(bool)

### ISSUE THREAD

**Issue by chchmatt** [juanfranblanco/vscode-solidity#22]
Compilation errors with: 

    Error: Undeclared identifier.

When using assert(bool) or require(bool) as outlined in Exceptions documentation: http://solidity.readthedocs.io/en/latest/control-structures.html#exceptions

**Comment by SCBuergel** [comment]
I think this is an issue with the solidity version. Despite having 0.4.10 locally installed the current version seems to default to 0.4.9. You can add the following to your settings:
```
    "solidity.compileUsingRemoteVersion": "latest"
```
Unfortunately this requires us to be online, using the local compiler [would be great](https://github.com/juanfranblanco/vscode-solidity/issues/23).

**Comment by juanfranblanco** [comment]
@chchmatt @SCBuergel  Updated now
