### ISSUE TITLE
Support Solidity 0.8.1 Unchecked

### ISSUE THREAD

**Issue by mudgen** [juanfranblanco/vscode-solidity#220]
Hello,
In the extension I have Solidity 0.8.1 selected as the compiler but I get syntax errors for `unchecked` blocks.  Anyway to fix this?

`unchecked` is new syntax in Solidity 0.8.0

Thanks
Nick

**Comment by mudgen** [comment]
@juanfranblanco any plans for this?

**Comment by juanfranblanco** [comment]
Sorry @mudgen I missed this! How do you get the syntax errors? I assume is not highlighted but the compiler should not complain.

**Comment by mudgen** [comment]
The Linter complains.  See this image: ![linter error](https://i.ibb.co/hsPvkbs/lintertest.png)

**Comment by mudgen** [comment]
@juanfranblanco  Is there a way to make it not complain about this?

**Comment by juanfranblanco** [comment]
Many thanks @mudgen, I have tested with the latest solhint I have raised an issue with them https://github.com/protofire/solhint/issues/280.

**Comment by mudgen** [comment]
@juanfranblanco No answer from Solhint project. I wish this could be fixed somehow.

**Comment by juanfranblanco** [comment]
I assume this is a problem with the antlr solidity parser. So it will be just something that needs to be added.

**Comment by juanfranblanco** [comment]
Actually the antr parser has been upgraded https://github.com/solidity-parser/antlr/blob/a4d87bb8fa99e23101694e2f05bfa5e656777437/Solidity.g4 it just needs to be updated in solhint

**Comment by mudgen** [comment]
@juanfranblanco Can you do it?   Maybe no one else will.

**Comment by juanfranblanco** [comment]
@mudgen no, truly. I don't know what consequences will have in the linter, although not many. You can disable solhint in vscode for the time being.

**Comment by mudgen** [comment]
@juanfranblanco Do you know can fix this?

**Comment by juanfranblanco** [comment]
Closing this as the awesome solhint team have updated the parser.. upgraded in latest
