### ISSUE TITLE
Solidity 8? solc-bin deprecation

### ISSUE THREAD

**Issue by yoshiko2000** [juanfranblanco/vscode-solidity#229]
So it looks like the sources of Solidity (solc-bin) being used with this extension will no longer be updated. Meaning it will never get past version 7. Are there plans to get a new source of Solidity so it will be updated with future versions (8+)? 

https://github.com/ethereum/solc-bin - is deprecated, it won't update with new versions anymore.

https://binaries.soliditylang.org/ - "will not receive any new releases or nightly builds for any platform and does not serve the new directory structure, including non-emscripten builds."

Maybe I misunderstand, but it seems like there will need to be changes in order to get future versions of Solidity using this extension.

**Comment by juanfranblanco** [comment]
@yoshiko2000  thanks, the readme should have been updated. I have changed it now and you can also have an option to download now using the context menu a version of the compiler.

**Comment by yoshiko2000** [comment]
> @yoshiko2000 thanks, the readme should have been updated. This was updated a while ago. I have changed it now and you can also have an option to download now using the context menu a version of the compiler.

Thanks! That was fast. I appreciate it haha.

**Comment by juanfranblanco** [comment]
@yoshiko2000 you inspired the thought too create this too, makes it easier if you to download locally.
![image](https://user-images.githubusercontent.com/562371/112471654-109e7c00-8d64-11eb-9b03-fb774179c7a1.png)

**Comment by cameel** [comment]
> https://binaries.soliditylang.org/ - "will not receive any new releases or nightly builds for any platform and does not serve the new directory structure, including non-emscripten builds."

This is not true. I just found this issue and just wanted to clarify this point for anyone who finds this in the future. Here's the actual text of the deprecation notice:

> The binaries are also available at https://ethereum.github.io/solc-bin/ but this page stopped being updated just after the release of version 0.7.2, will not receive any new releases or nightly builds for any platform and does not serve the new directory structure, including non-emscripten builds.
>
> If you are using it, please switch to https://binaries.soliditylang.org, which is a drop-in replacement. This allows us to make changes to the underlying hosting in a transparent way and minimize disruption. Unlike the ethereum.github.io domain, which we do not have any control over, binaries.soliditylang.org is guaranteed to work and maintain the same URL structure in the long-term.

The deprecation refers specifically to https://ethereum.github.io/solc-bin/ and the only reason it's no longer updated is that it's simply out of space (it went over over the 10 GB limit for Github Pages). The new https://binaries.soliditylang.org as well as the older https://solc-bin.ethereum.org both have been switched to the new hosting and do receive new releases and nightlies.

You can read the full story here: [What Happened with Solidity-related Domains?](https://blog.soliditylang.org/2021/05/03/soliditylangorg-umbrella-domain/)
