### ISSUE TITLE
"enableLocalNodeCompiler" unknown configuration setting

### ISSUE THREAD

**Issue by paulrberg** [juanfranblanco/vscode-solidity#230]
Hey @juanfranblanco, perhaps you deprecated `enableLocalNodeCompiler` by mistake? VSCode warns me that this is an unknown configuration setting now.

This is with vscode@1.54.3 and vscode-solidity@0.0.110.

**Comment by juanfranblanco** [comment]
It is deprecated now, mainly there is a new setting to set what default mode you want to use, as you may want to use two different compilers in a project.

![image](https://user-images.githubusercontent.com/562371/112134584-cf239a80-8bc4-11eb-97f4-59c4c7b23ade.png)

**Comment by juanfranblanco** [comment]
Enabling something like this
![image](https://user-images.githubusercontent.com/562371/112134857-10b44580-8bc5-11eb-853f-f42aabf68816.png)

**Comment by juanfranblanco** [comment]
It was pretty hard, how to do this, so I decided to use Remote as the default, as the ones that use node will be advanced users and know what they are doing :)

**Comment by juanfranblanco** [comment]
Also if your settings are broken, it will revert to the embedded one in the language server, giving you an error.

**Comment by juanfranblanco** [comment]
@paulrberg  ^^^^

**Comment by paulrberg** [comment]
Ah, ok. Thanks for the prompt reply! I think that the following should be done:

1. Remove the mention about `enableLocalNodeCompiler` in the [README](https://github.com/juanfranblanco/vscode-solidity/blob/9eaad9adc8fa65a2bd945b9c154ccd8ee162abe9/README.md#npm--node-installation) and replace it with the correct way to use the Node version.
2. Remove/ amend the "Compile with configured Node module" option in the dropdown

<img width="613" alt="Capture d’écran 2021-03-23 à 12 50 11" src="https://user-images.githubusercontent.com/8782666/112135563-942a6280-8bd6-11eb-99c1-7fb423b739b1.png">

**Comment by juanfranblanco** [comment]
Thanks, on my way to the readme :), as I have just literally added now the download of the compiler, and other command settings. You can configure the node module, even if simple, you can do this: 

![image](https://user-images.githubusercontent.com/562371/112135994-50c7f800-8bc6-11eb-80e9-86e56badb249.png)

As you may have another node_module package, which has a version of solc. (like optismism/solc)

**Comment by juanfranblanco** [comment]
Updated the readme!
