### ISSUE TITLE
"true" is not accepted when used in assembly

### ISSUE THREAD

**Issue by paulrberg** [juanfranblanco/vscode-solidity#238]
Take the following code snippet:

```solidity
function isPowerOfTen(uint256 x) external view returns (bool result) {
    assembly {
        switch x
            case 1 {
                result := true
            }
            case 10 {
                result := true
            }
            case 100 {
                result := true
            }
            case 1000 {
                result := true
            }
            /// ...
    }
}
```

I am getting the following error in VSCode, although the code compiles just fine when I run `hardhat compile`.

> Linter: Parse error: mismatched input 'true' expecting {'from', 'address', 'calldata', 'return', 'byte', 'callback', DecimalNumber, HexNumber, HexLiteralFragment, 'leave', 'payable', 'receive', Identifier, StringLiteralFragment} [undefined]

In the meantime I fixed this by replacing `true` with `1`, so it's not a biggy, but I thought to report this anyways.

**Comment by paulrberg** [comment]
Whoops, sorry! I opened the issue in the solhint repo. Thanks for the clarification.

**Comment by juanfranblanco** [comment]
Don't worry @paulrberg  :)
