### ISSUE TITLE
Code highlighting not working on ubuntuu

### ISSUE THREAD

**Issue by abdojapan** [juanfranblanco/vscode-solidity#242]
Hi,

I installed using sudo snap install code

I only has vscode-solidity and beautifier extensions installed but highlighting is not working.

My OS is Ubuntuu.

Thanks for advance.

**Comment by juanfranblanco** [comment]
@abdojapan it does work in ubuntu. 
![image](https://user-images.githubusercontent.com/562371/116063240-a89dc700-a67c-11eb-88cd-351384df4516.png)
Try restarting vscode?

**Comment by abdojapan** [comment]
Thank you. It's a little weird. I tried restarting visual studio and the whole machine.

Here are the settings

![Screenshot from 2021-04-26 15-34-33](https://user-images.githubusercontent.com/13039210/116083135-f3333980-a6a4-11eb-82de-5387b58a62c7.png)

But there is no highlighting.

![Screenshot from 2021-04-26 15-30-09](https://user-images.githubusercontent.com/13039210/116083229-11009e80-a6a5-11eb-9173-b4db3e4befc0.png)

**Comment by juanfranblanco** [comment]
That is super strange, as code highlighting is the most simple thing the extension does. Also I assume that is the latest version, this is an issue with vscode itself. Maybe reinstalling vscode will help.

**Comment by juanfranblanco** [comment]
@abdojapan There was a report of having some issues in windows similar to yours, the solution is to do a full uninstall. Checkt his https://superuser.com/questions/1380208/how-to-completely-uninstall-visual-studio-code-from-windows-10 it will be similar in ubuntu.

**Comment by abdojapan** [comment]
> That is super strange, as code highlighting is the most simple thing the extension does. Also I assume that is the latest version, this is an issue with vscode itself. Maybe reinstalling vscode will help.

Thank you very much.

I removed the extension, then removed visual studio code as you said, then reinstall both and now it works!

For future viewers, removing the extension alone and reinstalling the extension again didn't help.
Also leaving the extension installed and removing visual studio code and reinstalling visual studio code again didn't help.

I had to remove the extension first and do the following and it worked.

    sudo snap remove code
    sudo snap install --classic code

**Comment by abdojapan** [comment]
> @abdojapan There was a report of having some issues in windows similar to yours, the solution is to do a full uninstall. Checkt his https://superuser.com/questions/1380208/how-to-completely-uninstall-visual-studio-code-from-windows-10 it will be similar in ubuntu.

Yes, seems to be related to lurking files causing this issue. Thank you very much.
