### ISSUE TITLE
Support v0.8.4 custom errors

### ISSUE THREAD

**Issue by paulrberg** [juanfranblanco/vscode-solidity#248]
See the announcement [article](https://blog.soliditylang.org/2021/04/21/custom-errors/) for the new custom error syntax.

For the following code:

```solidity
error SomeError();

contract Greeter {
    function throwError() external pure {
        revert SomeError();
    }
}
```

I get this error in VSCode:

> Linter: Parse error: missing '=' at '(' [undefined]

This is in spite of me using the latest version of solhint (3.3.6), which has recently added support for solidity v0.8.4 custom errors. Related thread: https://github.com/protofire/solhint/issues/289.

**Comment by juanfranblanco** [comment]
Thanks @paulrberg. Now 2 issues, one i have not updated solhint to the latest and two i need to modify the parser to allow for the new syntax.

**Comment by juanfranblanco** [comment]
Should be included in the latest now, let me know how it goes.

**Comment by juanfranblanco** [comment]
@paulrberg  ^^

**Comment by paulrberg** [comment]
Wow, this was quick! Thanks @juanfranblanco!

I can now ship custom errors with my Solidity template :)

**Comment by juanfranblanco** [comment]
Great !! :)
