### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by v13s** [juanfranblanco/vscode-solidity#251]
- Issue Type: `Bug`
- Extension Name: `solidity`
- Extension Version: `0.0.116`
- OS Version: `Windows_NT x64 10.0.17134`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 25230,
		"activateCallTime": 19,
		"activateResolvedTime": 183,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "AzBlockchain.azure-blockchain",
				"_lower": "azblockchain.azure-blockchain"
			},
			"activationEvent": "onView:AzureBlockchain"
		}
	},
	"runtimeErrors": []
}
```

**Comment by juanfranblanco** [comment]
@v13s I know this autogenerated, but if you can add more info, it will be great.
