### ISSUE TITLE
Code generation as optional function

### ISSUE THREAD

**Issue by pynixwang** [juanfranblanco/vscode-solidity#253]
most users do not generate c#, f# and vb code.

**Comment by pynixwang** [comment]
<img width="643" alt="Screen Shot 2021-06-13 at 12 04 24 AM" src="https://user-images.githubusercontent.com/1189879/121782206-0493bf00-cbdb-11eb-880f-f53718ce6706.png">


context menu so mass, too many items, last 2 group can be removed

**Comment by juanfranblanco** [comment]
Yes, the context menu is big, I am awaiting for the support of submenus, but what we want is more code generators for other languages, not as an option but to help and teach anyone, regardless of the preferred language. "Most users" that is wrong :). Actually I had feedback that many users would have preferred to use .net for integration and thanks to this they discovered they could do it.

**Comment by pynixwang** [comment]
@juanfranblanco  most users(90% more) generate javascript(typescript) for dapp.

we can now remove last 2 group to make context menu clean, function can be also done by command. then move back when submenu is supported.

**Comment by juanfranblanco** [comment]
@pynixwang  sorry but no :).

**Comment by juanfranblanco** [comment]
BTW the code generation is only 4 items. The others are necessary to change compiler versions, download compilers, etc.

**Comment by pynixwang** [comment]
because javascript does' nt need a code generator.

**Comment by juanfranblanco** [comment]
Sure, thanks.
