### ISSUE TITLE
Unreachable Code

### ISSUE THREAD

**Issue by rachit2501** [juanfranblanco/vscode-solidity#256]
```
    function payInterest(uint256 amount) public payable {
        uint256 interest = calculateInterestAmount(amount);
        require(
            msg.value == interest,
            "Not the entire interest amount deposited"
        );
        interestPaid[msg.sender][amount] = true;
    }

```
The tool throws an `unreachable code` error at the `require` statement and the statement following it.
`calculateInterestAmount` returns just the number 10.

Also, the code is working fine in the truffle test suits.

**Comment by juanfranblanco** [comment]
@rachit2501 What does you mean by the tool?

**Comment by cameel** [comment]
This is unfortunately a bug in solc 0.8.5: https://github.com/ethereum/solidity/issues/11522.
The code the compiler generates is correct, it's just the analysis that incorrectly detects some calls to internal library functions as always reverting and issues a spurious warning. We already have a fix and we're going to release it as 0.8.6 very soon.

**Comment by pcaversaccio** [comment]
Solidity version `0.8.6` was just released: https://github.com/ethereum/solidity/releases/tag/v0.8.6. This should fix the unreachable code issue. @juanfranblanco I see that the `latest` version is still `Compiler using remote version: 'latest', solidity version: 0.8.5+commit.a4f2e591.Emscripten.clang`. How should I update it in my VS Code extension?

**Comment by juanfranblanco** [comment]
Just configure it to use "latest" I'll release it in a couple of hours anyway

**Comment by juanfranblanco** [comment]
@pcaversaccio it is released now.

**Comment by cameel** [comment]
@juanfranblanco I see that the update commit (384a93bcddd31f3537d79075230980bd4e2a987f) adds some random soljson binaries to the repo. Probably by mistake?

**Comment by juanfranblanco** [comment]
Yes, those are the testing ones.

**Comment by pcaversaccio** [comment]
@juanfranblanco thanks. When I click on Solidity: Compiler Information I still get `Compiler using remote version: 'latest', solidity version: 0.8.5+commit.a4f2e591.Emscripten.clang` (I restarted VS Code). Maybe I just need to wait a little bit until I get it on my machine via the remote node.

**Comment by juanfranblanco** [comment]
@cameel I am getting the same, although is the check-in from 4 hours ago (solc-bin). Try the mode "Embedded"
```
{
   "solidity.defaultCompiler": "embedded"
}
```

**Comment by juanfranblanco** [comment]
Or select it from the remote option.
![image](https://user-images.githubusercontent.com/562371/122973060-baec6680-d388-11eb-9977-4e6ac6ba1acf.png)

I think is something is getting cached, when dowloading it from the remote source, although I am ok doing it directly.

**Comment by pcaversaccio** [comment]
> Or select it from the remote option.
> ![image](https://user-images.githubusercontent.com/562371/122973060-baec6680-d388-11eb-9977-4e6ac6ba1acf.png)
> 
> I think is something is getting cached, when dowloading it from the remote source, although I am ok doing it directly.

Worked!

**Comment by juanfranblanco** [comment]
@cameel i have tested this in my machine in different vms, "latets" gets 8.5 all the time. Although downloading it through the browser has proved ok. Is this cached in the website?

**Comment by cameel** [comment]
Individual binaries are cached but they are not supposed to change anyway. The list files, including https://binaries.soliditylang.org/bin/list.json which you are probably using, are specifically exempt from caching and visiting it in a browser I can see 0.8.6 there. The new binary is available at https://binaries.soliditylang.org/bin/soljson-v0.8.6+commit.11564f7e.js. If you're using https://binaries.soliditylang.org/bin/soljson-latest.js, it should also be ok - I just downloaded it to check and it's byte for byte identical to `soljson-v0.8.6+commit.11564f7e.js`.

I think something must be cached elsewhere. Can you verify that you see 0.8.6 in the `list.json` file you get?

**Comment by juanfranblanco** [comment]
@cameel the problem is with https://binaries.soliditylang.org/bin/soljson-latest.js, some how it is ok in the browser, but not downloading it programmatically (i have tested it in different machines)

**Comment by cameel** [comment]
I just checked [`solc` npm package](https://www.npmjs.com/package/solc) (in case that's the one you're having problems with - we did have a problem with wrong binary being included once) but the binary there is also identical with the 0.8.6 ones from the links I posted above.

**Comment by juanfranblanco** [comment]
Yes npm, is fine, this is the current "embedded" version. The release was 4 hours ago, let me try tomorrow as the cache might have expired.

**Comment by cameel** [comment]
> the problem is with https://binaries.soliditylang.org/bin/soljson-latest.js, some how it is ok in the browser, but not downloading it programmatically (i have tested it in different machines)

I tried with `curl` and I'm still getting the same binary as from the website.
```bash
curl -L https://binaries.soliditylang.org/bin/soljson-latest.js | sha256sum
```
This is the hash I'm getting:
```
06a671efd8865a6ecc0ad648076177b35abcd06a7059888ea65111272e33a57f  -
```

**Comment by cameel** [comment]
Actually, I just realized that `soljson-latest.js` might actually be a caching issue on our side. Only files matching `*/list.*` are exempt.

I wonder why it works for me though - the cache is server-side so we should both be getting the same result. So either caching is regional or something else is caching it as well.

**Comment by juanfranblanco** [comment]
Yes, i have downloaded it using the browser and it was ok, but later other combinations have not worked. Trying again now.

**Comment by juanfranblanco** [comment]
@cameel I just 'curled' and I got the 8.5

**Comment by cameel** [comment]
OK. Let's see if clearing the Cloudfront will help. I have just invalidated everything maching `*/*-latest*`. Please check what you are getting now.

**Comment by juanfranblanco** [comment]
@cameel no changes yet, Ill give it an hour to propagate.

**Comment by cameel** [comment]
I invalidated the whole cache just in case (we're getting most of the traffic from repeated downloads and mostly on just a few files anyway so it should not be a big deal). See if that helps. These invalidations are supposed to take only 60 to 300 seconds so if that does not help I'd suspect extra caching somewhere else on the way.

**Comment by pcaversaccio** [comment]
Just to validate, curling gives me the hash: `06a671efd8865a6ecc0ad648076177b35abcd06a7059888ea65111272e33a57f`
![image](https://user-images.githubusercontent.com/25297591/122992702-b46ce780-d3a6-11eb-9f45-a2f19744efe6.png)

**Comment by pcaversaccio** [comment]
But if I use the remote node with `latest` I still get `0.8.5`: 
![image](https://user-images.githubusercontent.com/25297591/122992938-ff86fa80-d3a6-11eb-84cf-0dcbaa40ecbd.png)

**Comment by juanfranblanco** [comment]
@cameel @pcaversaccio the cache is cleared now, it is working on my end. 

You will need to restart vscode to get the "new" latest, or change version and go back to "latest" to refresh it as it will be kept in memory..

**Comment by cameel** [comment]
Great. I created an issue on our side to fix it in a more permanent manner. The problem is that outright disabling caching for this file might not be a good idea (it got 5 TB of traffic last month) so we might have to modify our mirroring to just invalidate stuff after every update.

**Comment by pcaversaccio** [comment]
Confirmed, after restarting VS Code I got `0.8.6`. Cache issues remain one of the major challenges in modern software engineering 😜

**Comment by rachit2501** [comment]
Confirmed here too. It's working for me too now. 
Thanks for the quick response and fix.
