### ISSUE TITLE
last version needs a complete uninstall and reinstall for Prettier to work.

### ISSUE THREAD

**Issue by Janther** [juanfranblanco/vscode-solidity#259]
So last version adds 2 upgrades to the prettier packages. Apparently this needs a full reinstall because the system thinks that the packages are good to go. Maybe you could include the `package-lock.json` in the bundle.

**Comment by juanfranblanco** [comment]
Sure, let me try it. Damn, I tested it as usual so I did not notice.

**Comment by juanfranblanco** [comment]
@Janther i have tested it and I don't see the issue, what do you mean by full reinstall? What did you do? (<-- i am confused : ))

**Comment by Janther** [comment]
Prettier got stuck in a loop forever in my laptop. Only once I reinstalled solidity from scratch it worked again

**Comment by juanfranblanco** [comment]
@Janther Hmm, I have been looking and I don't know how that might have been an issue, each extension comes with all node modules, (if not web packed), so you always have everything.

What were your settings?

**Comment by Janther** [comment]
I had an almost brand new setup as I just changed my laptop. It just happened that after upgrading it stopped saving files I thought that it was low on memory so I tried closing apps and even shutting the computer down and restarting it.
Same problem and eventually I thought about uninstalling solidity and reinstalling it and it worked like a charm

**Comment by juanfranblanco** [comment]
Weird, if you post your prettier file, I might be able to reproduce it.

**Comment by Janther** [comment]
Not sure this is worth following though. Thank you for the quick response.

**Comment by juanfranblanco** [comment]
Thank you @Janther !!
