### ISSUE TITLE
Version 0.0.122 messed up highlighting

### ISSUE THREAD

**Issue by rokso** [juanfranblanco/vscode-solidity#260]
Overall I know this is going to improve highlighting but some quick thoughts and possible issues.

- Parent contracts are also same color now
- Constant name color is weird
- `10_000` not highlighted properly

Before 

![Screen Shot 2021-06-28 at 8 32 22 PM](https://user-images.githubusercontent.com/14338548/123723493-208c9700-d850-11eb-95df-9a9c8d78102a.png)

After

![Screen Shot 2021-06-28 at 8 32 48 PM](https://user-images.githubusercontent.com/14338548/123723548-34d09400-d850-11eb-98ba-77b2ec01a643.png)

> EDIT::

- inline comments are messed up too
![Screen Shot 2021-06-28 at 8 36 29 PM](https://user-images.githubusercontent.com/14338548/123723706-95f86780-d850-11eb-9948-ada480ea9271.png)

**Comment by juanfranblanco** [comment]
Many thanks for the great feedback. fixed most of it now.

+ To change the colours of the extended contract names I have put the key "entity.name.type.contract.extend". Typescript follows the same convention.
+ I have removed the upper case constant rule. This is very specific on constant tastes. (it was also broken on underscore prefix), but it can be resurrected if wanted.
+ Added support for underscores on numbers, it was not supported before, but was not highlighted (matched)
+ Comments added to function parameters

**Comment by juanfranblanco** [comment]
@rokso ^^ check the latest

**Comment by rokso** [comment]
perfect. All fixed except extended contract color.

**Comment by rokso** [comment]
Thank for quick fix 😄

**Comment by juanfranblanco** [comment]
@rokso yeah.. I know about the contract extended color, i added an extra "name" for it, so it can be themed, as it is an "entity", I thought about quickly workaround it and make it a "variable" to get that different colour, but it did not make much sense..

**Comment by rokso** [comment]
I have seen comment in PR that there is still some problem with variable highlight in `require` and `return`, want me to submit separate issue or being tracked somewhere and in your todo?

**Comment by juanfranblanco** [comment]
@rokso yes please add a new issue :)
