### ISSUE TITLE
Styling is broken in interfaces since latest version

### ISSUE THREAD

**Issue by paulrberg** [juanfranblanco/vscode-solidity#261]
I'm not 100% sure if this is caused by vscode-solidity, but it probably is. This is how my interfaces get styled now:

<img width="482" alt="Capture d’écran 2021-06-29 à 16 59 38" src="https://user-images.githubusercontent.com/8782666/123810912-779b7600-d8fb-11eb-9c7b-70301d9bdcf1.png">

Notice the yellow tint to all "function" keywords except the first one. This isn't how styling was like before, e.g. last week.

**Comment by juanfranblanco** [comment]
Damn it!! 👍

**Comment by juanfranblanco** [comment]
Should be out the fix in a minutes, fixed on latest.

**Comment by paulrberg** [comment]
Thank you, ser! It works now.

Unbelievable how quickly you respond.

**Comment by juanfranblanco** [comment]
@paulrberg I just happened to be there :)
