### ISSUE TITLE
Interface function syntax highlighting slightly off

### ISSUE THREAD

**Issue by JamesLefrere** [juanfranblanco/vscode-solidity#266]
I may have introduced this in #258 

![image](https://user-images.githubusercontent.com/5450382/124233613-4e553280-db13-11eb-8962-b1d9765bedef.png)

Apologies if so, I must have been testing with a single function in my interface. Hoping to find the time to fix this plus #264 🙏

**Comment by juanfranblanco** [comment]
@JamesLefrere that is fixed already 
![image](https://user-images.githubusercontent.com/562371/124235091-c2d8a300-db0c-11eb-8b50-d5feba50484a.png)

**Comment by juanfranblanco** [comment]
@JamesLefrere  Let's see how things go and if there is more issues, probably it will need to be rollback (back to super simple highlighting) and move further work to a branch. So far i have not found major annoyances (a part from the ones flagged).

Yeah I did my tests too with limited areas....

**Comment by JamesLefrere** [comment]
Ok, sounds like this issue can be closed, but yes, it's possible that there are other issues. 

It might be possible to create some integration tests, I'll have a look 👍
