### ISSUE TITLE
Proxying the format to Prettier extension and passing on the plugin.

### ISSUE THREAD

**Issue by Janther** [juanfranblanco/vscode-solidity#267]
Hey @juanfranblanco,

I really like how you embraced [prettier-plugin-solidity](https://github.com/prettier-solidity/prettier-plugin-solidity).
There are however a few differences between using the prettier extension directly with our plugin in the `node-modules` folder and using vscode-solidity.

Could you have a look at prettier/prettier-vscode#2051 and maybe we could brainstorm an approach to do this.

**Comment by juanfranblanco** [comment]
@Janther sure :)
