### ISSUE TITLE
selectWorkspaceRemoteSolcVersion not found

### ISSUE THREAD

**Issue by nhausman1** [juanfranblanco/vscode-solidity#273]
Upon installing the most recent version `v0.0.125` I noticed that none of my solidity files were compiling. My first debug step when I get `vscode-solidity` errors is to change the workspace compiler version to make sure the extension is pulling from remote. When I ran the `Change workspace compiler version` command I got the following error:

```
Command 'Solidity: Change workspace compiler version (Remote)' resulted in an error (command 
'solidity.selectWorkspaceRemoteSolcVersion' not found)
```

I tried restarting vscode, reinstalling the extension, reinstalling solc, and running the `Download compiler and set workspace local Path` command to no avail unfortunately. The only fix I've found is to revert to `v0.0.124`.

**Comment by juanfranblanco** [comment]
Thanks @nhausman1 Ill have a look!

**Comment by juanfranblanco** [comment]
@nhausman1 
I have tripled checked and no changes have occurred that will cause that issue.
Maybe it might have been due to a corrupt installation?

![image](https://user-images.githubusercontent.com/562371/127324800-367438e9-29f2-42e4-b838-a90d027a89ba.png)

**Comment by juanfranblanco** [comment]
If you go to your .vscode folder you should be able to delete the "cached versions"
![image](https://user-images.githubusercontent.com/562371/127325095-7c6a0595-0064-4e72-b0e8-cc30bd8e04f4.png)

**Comment by juanfranblanco** [comment]
I am closing this now.. please reopen if you see anything.
