### ISSUE TITLE
Standalone language server

### ISSUE THREAD

**Issue by jmederosalvarado** [juanfranblanco/vscode-solidity#282]
Hi. Would it be possible to create a standalone package for the language server, and keep it separated from the vscode extension. This would allow the usage of the language server in other editors supporting the lsp protocol, like neovim.

I'd be happy to help if you point me in the right direction.

**Comment by juanfranblanco** [comment]
Hi, there are lots of dependencies that rely on vscode at the moment. Mainly all the plumming is specific to it. From writing autocompletes, goto definition to errors etc. Overall everything will require an abstraction.

**Comment by jmederosalvarado** [comment]
Hi @juanfranblanco, thanks for responding. I also thought at first that the server was to tied to vscode dependencies. However I took a look at you code and compared it with [tailwindcss language server](https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages%2Ftailwindcss-language-server), which I use all the time from neovim and these dependencies don't seem to be a problem.

More specifically, tailwindcss language server [depends](https://github.com/tailwindlabs/tailwindcss-intellisense/blob/dce390d98ca75bc6a0cf19d29e16ca6422faa924/packages/tailwindcss-language-server/package.json#L54,L56) on:
- vscode-languageserver
- vscode-languageserver-textdocument
- vscode-uri

Does your server depends on anything else that's vscode specific ?

**Comment by juanfranblanco** [comment]
So neovim actually supports all the lsp implementations by vscode-language server? That is very interesting and cool. Obviously now the issue will be the client side etc. But that will surely simplify things.

**Comment by jmederosalvarado** [comment]
Actually the client side is not a problem, neovim already comes with a full lsp client implementation, and the only thing that's actually needed is a language server running, so I believe the only thing you'd need to do is to split the codebase into to separate packages, so that neovim users can install the actual server without having to download a full vscode extension.

**Comment by jmederosalvarado** [comment]
So in theory it's possible to use the current codebase (with minor changes, like the ones related to stdin/stdout) as a language server, because you can always run the server with `node path/to/src/server.js --stdio`. So this issue is in part about having a way to install the language server as a standalone package.

**Comment by jmederosalvarado** [comment]
@juanfranblanco I just realized that the fork I mentioned in my comment is not updated with the changes I talked about. I'm on mobile right now, but I'll update it as soon as I get home.

**Comment by jmederosalvarado** [comment]
Hi @juanfranblanco. [This commit] introduces the changes I told you about. It enables to run as a standalone language server without breaking the vscode extension. I wasn't able to get diagnostics to work, it might ve because there's something wrong with my setup. I'd appreciate your feedback on this.

**Comment by juanfranblanco** [comment]
That is awesome thanks!

**Comment by jmederosalvarado** [comment]
Just dropping by to say I was able to get diagnostics to work.

The problem was I was not passing the settings expected by the server from the client, this was a problem because [the server's default settings](https://github.com/juanfranblanco/vscode-solidity/blob/master/src/server.ts#L61-70) don't match the ones from the vscode client, so the behaviour was inconsistent between vscode and neovim as I wasn't passing any settings from the client expecting to use the defaults.

The other issue is related to [how the compiler is initialized within the server](https://github.com/juanfranblanco/vscode-solidity/blob/master/src/server.ts#L162), which is [only called from the `onDidChangeConfiguration` hook](https://github.com/juanfranblanco/vscode-solidity/blob/master/src/server.ts#L247). This again causes that the compiler is never initialized when no settings are being passed from the client.

**Comment by jmederosalvarado** [comment]
I'm pretty sure there are some features that I still haven't tried (I'm quite new to solidity). But right now it seems that the only thing that would be needed to have the language server as a standalone package is to split the codebase into two different packages.

**Comment by jmederosalvarado** [comment]
This is the relevant part of my config right now in order to use this code as a language server, in case someone might find it usefull. I'm planning to submit a PR to nvim-lspconfig at some point.

```lua
local lspconfig = require("lspconfig")
local configs = require("lspconfig/configs")

if not lspconfig["vscode-solidity"] then
  configs["vscode-solidity"] = {
    default_config = {
      cmd = { "node", "path/to/repo/out/src/server.js", "--stdio" },
      filetypes = { "solidity" },
      root_dir = function(fname)
        return lspconfig.util.find_git_ancestor(fname)
          or lspconfig.util.find_node_modules_ancestor(fname)
          or lspconfig.util.find_package_json_ancestor(fname)
          or vim.loop.cwd()
      end,
      init_options = vim.fn.stdpath("cache"),
      settings = {
        solidity = {
          nodemodulespackage = "solc",
          compileUsingRemoteVersion = "latest",
          compilerOptimization = 200,
          compileUsingLocalVersion = "",
          defaultCompiler = "remote", -- remote | localFile | localNodeModule | embedded
          linter = "solhint", -- solhint | solium
          solhintRules = nil,
          formatter = "prettier", -- prettier | none
          soliumRules = {
            ["imports-on-top"] = 0,
            ["variable-declarations"] = 0,
            ["indentation"] = { "off", 4 },
            ["quotes"] = { "off", "double" },
          },
          enabledAsYouTypeCompilationErrorCheck = true,
          validationDelay = 1500,
          packageDefaultDependenciesDirectory = "node_modules",
          packageDefaultDependenciesContractsDirectory = "",
        },
      },
    },
  }
end
```

**Comment by juanfranblanco** [comment]
This is awesome, I am updating the extension at the moment, the connection when is created now is with ```let connection = createConnection(ProposedFeatures.all);``` that may allowed you not to require any changes from that commit.
Splitting, yeah need to do that, although there is plenty code reuse across client and server, I want to see if there is another option.

**Comment by xbladesub** [comment]
> This is the relevant part of my config right now in order to use this code as a language server, in case someone might find it usefull. I'm planning to submit a PR to nvim-lspconfig at some point.
> 
> ```lua
> local lspconfig = require("lspconfig")
> local configs = require("lspconfig/configs")
> 
> if not lspconfig["vscode-solidity"] then
>   configs["vscode-solidity"] = {
>     default_config = {
>       cmd = { "node", "path/to/repo/out/src/server.js", "--stdio" },
>       filetypes = { "solidity" },
>       root_dir = function(fname)
>         return lspconfig.util.find_git_ancestor(fname)
>           or lspconfig.util.find_node_modules_ancestor(fname)
>           or lspconfig.util.find_package_json_ancestor(fname)
>           or vim.loop.cwd()
>       end,
>       init_options = vim.fn.stdpath("cache"),
>       settings = {
>         solidity = {
>           nodemodulespackage = "solc",
>           compileUsingRemoteVersion = "latest",
>           compilerOptimization = 200,
>           compileUsingLocalVersion = "",
>           defaultCompiler = "remote", -- remote | localFile | localNodeModule | embedded
>           linter = "solhint", -- solhint | solium
>           solhintRules = nil,
>           formatter = "prettier", -- prettier | none
>           soliumRules = {
>             ["imports-on-top"] = 0,
>             ["variable-declarations"] = 0,
>             ["indentation"] = { "off", 4 },
>             ["quotes"] = { "off", "double" },
>           },
>           enabledAsYouTypeCompilationErrorCheck = true,
>           validationDelay = 1500,
>           packageDefaultDependenciesDirectory = "node_modules",
>           packageDefaultDependenciesContractsDirectory = "",
>         },
>       },
>     },
>   }
> end
> ```

tried this config, errors are not recognized some reason. I'd like to use this extension as lang server inside neovim also, because it allows to use any compiler version (using solc-select it also possible, but starting from 0.8.11)

**Comment by Marenz** [comment]
Since at least the last release `solc` has a rudimentary language-server integrated. Currently it supports only syntax-highlighting and diagnostics but we expect at least the renaming feature in the next release, but probably even more.

You can run it with `solc --lsp`.
For nvim I am using the [Coc plugin](https://github.com/neoclide/coc.nvim) with the following config (`:CocConfig` in nvim)

```
{
	"semanticTokens.filetypes":["*"],

	"languageserver": {
		"solidity": {
			"command": "/absolute/path/to/solc",
			"args": [
				"--lsp"
			],
			"settings": {
				"remappings": [],
				"evmVersion": "berlin"
			},
			"trace.server": "verbose",
			"rootPatterns": [
				"compile_commands.json",
				".git/"
			],
			"filetypes": [
				"solidity"
			]
		}
	}
}
```
Though you can probably just replace the `cmd` value in the config posted before me as well. In fact, I am gonna try that.

**Comment by GopherJ** [comment]
I have similar settings in coc.nvim but it seems the linter config cannot be passwd to the server:
```
  "languageserver": {
    "solidity": {
      "command": "solidity-language-server",
      "args": ["--stdio"],
      "rootPatterns": [".git/"],
      "trace.server": "verbose",
      "filetypes": ["solidity"],
      "initializationOptions": {
        "solidity.solhint": "solhint",
        "solidity.enabledAsYouTypeCompilationErrorCheck": true
      }
    }
  },
```
![image](https://user-images.githubusercontent.com/33961674/180463952-7c731833-fb48-4151-8751-1d6a59b2f19f.png)

**Comment by llllvvuu** [comment]
I just looked into this, and this is my idea for a solution: https://github.com/juanfranblanco/vscode-solidity/pull/411

It would remove the need to make a manual copy the default settings (which may get out of date) like this:

> This is the relevant part of my config right now in order to use this code as a language server, in case someone might find it usefull. I'm planning to submit a PR to nvim-lspconfig at some point.
> 
> ```lua
> local lspconfig = require("lspconfig")
> local configs = require("lspconfig/configs")
> 
> if not lspconfig["vscode-solidity"] then
>   configs["vscode-solidity"] = {
>     default_config = {
>       cmd = { "node", "path/to/repo/out/src/server.js", "--stdio" },
>       filetypes = { "solidity" },
>       root_dir = function(fname)
>         return lspconfig.util.find_git_ancestor(fname)
>           or lspconfig.util.find_node_modules_ancestor(fname)
>           or lspconfig.util.find_package_json_ancestor(fname)
>           or vim.loop.cwd()
>       end,
>       init_options = vim.fn.stdpath("cache"),
>       settings = {
>         solidity = {
>           nodemodulespackage = "solc",
>           compileUsingRemoteVersion = "latest",
>           compilerOptimization = 200,
>           compileUsingLocalVersion = "",
>           defaultCompiler = "remote", -- remote | localFile | localNodeModule | embedded
>           linter = "solhint", -- solhint | solium
>           solhintRules = nil,
>           formatter = "prettier", -- prettier | none
>           soliumRules = {
>             ["imports-on-top"] = 0,
>             ["variable-declarations"] = 0,
>             ["indentation"] = { "off", 4 },
>             ["quotes"] = { "off", "double" },
>           },
>           enabledAsYouTypeCompilationErrorCheck = true,
>           validationDelay = 1500,
>           packageDefaultDependenciesDirectory = "node_modules",
>           packageDefaultDependenciesContractsDirectory = "",
>         },
>       },
>     },
>   }
> end
> ```
