### ISSUE TITLE
Linting doesn't work for @openzeppelin/contracts

### ISSUE THREAD

**Issue by iboxgithub** [juanfranblanco/vscode-solidity#284]
Hi,

I wok with VSCode + juanblanco.solidity plugin. My issue is that despite compilling perfectly well, the linting shows an error with OpenZeppelin imports
`import "@openzeppelin/contracts/access/Ownable.sol";` (cf screenshot below)
![image](https://user-images.githubusercontent.com/5391993/133991736-e07b0cc4-2187-404a-97d7-c2d4a1377d3d.png)

Error: 
```
Source "@openzeppelin/contracts/access/Ownable.sol" not found
File import callback not supported
```

is it the expected behavior or is there a fix planned for this? thanks for your help!

**Comment by juanfranblanco** [comment]
Are your Oz files in the node modules folder?

**Comment by iboxgithub** [comment]
yes sir
![image](https://user-images.githubusercontent.com/5391993/134028120-2065aa08-9afa-47cc-b116-066535d49f24.png)

**Comment by juanfranblanco** [comment]
This should not happen if your node_modules is at root.

**Comment by juanfranblanco** [comment]
Have you checked the settings?

**Comment by iboxgithub** [comment]
I haven't touched the settings, it's a default install with the plugin added, nothing special on my workspace. But if you want me to check something specific let me know (Mac OS Big Sur 11.6, VSCode 1.56.2, juanblanco.solidity 0.0.125)

**Comment by juanfranblanco** [comment]
@iboxgithub  @jrbgit Check this:
[vscode-oz-template.zip](https://github.com/juanfranblanco/vscode-solidity/files/7202624/vscode-oz-template.zip)

**Comment by juanfranblanco** [comment]
Sample - template is tested in Linux - Windows and includes a workspace setting, which is the default of node-modules:

![linux](https://user-images.githubusercontent.com/562371/134167068-7664c584-6bac-4d44-9164-b4a0fb3b6b75.png)
![settings](https://user-images.githubusercontent.com/562371/134167069-8469c5dd-4e66-48ea-bf9a-099a0b56cfde.png)
![windows](https://user-images.githubusercontent.com/562371/134167070-ea5a3c2a-7261-49e6-a3b8-d42b6b3947be.png)

**Comment by iboxgithub** [comment]
it doesn't work on my Mac :(

![image](https://user-images.githubusercontent.com/5391993/134202637-8485e6ab-d97c-4aab-8fca-162c0733a384.png)

**Comment by juanfranblanco** [comment]
Right, the vscode-oz-template is not your root folder, it should be like this: (on a Mac)
<img width="960" alt="Screenshot 2021-09-22 at 10 12 52" src="https://user-images.githubusercontent.com/562371/134317958-b0088a2b-053e-49e3-b8e0-eaf44bdae073.png">

**Comment by jrbgit** [comment]
This worked fine until recently - My node_modules is in the correct place because I can compile and deploy the contracts still without any problems. The directories I'm working in had the plugin installed for weeks and was working fine the way it was setup and then suddenly this started.

**Comment by iboxgithub** [comment]
ok so when I put your project on the top I don't see the error anymore, not in your code, NOR IN MINE...what is this behavior???
![image](https://user-images.githubusercontent.com/5391993/134373734-1987e350-6a14-4e0f-b2d6-7d493decb3b9.png)

**Comment by juanfranblanco** [comment]
You only can have one folder at a time.

**Comment by iboxgithub** [comment]
ok, do you know why? also in my example I actually have several folders...and it works. after playing around (nothing rational) I can see that it doesn't work when the top folder contains several projects but it does work when the first project (like yours) is a simple one; in this case, the following projects don't show the error :D 
![image](https://user-images.githubusercontent.com/5391993/134393758-0700cbf5-049b-4d8f-a3ad-0297d629a013.png)

**Comment by juanfranblanco** [comment]
Yes, the extension has been created to work with a single workspace / folder, workspaces were a feature added afterwards in vscode.

**Comment by iboxgithub** [comment]
ok, I think it would be cool to take a look at it seems like a workaround no? (last question, after I close the ticket I promise!)

**Comment by jrbgit** [comment]
> Yes, the extension has been created to work with a single workspace / folder, workspaces were a feature added afterwards in vscode.

I understand that the extension was created before workspaces were a feature in vscode but having a separate workspace for every project that contains solidity or having to download your zip file is not practical.

> ok, I think it would be cool to take a look at it seems like a workaround no? (last question, after I close the ticket I promise!)

I don't think you should close this ticket. The amount of people who are having this issue is more than just the two of us. I'm in a solidity telegram group and this issue has come up for multiple people.

@juanfranblanco Is this something that can be fixed or does this require a major re-write due to the fact that the plugin was written before workspaces existed? I've been meaning to get my feet wet with vscode extensions so maybe now is the time :)

**Comment by juanfranblanco** [comment]
You are able to work with different - folders, just not at the moment with random folders in a workspace. Example  https://github.com/Nethereum/ERC721ContractLibrary.Template

Also you don't need to download anything it works out of the box, is just you are settling an environment that is not currently supported.

**Comment by jrbgit** [comment]
Gotcha - thanks for the clarity on that.

**Comment by iboxgithub** [comment]
@juanfranblanco so do we keep this ticket open for a further release? (or put it on hold?)

**Comment by jrbgit** [comment]
I'd like to see this added to a future release - I've disabled the extension in the meantime

**Comment by juanfranblanco** [comment]
> @juanfranblanco so do we keep this ticket open for a further release? (or put it on hold?)

I will create a new ticket, this is too specific to the Oz use case. When I can put time aside I will look into this.

**Comment by iboxgithub** [comment]
ok, I will close the ticket now, if you can put the new ticket reference here when ready that would be great (I only have this ticket linked to several Discord discussions on this topic so like this people will know where to go), thanks a lot for your help!

**Comment by juanfranblanco** [comment]
@iboxgithub multiple workspace folders is supported now, have a go
