### ISSUE TITLE
Creating a .prettierrc file doesn't modify prettier config

### ISSUE THREAD

**Issue by JulienGmd** [juanfranblanco/vscode-solidity#293]
How to modify the integrated prettier config? 
What I did :
- Installed the Solidity plugin.
- Created a .prettierrc like stated in the plugin overview and placed it at the root of my folder with this content :
```
{
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 2000,
        "tabWidth": 2,
        "useTabs": true,
        "singleQuote": false,
        "bracketSpacing": true,
        "explicitTypes": "always"
      }
    }
  ]
}
```

**Comment by pofulu** [comment]
It worked after I restarted my VSCode, did you too?

**Comment by juanfranblanco** [comment]
@pofulu  yes it should work after restarting and new release should be out soon that fixes this.
