### ISSUE TITLE
Compiler "aborts" whenever editing Solidity files

### ISSUE THREAD

**Issue by transmissions11** [juanfranblanco/vscode-solidity#297]
```
[2021-11-06 19:34:15.079] [exthost] [error] RuntimeError: abort(Canceled: Canceled). Build with -s ASSERTIONS=1 for more info.
    at process.abort (/Users/t11s/.vscode-insiders/extensions/juanblanco.solidity-0.0.135/node_modules/solc/soljson.js:1:13074)
    at process.emit (events.js:327:22)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

I see this error in my extension host logs upon starting up vscode in a solidity project now, and errors do not showing up when editing solidity files as a result.

**Comment by transmissions11** [comment]
This is not limited to a specific solc version or project. The compiler has simply stopped for all projects regardless of their details.

**Comment by transmissions11** [comment]
Just in case it is somehow related to my project, here's the link: https://github.com/rari-Capital/vaults

**Comment by AlphaSerpentis** [comment]
Same thing is occurring on my project - rolling back resolved the issue for me

**Comment by juanfranblanco** [comment]
@transmissions11 @AlphaSerpentis  can you check the latest? 
![image](https://user-images.githubusercontent.com/562371/140736871-8b509a42-d2fa-4cef-b3be-aa8ac88e8699.png)
What OS are you using?

**Comment by transmissions11** [comment]
looks like that build fixed it! thanks!!

i'm on macos m1 if that matters

**Comment by AlphaSerpentis** [comment]
> @transmissions11 @AlphaSerpentis can you check the latest? ![image](https://user-images.githubusercontent.com/562371/140736871-8b509a42-d2fa-4cef-b3be-aa8ac88e8699.png) What OS are you using?

Windows 10 Home Version 10.0.19043 Build 19043

It seems the latest build fixed this for me as well. Thanks for the swift fix!

**Comment by juanfranblanco** [comment]
Thanks to you both!! :)
