### ISSUE TITLE
No handler found for the command: 'solidity.compile'. An extension might be missing an activation event

### ISSUE THREAD

**Issue by areijngoudt** [juanfranblanco/vscode-solidity#3]
Hi,
When I try to compile a solidity contract in VSCode I get the error 

No handler found for the command: 'solidity.compile'. An extension might be missing an activation event

I've installed the solc compiler using npm, both global and local in the project.

**Comment by juanfranblanco** [comment]
Have you got the latest version?

**Comment by areijngoudt** [comment]
I had the version of yesterday. I've just upgraded and compilation is
starting to work!

Now I get some errors for
import "some-other-contract"

Is there a way to overcome these problems?

Best regards, Ad

2016-04-26 16:06 GMT+02:00 Juan Blanco <notifications@github.com>:

**Comment by juanfranblanco** [comment]
your imports need to follow the format of "./fileincurrentdirectory.sol" or "../upperdirectory" or "./foldermodule/anothercontract.sol"

**Comment by juanfranblanco** [comment]
this is the standard that the compiler uses to resolve paths, I used to follow your format when specifying the keys myself.

**Comment by areijngoudt** [comment]
Yep, now it compiles correctly.
Thanks man!

2016-04-26 16:16 GMT+02:00 Juan Blanco <notifications@github.com>:
