### ISSUE TITLE
I'm having trouble using the extension

### ISSUE THREAD

**Issue by BladeMF** [juanfranblanco/vscode-solidity#30]
I'm new to VS Code (using VS Ultimate) and have these questions:
* How do I start? How do I create a "project" with the correct structure and default files?
* How do I deploy (manually with Mint?)

**Comment by juanfranblanco** [comment]
@BladeMF  VsCode is different from VS Ultimate. Are you using the right extension?

**Comment by BladeMF** [comment]
Yes, I just said that I am familiar with VS Ultimate. Now I'm using your extension with VS Code. I have installed Mist and Parity.

**Comment by juanfranblanco** [comment]
Ah cool, I misread it. Are you ok now?

**Comment by BladeMF** [comment]
Well, haven't done anything yet, just reading. But if I get it correctly, your extension compiles the necessary files and then I deploy manually, right? What other stuff can I do, i.e. debugging, etc.?

**Comment by juanfranblanco** [comment]
It mainly does the compilation, highlighting, initial auto-complete, linting has been added recently by a contributor, snippets and code generation for Nethereum.

Deploying you can use truffle for that, or your custom deployment mechanism.
It does not do debugging, you can try remix for that.

**Comment by BladeMF** [comment]
Hey, it's something :) I'm happy with that for now. Thanks!

**Comment by BladeMF** [comment]
One more thing, how about the file structure. Do I create it manually or does the extension manage that?

**Comment by juanfranblanco** [comment]
There is a default file structure. Bin is the output directory. Src folder for contracts and Lib for external solidity projects. But if you are not using any library you can put your code anywhere.

**Comment by BladeMF** [comment]
That is I'm using the built in compiler, right?

Влади.

**Comment by juanfranblanco** [comment]
Yes correct.

**Comment by SeanCMrsh** [comment]
When I compile successfully - VS Code says all went well - but I cannot find any bin folder with the compile results. Where do I look?

**Comment by juanfranblanco** [comment]
@SeanCMrsh you may not have saved the file, so the output wont be produced. Also you need to open a folder / workspace.

**Comment by SeanCMrsh** [comment]
Thanks Juan - I realised my root folder in the workspace was different to that I expected and I found the bin there.
