### ISSUE TITLE
Solidity: Compile with configured Remote version: Different Results windows vs mac.

### ISSUE THREAD

**Issue by Elyx0** [juanfranblanco/vscode-solidity#302]
![image](https://user-images.githubusercontent.com/706218/143297695-ecec325c-140c-4902-8fc2-9eafef3f43a1.png)

Will link the code if needed.

Could be unrelated to the plugin as well. But it's my only lead so far.

Edit: Remix yields the same error message, not sure which to trust
![5ccad827733633d29d3d60ead232ee10 (1)](https://user-images.githubusercontent.com/706218/143306070-29fa14da-9f8d-4e19-b0d9-79b3253595a6.png)

**Comment by juanfranblanco** [comment]
@Elyx0 please post the source, although I think is easy to replicate, this is rather strange

**Comment by Elyx0** [comment]
Minimal use case was: https://gist.github.com/Elyx0/e591488642a0b8fea23d3232c78c46d6

**Comment by Elyx0** [comment]
Closing as I can't reproduce anymore.

**Comment by juanfranblanco** [comment]
Many thanks @Elyx0, this is strange, Ill have a look anyway.

**Comment by Elyx0** [comment]
Don't waste too much time I really think it was a local issue on my end. Maybe I swapped some branch between main or something, I was tired and felt guilty the next morning when I couldn't reproduce on a fresh setup to have wasted your time already. Great extension, we owe you!
