### ISSUE TITLE
VSCode format on save adding additional tabs in Solidity files

### ISSUE THREAD

**Issue by primecoderama** [juanfranblanco/vscode-solidity#310]
When I save my solidity file in VSCode it adds additional tabs (additional 2 spaces) to all single tabs (2 spaces). Where can I override this? This only happens to my solidity (.sol) files. `Format on save` works correctly for other files e.g. js extensions

VSCode settings.json
```

{
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
  "editor.detectIndentation": false
}
```

**Comment by obiwanchinobi** [comment]
This issue can be closed as it was resolved by creating a `.prettierrc` file with the tab override

**Comment by primecoderama** [comment]
This issue can be closed as it was resolved by creating a `.prettierrc` file with the tab override
