### ISSUE TITLE
Prettier does not format sol files, but works great for ts files, so prettier seems to be working

### ISSUE THREAD

**Issue by iangregsondev** [juanfranblanco/vscode-solidity#313]
Hi,

Prettier does not format sol files.

I have a simple contract (.sol) and I have put lots of spaces at the front of it and i was hoping when I saved it then it would reformat the line but it does not.

here is the abstraction of the line

```

                            function functionCall(address target, bytes memory data, string memory errorMessage) internal returns (bytes memory) {
                      return _functionCallWithValue(target, data, 0, errorMessage);
    }

    function functionCallWithValue(address target, bytes memory data, uint256 value) internal returns (bytes memory) {
             return functionCallWithValue(target, data, value, "Address: low-level call with value failed");
    }
```

here is the prettierrc file

```
{
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "printWidth": 80,
        "tabWidth": 4,
        "useTabs": true,
        "singleQuote": false,
        "bracketSpacing": true,
        "explicitTypes": "always"
      }
    }
  ]
}

```

also, see this in the logs

```
["INFO" - 3:10:15 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
```

I tested it with a .TS file and all is ok, i get stuff in the logs and also it reformats.. I have formatOnSave set also.

```
["INFO" - 3:07:29 PM] Formatting completed in 0.038ms.
["INFO" - 3:10:15 PM] Formatting file:///Volumes/Data/Development/Personal/trader/removeme/test.ts
["INFO" - 3:10:15 PM] Using config file at '/Volumes/Data/Development/Personal/trader/removeme/.prettierrc'
["INFO" - 3:10:15 PM] Using ignore file (if present) at /Volumes/Data/Development/Personal/trader/removeme/.prettierignore
```

Maybe I am doing something wrong ?

I installed the files locally - here is my package.json

```
{
  "name": "removeme",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "prettier": "^2.5.1",
    "prettier-plugin-solidity": "^1.0.0-beta.19"
  }
}

```

I did not install it globally, I presume I have to install these right ?

On a similar front, I am using solhint, but i installed this globally, this seems to work but unsure why its a global install :-)

npm install -g solhint

Any help you can offer would be gratefully appreciated, would love to have prettier format my Sol's 

If I can provide further info, don't hesitate to ask.

Thanks

p.s. here is the file structure

![image](https://user-images.githubusercontent.com/2370364/150148871-1f26a2d8-328b-4c0c-8789-c1212a87c66e.png)

**Comment by juanfranblanco** [comment]
@iangregsondev  any changes on prettierrc are only detected at the moment when restarting the ide.
To format the document you can just 
![image](https://user-images.githubusercontent.com/562371/150318330-1f0aa6f3-a87a-4781-900a-336ec87d8508.png)

**Comment by juanfranblanco** [comment]
Example
![prettier](https://user-images.githubusercontent.com/562371/150320372-d357a30f-b521-48ca-83b2-d57747f9bc55.gif)

**Comment by iangregsondev** [comment]
Hi, yep I realise that about restart the IDE.

Anyway, it still didn't work..

And guess what it was ? Something silly, I currently have another project (not sol but ts and i have its own prettier config etc etc).

I did a mkdir removeme, for testing.... but it seems that it was still pickup up the prettier config from lower down DOH :-) My bad..

I removed the "removeme" directory into its own directory and now everything is working - thanks a lot !

**Comment by juanfranblanco** [comment]
@iangregsondev thanks, mainly prettier is caching the configuration, hence it needs to restart it. I am clearing the cache now so in the next release the changes will be picked up automatically.
