### ISSUE TITLE
Empty try blocks causing parser errors

### ISSUE THREAD

**Issue by RomiRand** [juanfranblanco/vscode-solidity#315]
Empty try blocks seem to cause an parser error:
`Error: Request textDocument/definition failed with message: Expected "!", "!=", [...] or whitespace but "c" found. Line: 12, Column: 9`
Issues in https://github.com/juanfranblanco/solparse are disabled, so I'm posting here.

## Example
``` solidity
pragma solidity 0.8.10;

contract Test
{
    uint foo = 1;
    function test() public {
        foo += 1;
        try this.test() {
            // require(true);
        }
        catch {}
    }
}
```
When you go to definition (ctrl + click) of `foo` it fails. When you uncomment it works.

**Comment by juanfranblanco** [comment]
Hi @RomiRand I have opened issues there, thanks for that.

**Comment by RomiRand** [comment]
Okay thanks, I've created an issue in that repo
