### ISSUE TITLE
Add VSCode marketplace website URL to the about section of the repository

### ISSUE THREAD

**Issue by KrishnaPravin** [juanfranblanco/vscode-solidity#325]
I couldn't quickly find the extension in the marketplace as the URL is hidden behind the chip in the README.
People who are very familiar finding the marketplace URL from the chip might know it. But newbies might not quickly find the URL.

When the website is added, it will appear in this section

![Screenshot 2022-02-22 at 8 19 43 AM](https://user-images.githubusercontent.com/17372422/155054103-a6a29167-b911-48af-8470-88d4792a4167.png)

Like this:
<img width="340" alt="Screenshot 2022-02-22 at 8 20 33 AM" src="https://user-images.githubusercontent.com/17372422/155054205-44e2389f-4f14-4cc6-802d-46025e7bae7d.png">

**Clicking on the settings button will open up a model to enter the website URL.**

![Screenshot 2022-02-22 at 8 21 36 AM](https://user-images.githubusercontent.com/17372422/155054286-070a31b2-e87c-4a02-a54e-386ae1569d96.png)

URL: https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity

Anyone with the permission to edit about section, add the marketplace URL.

**Comment by juanfranblanco** [comment]
Good idea I'll add the url
