### ISSUE TITLE
Add Solhint linter against with Solium

### ISSUE THREAD

**Issue by idrabenia** [juanfranblanco/vscode-solidity#34]
Hi Guys!

We developed [linter for Solidity](https://github.com/tokenhouse/solhint) that allow to find security vulnerabilities, validate style guide compliance and best practice accordance. 

Is it ok - if I implement integration of this plugin to vscode-solidity both with solium. End user it will have possibilities to select needed linter.

What do you think @juanfranblanco?

Thanks!
\- Ilya

**Comment by juanfranblanco** [comment]
hi @idrabenia ,

Sure no problem :) If the user has the option it is great.

**Comment by juanfranblanco** [comment]
It is released now :) thanks @idrabenia
