### ISSUE TITLE
Does not support recent versions of Solidity language grammar

### ISSUE THREAD

**Issue by aathan** [juanfranblanco/vscode-solidity#368]
I cannot seem to get this extension's language server for solidity to accept valid solidity code. I've set the compiler to use to a local compiler verison 0.8.17, but I'm not sure if the extension uses the compiler or uses solhint/solium for that purpose???

The full error is:
```
Error: Request textDocument/definition failed with message: Expected "abstract", "contract", "error", "import", "interface", "library", "pragma", "struct", comment, end of input, end of line, or whitespace but "t" found. Line: 9, Column: 1
```

and the file in question contains:
```
// SPDX-License-Identifier: MIT

import "./ERC721.sol";
import "openzeppelin-contracts/contracts/access/Ownable.sol";
import "openzeppelin-contracts/contracts/proxy/utils/Initializable.sol";

pragma solidity ^0.8.17;

type TokenID is uint256;
```

... the error reported is for the "t" in "type TokenID ..."

**Comment by aathan** [comment]
I've narrowed this down to the code in `SolidityDefinitionProvider` and I believe the error is due to:
```
      const result = solparse.parse(documentText);
```

I'm unfamiliar with solparse. Maybe it's an outdated solidity grammar that doesn't have "type" in it?

**Comment by aathan** [comment]
If the underlying linters/parsers are not being kept up to date with the language, should this feature be changed to instead rely on the AST output from solc?

**Comment by juanfranblanco** [comment]
@aathan you cannot rely on the output as it might be broken, solparse is not used for this, it has been extended since.

**Comment by juanfranblanco** [comment]
more updates on the grammar on the latest https://github.com/juanfranblanco/solparse-exp
