### ISSUE TITLE
Warnings on all Functions

### ISSUE THREAD

**Issue by james-s-nduka** [juanfranblanco/vscode-solidity#37]
```No visibility specified. Defaulting to "public" ..... ^ Spanning multiple lines```

What is the solution for getting rid of this warning on the functions in my contracts?

**Comment by juanfranblanco** [comment]
This is a new warning provided by the compiler, I understand your pain. I might include the option to remove warnings, but that is something you might not want in general.

**Comment by james-s-nduka** [comment]
It's something I can live with for now :) keep up the good work on this extension.

**Comment by juanfranblanco** [comment]
Thanks @james-s-nduka
