### ISSUE TITLE
Solidity-extension in VS Code can't resolve the imports from node_modules

### ISSUE THREAD

**Issue by iamasimkhan** [juanfranblanco/vscode-solidity#370]
Please take a look at my environment details. 

**Environment** 
 - Node installed with `nvm`
 - Truffle is installed in different node environments which can be switched by simply changing the node by `nvm use v16.17.0`
- In my vs code I have installed Truffle for VS Code extension, which is also tightly dependent on solidity extension.
- I have installed `Ganache` desktop application. 
- I also have `solcjs` installed as `npm` package in one of my node versions.

**Contract**
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.4.25 <0.9.0;

import "@openzeppelin/contracts/access/Ownable.sol";

contract CallerContract is Ownable {

}
```
**Project Structure**
The node modules are installed one folder behind the truffle project for contract as shown below. 

```
├── caller
│   ├── build
│   ├── contracts
│   ├── migrations
│   ├── test
│   └── truffle-config.js
├── oracle
│   ├── build
│   ├── contracts
│   ├── migrations
│   ├── test
│   └── truffle-config.js
├── node_modules
├── package-lock.json
├── package.json
```

**Output** 
- truffle compile works fine in terminal by using `truffle compile` in all the node versions.
- In VS code truffle extension's Truffle contract explorer part successfully compiles the contract. 

**Failure**
- I am facing one failure and that is when I right-click `Solidity: Compile Contract`. It outputs 

```
Retrieving compiler information:
Compiler using default compiler (embedded on extension), solidity version: 0.8.9+commit.e5eed63a.Emscripten.clang
ParserError: Source "@openzeppelin/contracts/access/Ownable.sol" not found: File import callback not supported
 --> path to contracts/contracts/CallerContract.sol:7:1:
  |
  | import "@openzeppelin/contracts/access/Ownable.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Compilation failed with 1 errors

``` 
And I have tried many ways to resolve this as mentioned here, mainly this solution. 
```
"solidity.packageDefaultDependenciesContractsDirectory": "",
"solidity.packageDefaultDependenciesDirectory": "node_modules",
```

**Comment by denbon05** [comment]
Hi,
I faced the same problem 
![image](https://user-images.githubusercontent.com/58662935/210988758-f72e47a9-6e47-4944-9157-bd859c688889.png)
![image](https://user-images.githubusercontent.com/58662935/210989237-2e3c0c95-c4c9-4650-bcd8-7e7a0c9c72b4.png)
 
 My problem was [the extension for Hardhat](https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity) in the Truffle project.
 
 So I just disabled first one and enabled [Solidity extension from Juan Blanco ](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity)
 
![image](https://user-images.githubusercontent.com/58662935/210992119-d7029c25-10fc-41b9-afca-307adb561169.png)

Hope it will be helpful.

**Comment by yacc** [comment]
I can confirm that adding the `remappingsUnix` setting in `.vscode/setting.json` works on MacOs with a similar project structure (suggested in #320 and StackOverflow)
Just for reference manually add this in `.vscode/setting.json` at the root of your project:
```json
{
  "solidity.remappingsUnix": ["@openzeppelin/=node_modules/@openzeppelin/"]
}
```
@juanfranblanco I think it is safe to close this issue.
