### ISSUE TITLE
@custom:<name> tags not highlighted in NatSpec comments

### ISSUE THREAD

**Issue by PaulRBerg** [juanfranblanco/vscode-solidity#383]
The NatSpec format [allows](https://docs.soliditylang.org/en/v0.8.17/natspec-format.html#tags) the use of `@custom:<name>` tags, which enables users to provide custom tags for documentation. This is especially useful for structs because, alas, Solidity doesn't have NatSpec for structs still.

vscode-solidity doesn't highlight these custom tags just yet:

<img width="895" alt="Screenshot 2022-12-29 at 5 19 18 PM" src="https://user-images.githubusercontent.com/8782666/209974742-4603f178-50b3-47e4-83d1-256729ad0b03.png">

**Comment by juanfranblanco** [comment]
![image](https://user-images.githubusercontent.com/562371/223419770-6bc6f676-46fa-4e88-ab92-34c21c18b300.png)

**Comment by PaulRBerg** [comment]
Looks great, indeed!

<img width="785" alt="Screenshot 2023-03-07 at 6 24 19 PM" src="https://user-images.githubusercontent.com/8782666/223484642-1778553e-21e3-49d3-a9dc-2f79d1673b77.png">
