### ISSUE TITLE
`assembly ("memory-safe")` not supported

### ISSUE THREAD

**Issue by PaulRBerg** [juanfranblanco/vscode-solidity#386]
Solidity v0.8.13 [introduced](https://docs.soliditylang.org/en/v0.8.13/assembly.html) a dialect that lets users mark a piece of assembly code as memory safe:

```solidity
assembly ("memory-safe") {
    ...
}
```

This dialect does not seem to be currently supported by this extension:

<img width="752" alt="Screenshot 2023-02-05 at 8 03 54 PM" src="https://user-images.githubusercontent.com/8782666/216836852-363572c2-26e3-4c4f-a0e2-16c612db3b65.png">

Running Solhint via the CLI works fine! See the related discussion in https://github.com/protofire/solhint/issues/398.

**Comment by pcaversaccio** [comment]
Can confirm this behavior. If a reproducible code is needed, you can use [this](https://github.com/pcaversaccio/create-util/blob/main/contracts/Create.sol#L57) contract.

**Comment by pcaversaccio** [comment]
Thanks for the heads-up @juanfranblanco - can confirm it works now after updating. Thanks for fixing it!

**Comment by juanfranblanco** [comment]
Thanks for flagging it and for the example !

**Comment by PaulRBerg** [comment]
Thanks for the fix! Can confirm that it works now.
