### ISSUE TITLE
Support for Solidity Version `0.8.18` & `0.8.19`

### ISSUE THREAD

**Issue by pcaversaccio** [juanfranblanco/vscode-solidity#387]
Seems that Solidity version `0.8.18` is not yet supported by the plugin:

![image](https://user-images.githubusercontent.com/25297591/217103012-278f1f9c-8bda-4a35-ae64-3e94c1790613.png)

Any plans on when it will be supported?

**Comment by PaulRBerg** [comment]
I think that this issue can be closed now. Solidity v0.8.18 seems to be supported - but not certain features of it, e.g. named mapping parameters:

https://github.com/juanfranblanco/vscode-solidity/issues/391

**Comment by pcaversaccio** [comment]
not for me 

![image](https://user-images.githubusercontent.com/25297591/219748702-2b44c40e-a461-47b6-a850-c3afa76e0a69.png)

**Comment by PaulRBerg** [comment]
Oh yeah, "latest" didn't work for me either .. but this works:

```json
"solidity.compileUsingRemoteVersion": "v0.8.18+commit.87f61d96"
```

**Comment by pcaversaccio** [comment]
sure, but that's why I think this issue should not be closed.

**Comment by PaulRBerg** [comment]
I agree with you now.

**Comment by pcaversaccio** [comment]
I changed the title to also support `0.8.19` now (released yesterday https://blog.soliditylang.org/2023/02/22/solidity-0.8.19-release-announcement/). @juanfranblanco any update on the plans here?

**Comment by pcaversaccio** [comment]
Closing since the issue is resolved (at least on my end).
