### ISSUE TITLE
Command 'solidity.compile.active' not found

### ISSUE THREAD

**Issue by bcshop-io** [juanfranblanco/vscode-solidity#39]
Hello.
After recent VS Code update, I am not able to compile .sol files by pressing F5. VS Code displays error "Command 'solidity.compile.active' not found". 
Ctrl+F5 gives error "Command 'solidity.compile' not found".
I feel these commands should be configured in some sort of settings file, but I don't know how.

**Comment by lyzs90** [comment]
im getting this too, did you manage to resolve it?

**Comment by juanfranblanco** [comment]
I do not have this problem and had looked into it. Can you confirm if you are still having this issue? And in what situations?

**Comment by mcadamm4** [comment]
I am experiencing the same issue, recent version of vsCode. 
Solidity version: 
the solidity compiler commandline interface
Version: 0.4.20+commit.3155dd80.Windows.msvc

Solidity is in my path. When I try to compile, vsCode shows the following error "command 'solidity.compile' not found".

**Comment by gdesantos** [comment]
Did you solve it? 
I am getting now this error after a month using the plugin

**Comment by juanfranblanco** [comment]
Have you got installed any forked version of the plugin? This has been proven to be a conflict.

**Comment by juanfranblanco** [comment]
Closing this.. please reopen if needed

**Comment by npattarone** [comment]
Having this issue: 
    "solidity.compileUsingRemoteVersion": "v0.5.0+commit.1d4f565a"

**Comment by juanfranblanco** [comment]
Have you open a workspace / folder?

**Comment by npattarone** [comment]
I'm working on a folder, not workspace, but again, that hasn't change... just press F5 again and failed

**Comment by juanfranblanco** [comment]
So all of the sudden started to fail? Checking the obvious have you restarted?

**Comment by npattarone** [comment]
Yes, I did
