### ISSUE TITLE
vscode go to definition doesn't work

### ISSUE THREAD

**Issue by Fabien-Morrow** [juanfranblanco/vscode-solidity#398]
- [clone this](https://github.com/Fabien-Morrow/mwe_ctrl_click.git) very small mwe
- open the repo with vscode

In A.sol, I can't ctrl+click on B.sol in the import. If I remove the fallback function, it works !

Can you reproduce this ? Same behaviour on Linux, Windows. I've reinstalled extension, and deleted .vscode .code repo plenty of times, with no results.

**Comment by juanfranblanco** [comment]
Thanks for the great example ♥️, I'll investigate.

**Comment by juanfranblanco** [comment]
@Fabien-Morrow it should be fixed on the latest.
![solidity-got](https://user-images.githubusercontent.com/562371/232062465-78c7daa5-bf0b-46e7-b118-739899faa76a.gif)
