### ISSUE TITLE
Add Ethereum Icon to Associate with Solidity Files

### ISSUE THREAD

**Issue by seesemichaelj** [juanfranblanco/vscode-solidity#40]
It would be great if the extension added the icon file association for Solidity files instead of the default icon. The extension icon would work great as a file icon within VS Code

**Comment by juanfranblanco** [comment]
Looking into it

**Comment by juanfranblanco** [comment]
There is now :)

**Comment by juanfranblanco** [comment]
I did not do anything btw..

**Comment by seesemichaelj** [comment]
Haha I think the Microsoft team must of added it to the icon pack or something :man_shrugging:

**Comment by juanfranblanco** [comment]
Yes, much better that way !
