### ISSUE TITLE
Foundry remapping paths are highlighted as not found

### ISSUE THREAD

**Issue by pcaversaccio** [juanfranblanco/vscode-solidity#403]
@juanfranblanco Since around 1 day I get the following issue (I guess it's related to the recent Foundry support PR):

![image](https://user-images.githubusercontent.com/25297591/231992650-bd20b0ab-30db-4490-bc17-4d69db268c31.png)

My remappings file:
![image](https://user-images.githubusercontent.com/25297591/231992784-4d63895b-4d88-447e-bdad-f9fe798a34be.png)

You can reproduce the behavior via my repo [here](https://github.com/pcaversaccio/snekmate).

To be clear, there is no compilation issue at all from Foundry, just the warning in the UI. Also, before (i.e. 2 days ago and before) everything was working smoothly.

**Comment by juanfranblanco** [comment]
I can see what is happening your foundry file has an empty array of remappings that is taking preference over the real remappings

**Comment by PaulRBerg** [comment]
>  Pinging @PaulRBerg, you got the same warnings?

Nope

**Comment by pcaversaccio** [comment]
I guess you're referring to this 
![image](https://user-images.githubusercontent.com/25297591/231994261-6188f4ba-6d3c-4f71-adbf-112523380cef.png)

So, `foundry.toml` remappings take preference over my `remappings.txt`? The [default value](https://github.com/foundry-rs/foundry/blob/master/config/README.md#all-options) is an empty array of remappings actually: 
![image](https://user-images.githubusercontent.com/25297591/231995571-6f282262-af93-4880-a7fb-74dea96bb276.png)

So I didn't do anything special here...

**Comment by juanfranblanco** [comment]
@pcaversaccio update the latest in a couple of minutes as I have put a check to ignore null remappings in the foundry config file.

@PaulRBerg @pcaversaccio I have assumed that foundry takes preference over remappings.txt thoughts?

**Comment by juanfranblanco** [comment]
It is out now the fix.. Thanks again @pcaversaccio

**Comment by pcaversaccio** [comment]
> @pcaversaccio update to the latest in a couple of minutes as I have put a check to ignore null remappings in the foundry config file. Thanks for pointing it out that it was the default too!

Thanks a lot! We revert with a confirmation once tested.

> @PaulRBerg @pcaversaccio I have assumed that foundry takes preference over remappings.txt thoughts? https://github.com/foundry-rs/foundry/blob/master/config/src/providers/remappings.rs#L40

![image](https://user-images.githubusercontent.com/25297591/231999918-32f0f5bd-eab4-4d53-ae4a-4e59db4576d4.png)

I prefer working with `remappings.txt` files since otherwise the `foundry.toml` file gets too verbose.

**Comment by pcaversaccio** [comment]
> It is out now the fix.. Thanks again @pcaversaccio

Thx a lot @juanfranblanco!

**Comment by pcaversaccio** [comment]
Confirmed - everything fixed.

**Comment by PaulRBerg** [comment]
> I prefer working with remappings.txt files since otherwise the foundry.toml file gets too verbose.

Same. Also, separating the remappings in a bespoke `remappings.txt` makes it easier to compartmentalize the project settings - this is useful e.g. when documenting how to install a Foundry project, as I often include a reference to what the user should have in the `remappings.txt` files (whereas explaining what field one should set in the Foundry config is more cumbersome).

**Comment by juanfranblanco** [comment]
Great thanks, I see your point, maybe that is another option to having a common project file which has been my hope for years .. different settings, per file. In that scenario it makes more sense that the remappings file will take preference over the foundry if found, as it is a decision to make it generic.

**Comment by pranjal1127** [comment]
@juanfranblanco still happening with me 
<img width="436" alt="image" src="https://github.com/juanfranblanco/vscode-solidity/assets/45527699/3f272ff4-3b24-4754-b3ec-a8f93bb9e0c0">

**Comment by juanfranblanco** [comment]
Have you tried to change the setting from monorepo back and forth,?

**Comment by pranjal1127** [comment]
I have added this 
So sometime it doesn't bother  but sometime it shows error although I can access files by cmd + press
<img width="629" alt="image" src="https://github.com/juanfranblanco/vscode-solidity/assets/45527699/8f870c09-3590-4e04-9709-8017ea072265">

**Comment by gnattishness** [comment]
@pranjal1127
If you are defining your remapping with the `@` symbol `@openzeppelin`, you should also be importing using that.
That is:
```solidity
import "@openzeppelin/token/ERC20/IERC20.sol"
```
The "@" character is not treated specially.
Check whether you can compile - if not, it's not an issue with `vscode-solidity` :)
