### ISSUE TITLE
Add `0.8.20` support

### ISSUE THREAD

**Issue by pcaversaccio** [juanfranblanco/vscode-solidity#408]
Any plans to support Solidity version `0.8.20` by default? Or is the intention to wait until most EVM chains adopted `PUSH0`? 

![image](https://github.com/juanfranblanco/vscode-solidity/assets/25297591/b0a42641-79d7-4363-97e0-c827bda8caad)

**Comment by juanfranblanco** [comment]
Yes, that is correct, well at least until everyone is more aware.

**Comment by juanfranblanco** [comment]
@pcaversaccio (and everyone checking this out) also note that "latest " defaults to 19, 20 needs to be set manually.

**Comment by pcaversaccio** [comment]
thanks for the ping!
