### ISSUE TITLE
VSCode Output windows opens automatically (with Solhint linter)

### ISSUE THREAD

**Issue by kandrianov** [juanfranblanco/vscode-solidity#41]
VsCode version: 1.18.1
OS version: MacOs 10.13

How to reproduce:
1. Open Terminal window
2. Edit your .sol files
3. Output panel with errors takes focus

**Comment by idrabenia** [comment]
Hi @kandrianov ,

Thanks for your feedback!

It is fixed and I believe it will be published soon! 

Thanks!
\- Ilya

**Comment by arnoudbevers** [comment]
Hi,

I've been using the VScode extension for about two weeks now and this issue keeps happening.
The extension has been updated to v 0.0.31.
Is there any way to solve this?

**Comment by juanfranblanco** [comment]
Closing this now
