### ISSUE TITLE
color coding for `internal` keyword does not work?

### ISSUE THREAD

**Issue by StefH** [juanfranblanco/vscode-solidity#43]
When using the `internal` keyword, it remains white, and I would expect it to follow the same color for `public` or `private`?

See this:
![2017-12-27_18h59_03](https://user-images.githubusercontent.com/249938/34389149-51b04b00-eb38-11e7-9b65-fcbd0c02568a.png)

**Comment by eduardonunesp** [comment]
Yeah `internal` needs to be highlighted

**Comment by StefH** [comment]
thanks
