### ISSUE TITLE
 @juanfranblanco/vscode-solidity-server not found on npm registry

### ISSUE THREAD

**Issue by sify21** [juanfranblanco/vscode-solidity#432]
The language server can't be installed through `npm`:
`npm install -g @juanfranblanco/vscode-solidity-server`

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@juanfranblanco%2fvscode-solidity-server - Not found
npm ERR! 404 
npm ERR! 404  '@juanfranblanco/vscode-solidity-server@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by juanfranblanco** [comment]
Is not out yet, next week.

**Comment by llllvvuu** [comment]
Automation available if desired: https://github.com/juanfranblanco/vscode-solidity/pull/429

**Comment by juanfranblanco** [comment]
I know, I seen it, pretty cool!
I guess hooking the automation to  a release, and creating a custom fork could allow to publish directly from a fork named after the release, removing the need to have the secrets in Github.

**Comment by GeorgeGkas** [comment]
hi team, do you have any updates on this task?

**Comment by juanfranblanco** [comment]
this is in just "vscode-solidity-server"
