### ISSUE TITLE
Upgrade Solhint version to catch new rules

### ISSUE THREAD

**Issue by AlissonRS** [juanfranblanco/vscode-solidity#439]
I'm using Solhint 3.6.2, which provides a rule `immutable-vars-naming` to use SNAKE_CASE for immutable state, there was also a [PR on Solhint repo](https://github.com/protofire/solhint/pull/458) to fix the `var-name-mixedcase` rule to disregard immutable variables, which was added in Solhint 3.5.1.

This extension is using Solhint 3.4.0 though, so it's making VS Code to give false positive errors:

![image](https://github.com/juanfranblanco/vscode-solidity/assets/4753901/202f7563-e99f-44af-904a-666272a964cf)

Is there a way to configure the extension to use a higher Solhint version, or rather would it be ok to upgrade Solhint version on this extension? I'm keen on opening a PR for this if this is desirable.

Thanks for such a great extension!!!

**Comment by JosephSaw** [comment]
+1

**Comment by juanfranblanco** [comment]
@AlissonRS it is now integrated in the latest versions
