### ISSUE TITLE
v0.0.167 Unable to compile, prompt: Invalid EVM version requested

### ISSUE THREAD

**Issue by doxulovezh** [juanfranblanco/vscode-solidity#447]
![image](https://github.com/juanfranblanco/vscode-solidity/assets/54633419/2669b83a-06a4-4aed-bbc6-a1b81e5682fb)

**Comment by doxulovezh** [comment]
V0.0.165 can be used correctly but v0.0.167 error

**Comment by juanfranblanco** [comment]
@doxulovezh fixed now Thanks!

**Comment by doxulovezh** [comment]
Thanks!
