### ISSUE TITLE
`Source file requires different compiler version` warning even after global compiler is set

### ISSUE THREAD

**Issue by pcaversaccio** [juanfranblanco/vscode-solidity#448]
I'm seeing since a couple of days (I use the latest VS Code Solidity version) the `Source file requires different compiler version` warnings even if I configured the global remote compiler to be `0.8.24`:

![image](https://github.com/juanfranblanco/vscode-solidity/assets/25297591/cb425c22-7d56-4bb8-b242-44424efe0a42)
![image](https://github.com/juanfranblanco/vscode-solidity/assets/25297591/ec240ec4-391b-48f4-ae85-ddb3fac56574)
![image](https://github.com/juanfranblanco/vscode-solidity/assets/25297591/1465e944-6828-4550-9d01-78168b49a900)

This configuration has been working smoothly in the past. So am not sure what happened.

**Comment by juanfranblanco** [comment]
@pcaversaccio have you checked your workspace version? Look at the complete settings using F1 >> User settings >> Solidity

**Comment by pcaversaccio** [comment]
> @pcaversaccio have you checked your workspace version? Look at the complete settings using F1 >> User settings >> Solidity

yup checked
![image](https://github.com/juanfranblanco/vscode-solidity/assets/25297591/c642adcd-4cab-4f8a-858f-3ab05251f1b6)

**Comment by pcaversaccio** [comment]
> > @pcaversaccio have you checked your workspace version? Look at the complete settings using F1 >> User settings >> Solidity
> 
> yup checked ![image](https://private-user-images.githubusercontent.com/25297591/304746136-c642adcd-4cab-4f8a-858f-3ab05251f1b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MTkzODYsIm5iZiI6MTcwNzkxOTA4NiwicGF0aCI6Ii8yNTI5NzU5MS8zMDQ3NDYxMzYtYzY0MmFkY2QtNGNhYi00ZjhhLTg1OGYtM2FiMDUyNTFmMWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDEzNTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNDE4ZTM5NjJiNjQ2NmExMGE2NDY0MjVjNzc1NTc1MDBiOWNhNjUwYTg5NTcwZTY4MTQ4ODJkNDE4YmU1ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nymme2RV4duWtrpTQlCfXlRejt1FGn7vAWieCoCZcCU)

After restarting and waiting for around 20mins it finally went away... very weird behaviour. But will close now since the error is gone.
