### ISSUE TITLE
Formatter error: Extension 'solidity' is configured as formatter but it cannot format 'solidity - files

### ISSUE THREAD

**Issue by amusingaxl** [juanfranblanco/vscode-solidity#452]
I have the following in my `settings.json`:

```json5
    "[solidity]": {
        "editor.defaultFormatter": "JuanBlanco.solidity"
    },
    "solidity.formatter": "forge",
```

However, whenever I try to format a .sol file, I get this error:

![2024-03-14_12-03](https://github.com/juanfranblanco/vscode-solidity/assets/112016538/9bfef653-e28d-4864-9ba9-de45564e09af)

If I click "Configure", the only option I see is this one:
![2024-03-14_12-03_1](https://github.com/juanfranblanco/vscode-solidity/assets/112016538/642959c3-f688-4175-8458-50b030f066b6)

If I select it, it overrides the value in `settings.json`:

```diff
     "[solidity]": {
-        "editor.defaultFormatter": "JuanBlanco.solidity"
+        "editor.defaultFormatter": "0xp.vsc-solidity"
     },
     "solidity.formatter": "forge",
```

**Comment by juanfranblanco** [comment]
You need to remove that extension if you have it installed "0xp.vsc-solidity"

**Comment by juanfranblanco** [comment]
I have ask him to contribute here :)
