### ISSUE TITLE
VS Code autocomplete feature broken when extension running

### ISSUE THREAD

**Issue by Eric-Showers** [juanfranblanco/vscode-solidity#46]
I'm not sure if anyone else has experienced this but autocomplete is working for me in every file type except Solidity. If I disable this extension then autocomplete works properly again with Solidity files. I have set "editor.quickSuggestions": true in my settings but the issue persists. Would be nice to know if others are experiencing this too, it's not great having to double check the spelling every time I reference a variable.

I am running VS code version 1.19.2 on Win 10

**Comment by juanfranblanco** [comment]
@Eric-Showers  I think the autocomplete you refer to, is the suggestions on what you have written before. As opposed to autocomplete for code. I would look for a way to also include those.

**Comment by juanfranblanco** [comment]
I had a look, and there is not a capability to enable both at the same time that I could find. Closing for now, but keeping an eye if it becomes possible.

**Comment by b1acKr0se** [comment]
@juanfranblanco I am experiencing this issue with solidity extension 0.0.50, vscode 1.32.3. It's very frustrating because the only way to make code suggestion work is to disable this extension. I notice it works too when vscode starts up until the extension finishes loading.

**Comment by juanfranblanco** [comment]
@b1acKr0se is this something recent with 0.0.50? or is the generic quick suggestion you need.

**Comment by b1acKr0se** [comment]
@juanfranblanco 
Sorry, I was talking about this 

<img width="623" alt="Screen Shot 2019-04-05 at 9 00 43 AM" src="https://user-images.githubusercontent.com/8596158/55599331-6ba6c500-5781-11e9-89f4-2b0fa83d007b.png">

It should provide the variable `new_address`. I tried the previous version (0.0.49) and sometimes it works, sometimes it doesn't work. I haven't figured out the pattern on when it works yet.

**Comment by juanfranblanco** [comment]
Yes, it won't work once the extension is loaded as it does not recognise parameters yet. When is loading is using the default auto-complete of visual studio code which mainly outputs all the words within the text document.

**Comment by Elyx0** [comment]
Having the same issue it only completes natspec. Maybe a conflict with tintinweb extensions?

**Comment by juanfranblanco** [comment]
@Elyx0 It might be, does it happen for all contracts?
