### ISSUE TITLE
first line pragma flags a compilation error

### ISSUE THREAD

**Issue by jtakalai** [juanfranblanco/vscode-solidity#47]
I start my Solidity with ```pragma solidity ^0.4.0;``` and I get an entry in problems tab: 
```
file: 'file:///.../MyContract.sol'
severity: 'Error'
message: '/.../MyContract.sol:1:1: Error: Expected import directive or contract definition.
pragma solidity ^0.4.0;
^'
at: '1,2'
```

If I comment that first line, I get the following entry in problems tab:
```
file: 'file:///.../MyContract.sol'
severity: 'Warning'
message: 'pragma-on-top: No PRAGMA directive "pragma solidity <VERSION>" found at the top of file.'
at: '3,1'
```

So... which way would the plugin be happy? 😄 (obviously the pragma should be there)

JuanBlanco.solidity version: 0.0.31 (right now showing exactly 63,000 downloads, grats!)
solc --version: Version: 0.4.8+commit.60cc1668.Darwin.appleclang
VSCode version: 1.19.3

**Comment by jtakalai** [comment]
Hmm, doing ```npm install solc``` fixed it for me. No idea if that was a real fix, or if the real fix was turning it off and on again.

**Comment by jtakalai** [comment]
Perhaps you might want to test if you can replicate this with out-of-the-box VSCode download, then close this issue?

**Comment by juanfranblanco** [comment]
Hi, you can configure the extension to use any solidity version you want, check the user settings, or readme for help.
