### ISSUE TITLE
pragma solidity ^0.4.17;

### ISSUE THREAD

**Issue by Serjster** [juanfranblanco/vscode-solidity#49]
It looks like the current version of this is compiled for Solidity 0.4.15 so trying to use 0.4.17 causes  VS Code to falsely detect issues. I'm curious as to the status update of this extension including the latest changes to Solidity (`pragma` version, `pure` and `view` being the current annoyances)?

**Comment by juanfranblanco** [comment]
I will release a new version, today thanks.

**Comment by Serjster** [comment]
Did you ever release the new version? I still don't see an update for it in Code.

**Comment by alberthu16** [comment]
I'm getting a similar issue between solidity 0.4.18 vs 0.4.19

```
SyntaxError: Source file requires different compiler version (current compiler is 0.4.18+commit.9cf6e910.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.19;
^---------------------^
```

my truffle version:
```
➜  sp18-lab03 git:(albert) ✗ truffle version
Truffle v4.0.6 (core: 4.0.6)
Solidity v0.4.19 (solc-js)
```

**Comment by juanfranblanco** [comment]
Any issues like this, just change your configuration to compile using the latest or any other version you want / need.

**Comment by sdelvalle57** [comment]
> Any issues like this, just change your configuration to compile using the latest or any other version you want / need.

How?

**Comment by zzj0402** [comment]
It's alarming me to change my solidity version 0.5.0.

**Comment by rushabh098** [comment]
SyntaxError: Source file requires different compiler version (current compiler is 0.4.24+commit.e67f0147.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.11;
^---------------------^
