### ISSUE TITLE
Block gaslimit member.

### ISSUE THREAD

**Issue by ArnaudovSt** [juanfranblanco/vscode-solidity#52]
The block member should be `block.gaslimit`, and not `block.gasLimit` as it is now.
![image](https://scontent.fsof2-1.fna.fbcdn.net/v/t34.0-12/28450073_1595879683837974_1609604530_n.jpg?oh=8605d1fc7da31d36eefc98106f10c1c1&oe=5A970072)

**Comment by juanfranblanco** [comment]
Changed, thanks for reporting it
