### ISSUE TITLE
Solium Dependency Update

### ISSUE THREAD

**Issue by ZitRos** [juanfranblanco/vscode-solidity#53]
Hello! Thank you for writing a great plugin for VSCode.

While [Solium is v1.1.5](https://github.com/duaraghav8/Solium/blob/b201acd1d5df0b31b31a6107e18be8733857539d/package.json#L3) in master branch, it is still v0.5.5 in vscode-solidity.

Will you accept pull request updating the dependency? Are there any critical parts of the plugin that may be affected?

Thank you!

**Comment by antogh** [comment]
Any advice on how to upgrade the Solium version in this VS Code solidity extension? I get a lot of nonsense warning and errors on some sources, would like to use the new solium version but don't know how to upgrade. Thanks

**Comment by ZitRos** [comment]
@antogh looks like they abandoned this project. Maybe we should consider forking it. Anyone from maintainers?

**Comment by duaraghav8** [comment]
Hey guys, I'm the maintainer of Solium.
Although I don't have much knowledge about this extension itself, you can try resolving your problem the same way https://github.com/beaugunderson/vscode-solidity-extended/issues/3 deals with it.

**Comment by ZitRos** [comment]
@duaraghav8, thank you! Doing so will most likely work, but we need to get some feedback from `vscode-solidity` maintainers first. They have a couple of PRs with no feedback and that's why I assume the project is abandoned. Anyone from maintainers? @juanfranblanco?

**Comment by antogh** [comment]
Thank you @duaraghav8  

I tried the other extension but I didnt find a way to change the compiler version there
When I tried I was very tired (working hard on short deadlines) so I asked on that repo how to do it, 
https://github.com/beaugunderson/vscode-solidity-extended/issues/8
no answer so far

Overall the other extension seems less documented and with much less settings to customize the environment. I prefer this extension.

@juanfranblanco did an excellent job, he also has a great reputation, I dont think he abbandoned this project. I hope to get an answer from him to fix this issue. Shouldnt be difficult, after all solium is just an external reference to this extension, should be a matter to upgrade that reference. I confess I tried to force this upgrade manually but failed so far, 
I changed the package.json reference to solium, in a win10 machine it is located here
%USERPROFILE%\.vscode\extensions\JuanBlanco.solidity-0.0.31\package.json
and I changed the solium folder with the newest from @duaraghav8  repo , in the same win10 machine this is the folder where the vscode extension stores solium 
%USERPROFILE%\.vscode\extensions\JuanBlanco.solidity-0.0.31\node_modules\solium

unfortunately something went wrong, VS Code was erroring at start saying the extension crashed. 

Again I did it tired and in a hurry, maybe I missed something, if someone else want to try and in case of success update this thread.

I have also the problem that github email notifications sometime are not fired, I missed the last couple of messages here, I have to do manual polling to check the issues I am involved in... 😡

**Comment by juanfranblanco** [comment]
No the project is not abandoned I just get no damn notifications. I will do upgrades this weekend for everything.

Please drop by in Gitter on either Nethereum or Vscode if you dont get any answers.

**Comment by juanfranblanco** [comment]
Yes. I have actually just done that, let's see how it goes. Feel free to ping me anytime in twitter or Nethereum https://gitter.im/Nethereum/Nethereum. I am always there providing support.

**Comment by ZitRos** [comment]
Thank you very much @juanfranblanco! I appreciate your work and use your solidity plugin on a daily basis.

**Comment by juanfranblanco** [comment]
Closing this, as it is upgraded now.

**Comment by antogh** [comment]
Hi @juanfranblanco  saw the upgrade this morning I got the new solium in your extension (dind't even notice the upgrade, all was done silently without requesting my approval to update) 

However I have a problem with this upgrade, now every linter warning or error is causing an annoying popup to appear in the bottom right corner , how do I disable it? I was ok with errors just in the "problems" windows that I show when I want but these continuos notification popup are really annoying and distracting when coding

**Comment by juanfranblanco** [comment]
That might be due to the Emit issue as it is not fully finished in solium. I'll disable it (remove it)

**Comment by antogh** [comment]
ok thanks, have a look at this to feel my pain
![vscode popups](https://user-images.githubusercontent.com/8667587/37593945-1b829cbe-2b74-11e8-9a6c-0934b2c3c497.png)

**Comment by juanfranblanco** [comment]
New version published

**Comment by antogh** [comment]
Thanks, I see no more popups , 
but again 
didnt tell vs code to update your extension nor I was notified it was happening , it seems all happening in background silently... robots starts to decide instead of humans :)
