### ISSUE TITLE
In MetaCoin TestMetacoin.sol file, import "truffle/Assert.sol"; is red

### ISSUE THREAD

**Issue by stefanks** [juanfranblanco/vscode-solidity#54]
Says ParserError: Source "truffle/Assert.sol" not found.
The test compiles and runs fine. 
I'm on a mac.

**Comment by myknbani** [comment]
Happens to me as well.  Code compiles via CLI, it's just a VSCode thing.  I'm on Ubuntu 17.10.

**Comment by juanfranblanco** [comment]
Yes, there is not a specific setting to resolve truffle.

**Comment by juanfranblanco** [comment]
Closing this, but it might be reopen for full integration with truffle
