### ISSUE TITLE
Syntax error when emitting events in Solidity 0.4.21

### ISSUE THREAD

**Issue by rrickdar** [juanfranblanco/vscode-solidity#57]
This issue is a duplication of this [question](https://ethereum.stackexchange.com/questions/42671/vs-code-syntax-error-when-emitting-events-in-solidity-0-4-21) on Ethereum StackExchange: 

I'm having a syntax error in VS Code in the parts where I emit events using new notation for Solidity v0.4.21.

Remix doesn’t raise any errors, though.

My User Settings in VS Code contain `"solidity.compileUsingRemoteVersion": "latest"`, and compiler doesn't raise error on `emit` itself, rather gives this message:

`Syntax error: Expected "!=", "%", "%=", "&", "&&", "&=", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", "/", "/*", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", ">>>", "?", "^", "^=", "|", "|=", "||", comment, end of line, or whitespace but "(" found.`

Here's how it looks like (2nd emit event is ok for some reason):

![screen shot 2018-03-13 at 22 36 25](https://user-images.githubusercontent.com/15833027/37392768-60820358-276f-11e8-828e-88d3a0532404.png)

The problem is in syntax only, compilation completes successfully.

**Comment by naddison36** [comment]
`emit` just needs to be added as a keyword in the following line https://github.com/juanfranblanco/vscode-solidity/blob/master/syntaxes/solidity.json#L76
@rrickdar do you want to have a go at doing a Pull Request for this change?

**Comment by rrickdar** [comment]
I see now that @lew made a Pull Request just two days ago:
https://github.com/juanfranblanco/vscode-solidity/pull/56/

**Comment by ImmuneGit** [comment]
it doesn't resolves a problem for me... just change a color of emit from white to purple and I got:
Syntax error: Expected "!=", "%", "%=", "&", "&&", "&=", "*", "*=", "+", "++", "+=", ",", "-", "--", "-=", "/", "/*", "/=", ";", "<", "<<", "<<=", "<=", "=", "==", ">", ">=", ">>", ">>=", ">>>", "?", "^", "^=", "|", "|=", "||", comment, end of line, or whitespace but "(" found.

**Comment by lew** [comment]
https://github.com/duaraghav8/solparse/issues/29

I think this was the problem

**Comment by rrickdar** [comment]
Updating npm packages solium to v1.5.5. and solparse to v2.2.4 solves the issue

**Comment by rrickdar** [comment]
As mentioned by @duaraghav8 in #https://github.com/duaraghav8/Solium/issues/177, the fix will be added in the new version of `Solium`, i.e the `Solparse` dependency where support for `emit` was recently added in v2.2.4 will be updated.

**Comment by rrickdar** [comment]
Updating solparse to `2.2.4` alone didn't help, rather update combination of `solium 1.1.5` plus `solparse 2.2.4` with a bit of manual modification of `package-lock.json` worked perfectly.
Thank everyone in this thread!

**Comment by duaraghav8** [comment]
^Thanks, I think you'd have to do that if the extension by default uses solium v0.

**Comment by juanfranblanco** [comment]
@rrickdar  @duaraghav8  I have updated the extension to both the latest and works like a charm thanks and merged that pull request too.

**Comment by juanfranblanco** [comment]
@duaraghav8 BTW many thanks for Solium :)

**Comment by duaraghav8** [comment]
Great @juanfranblanco! Thanks for *your* work on this & Nethereum :)

**Comment by rrickdar** [comment]
👍 Issue closed

**Comment by juanfranblanco** [comment]
@duaraghav8  I think I spoken too soon ?

If I put emit I get an error.
![image](https://user-images.githubusercontent.com/562371/37564348-4ce19f00-2a8c-11e8-8331-d213673fa041.png)

But if don't use emit I don't get an error I get a warning, which is the correct behaviour

![image](https://user-images.githubusercontent.com/562371/37564361-7a5efe32-2a8c-11e8-995c-eba507417a20.png)

It was not reported yesterday as the message format has changed (other issue)

**Comment by duaraghav8** [comment]
@juanfranblanco actually this isn't unexpected. Vscode Solidity uses the latest version of Solparse (2.2.4) which **has** support for emit.

But this error came from Solium. The latest version of it (1.1.5) contains **solparse 2.2.3** as an internal dependency, which **does not** have support for emit. So when Solium tries to lint your solidity code, it doesn't recognise `emit` because it uses its internal solparse which doesn't support emit.

This isn't your fault. I'll be releasing the next version of solium in a day or 2 which will contain latest solparse as internal dep. So all you need to do is update vscode-solidity's solium version to 1.1.6 when I ping you (on this thread or gitter channel?).

**Comment by juanfranblanco** [comment]
@duaraghav8  Excellent thanks, I am getting notifications too now. :)

**Comment by juanfranblanco** [comment]
Note: Notifications from Github. I had problems. 

@duaraghav8  I have added autofix to the extension for the current document using Solium. I had a look at the indentation rules to implement fixing based on the "Quotes" one, but true, no idea where to start.

**Comment by duaraghav8** [comment]
ah! The indentation rule is the longest (and most spaghetti!) code I've written in Solium. I wouldn't be surprised if somebody got lost trying to read it.

I'd recommend you **don't** implement indent's fix right now. Its on priority since manually fixing indents is obviously very painful. I plan to get 2-3 devs on board now that we have a little help from ethereum grants who'll [refactor](https://github.com/duaraghav8/Solium/issues/166) and implement all the [missing fixes](https://github.com/duaraghav8/Solium/issues/94).

Nevertheless, if you'd still like to give it a shot, [this section](http://solium.readthedocs.io/en/latest/developer-guide.html#writing-a-core-rule) will help you understand how a rule is implemented in solium and contains info about implementing fix. From there, I'll help clarify all your doubts.

The list of rules currently providing autofix can be found [here](http://solium.readthedocs.io/en/latest/user-guide.html#list-of-style-rules)

**Comment by juanfranblanco** [comment]
@duaraghav8 Thanks, if you are getting developers, they will do a much better job than me. The implementation (whilst rudimentary) is already there to trigger it, I won't just mention it yet.

**Comment by juanfranblanco** [comment]
Referencing https://github.com/juanfranblanco/vscode-solidity/issues/18

**Comment by duaraghav8** [comment]
MAN this feature is in demand!

**Comment by DanielRX** [comment]
@duaraghav8 Mainly because right now linting for 0.4.21 fails for me, so I can't actually use `emit` and have to ignore the warning that I need to add it, otherwise the linter just stops on the first use of `emit`

**Comment by juanfranblanco** [comment]
@DanielRX he was referring to the formatting, he mentioned he will be releasing the fix related to the emit soon.

And yes, the workaround is to ignore the warning for the time being.  Good point you mention it.

**Comment by DanielRX** [comment]
@juanfranblanco Apologies, is there anyway I can edit the deps myself so that I can have solium run with the latest solparse just as a bootstrap so I can avoid forgetting to readd emits?

**Comment by juanfranblanco** [comment]
well another option is to modify the package file of solium.

"  "dependencies": {
    "ajv": "^5.2.2",
    "chokidar": "^1.6.0",
    "colors": "^1.1.2",
    "commander": "^2.9.0",
    "js-string-escape": "^1.0.1",
    "lodash": "^4.14.2",
    "sol-digger": "0.0.2",
    "sol-explore": "1.6.1",
    "solium-plugin-security": "0.1.1",
    "solparse": "2.2.4",
    "text-table": "^0.2.0"
  },"

But I cannot release this as the packaging resets all the package references. (Ill try again)

**Comment by juanfranblanco** [comment]
Ok I have actually released a new version with the dependency hardcoded, test it and see how it goes @DanielRX

**Comment by DanielRX** [comment]
@juanfranblanco I think it's working, now I just need to work out a nice way to edit my line endings when I swap windows <-> unix until that fix is out aha

**Comment by duaraghav8** [comment]
@juanfranblanco Solium 1.1.6 is now out and supports `emit`. I haven't included support for automatic indentation formatting yet, turns out to be way more complex than I thought!
Let me know if you face any issues

**Comment by juanfranblanco** [comment]
@duaraghav8  Many thanks, I will update it today and let you know. And yes indentation formatting seems rather complex.

**Comment by elie222** [comment]
So I don't have problems with emit anymore, but I do have an issue when I use msg.sender on a line that has `emit` in it:
```
ParserError: Expected token Semicolon got 'LParen'
    emit Deposit(msg.sender, _amount, shares, totalShares);
```

**Comment by juanfranblanco** [comment]
@duaraghav8  FYI ^^

**Comment by elie222** [comment]
A bunch changed in my settings and the issue has gone away since then.
I think there may be some issues for users when using both this package and the extended version of the package together. I had some weird issues around linting and emit going on and had both packages installed.

**Comment by juanfranblanco** [comment]
yes having the extended version has been validated to be a problem.
