### ISSUE TITLE
Autocomplete improvements

### ISSUE THREAD

**Issue by juanfranblanco** [juanfranblanco/vscode-solidity#58]
Autocomplete is working, but it could be better.

On struct, identify the type declared or returned by a method and do a dot completion on properties.
On contract, identify the type declared or returned by a method and do a dot completion on functions.
Methods need to identify the type returned.

**Comment by reuvenpo** [comment]
hello juanfranblanco.
is there progress on this issue? i'm seeing the same the same issue as described in #66.

I'm using npm's solc v0.5.10, npm v6.10.0, node v12.7.0

**Comment by rocky** [comment]
Gee this seems to be vscode report issue day today.  This too I have been working on and here is a screenshot for one of the programs listed above: 

![vsode-completion](https://user-images.githubusercontent.com/8851/62540671-22957900-b826-11e9-8bde-e6622fe221ad.png)

As I mentioned in https://github.com/juanfranblanco/vscode-solidity/issues/88#issuecomment-518601360 I hope to have things cleanup in about a week and I will may have a video on this. 

However to manage expectations, early on I am targeting hackers who might be willing to work on the code to improve it. I hope to be focusing more on the backend and making this more available pervasively such as also in remix, the atom editor, eclipse. 

Also I should say with respect to completion, there are changes in the works to solc itself to make this work smoother. I'll give more details sometime later as things are more definite.

**Comment by juanfranblanco** [comment]
That is awesome @rocky is that using the AST from Solc now ?

**Comment by rocky** [comment]
Yes, it uses the AST from Solc.

**Comment by juanfranblanco** [comment]
Awesome !!! :)
@reuvenpo To answer your question, we were awaiting to use solc AST instead of solparse as it is the best source of information. @rocky has been working on solc to enable to use their AST as part of a language server

**Comment by reuvenpo** [comment]
awesome! thanks guys :)

BTW, I'm really amazed at the quick response! I thought that this issue was really backlogged, since there was no comment here for over a year.

**Comment by juanfranblanco** [comment]
Yes, lots of thought about this, I did not want to progress in any direction as the solc was making the most sense. @rocky which is an AST / language expert it is making it a reality.

**Comment by juanfranblanco** [comment]
This is done in current releases

**Comment by markokhman** [comment]
#316 Hello folks, not sure how to make this autocomplete work for me on VScode, explained in details here
