### ISSUE TITLE
How to turn off linting for libraries

### ISSUE THREAD

**Issue by akucheruk-vareger** [juanfranblanco/vscode-solidity#65]
Hi,
When I use libraries such as zeppelin, I get annoying linting Warnings for libraries code like this:

![linting libraries](https://user-images.githubusercontent.com/31038795/39083635-1b8523c4-4570-11e8-8655-727a9ec04966.png)

Is this possible to turn off linting for imported libraries?

**Comment by juanfranblanco** [comment]
Good point and no, but it will be as simple as closing the file? Although it is good to know the library that you are using may have some issues.

**Comment by akucheruk-vareger** [comment]
Hmm.
I don't open lib file, this is my own contract that import one.
And (for me) I prefer to catch issues in my own code that not mixed with lib's issues especially if notice about lib's issue appears in random place of my code. 
And there are can be a lot of such notices that can hide my own code issue from my eyes. 
Also I can do nothing (except fork) with lib or don't want to do that.
Is this smth related to Visual Studio Code behavior?

**Comment by akucheruk-vareger** [comment]
![random annoying warnings](https://user-images.githubusercontent.com/31038795/39085099-ca8fc48a-4586-11e8-9f1f-32405ecef6fe.gif)

**Comment by juanfranblanco** [comment]
Ok the issue, is on compilation. Mainly the auto highlighting of compiling erros is creating the warnings.

**Comment by juanfranblanco** [comment]
Yes, you will get the warnings for dependencies regardless, as your dependency might be your own project. But you should not get those warnings on the file, I am checking that now.

**Comment by juanfranblanco** [comment]
@akucheruk-vareger  check the latest release

**Comment by akucheruk-vareger** [comment]
Got it!
Everything is OK.
Thank you very much!

**Comment by juanfranblanco** [comment]
@akucheruk-vareger  thanks to you !
