### ISSUE TITLE
Solidity Linter no longer shows Problems

### ISSUE THREAD

**Issue by ricochen** [juanfranblanco/vscode-solidity#69]
It worked fine a week/2 weeks ago, but right now the linter isn't working at all.

![vscode1](https://user-images.githubusercontent.com/16439986/39983272-f11b55f6-570b-11e8-8b6f-54afafb2ae34.png)
![vscode2](https://user-images.githubusercontent.com/16439986/39983273-f136027a-570b-11e8-8d07-5d2a7fb7f0d1.png)

**Comment by juanfranblanco** [comment]
Hi, have you installed any of the "extended" solidity extensions? As they are causing problems.

**Comment by juanfranblanco** [comment]
Did you install it and then this issue happened?

**Comment by ricochen** [comment]
No it was already happening before I installed solidity extension.

**Comment by juanfranblanco** [comment]
Have you tried to open only the ERC20 folder?

**Comment by juanfranblanco** [comment]
This is a wild shot btw..

**Comment by ricochen** [comment]
Yes still doesn't work. Could it be something with my windows setup? I did
install geth etc recently.

**Comment by juanfranblanco** [comment]
No geth won't affect this. I am releasing a new version with a higher number. I am thinking something is being left behind that causes this.

**Comment by ricochen** [comment]
It works fine on my mac, which I just installed VS Code and your extension.

Also, the default does not work with open-zeppelin:

// Default directory where the Package Dependency store its contracts, i.e:
'src', 'contracts', or just a blank string ''
"solidity.packageDefaultDependenciesContractsDirectory": "contracts",

// Default directory for Packages Dependencies, i.e: 'node_modules', 'lib'
"solidity.packageDefaultDependenciesDirectory": "node_modules",

I have to do this in User Settings:

"solidity.packageDefaultDependenciesContractsDirectory": "",
"solidity.packageDefaultDependenciesDirectory": "",

**Comment by ricochen** [comment]
It turns out in my C:\Users\ricox\.vscode\extensions I had:

JuanBlanco.solidity-0.0.42
JuanBlanco.solidity-0.0.43. 

2 solidity extensions for some reason. I deleted them and reinstalled and now the linting works!

**Comment by juanfranblanco** [comment]
@ricochen awesome thanks, great discovery work. I'll raise an issue (or if you want you are welcome) to vscode.

**Comment by juanfranblanco** [comment]
Raised as above, it is by design as per comments. See the thread.
