### ISSUE TITLE
openzeppelin-solidity imports are highlighted red (but compile fine)

### ISSUE THREAD

**Issue by aleybovich** [juanfranblanco/vscode-solidity#70]
I use `openzeppelin-solidity` package in my project (installed with `npm install --save openzeppelin-solidity`), and my smart contract file has this line:

`import "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol";`

VS Code highlights `import` in red with the error `Source "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol" not found`

Everything compiles and works fine, it's just annoying to see an error. Anything can be done about that?

**Comment by juanfranblanco** [comment]
For that scenario you need your user settings as following:

```json
    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "node_modules",
```

**Comment by kigawas** [comment]
Say your repo structure like this (`openzeppelin-solidity` is in `node_modules`):
```
.
├── .git
├── .gitignore
├── README.md
└── src
    ├── contracts
    │   └── Hello.sol
    ├── node_modules
    │   └── openzeppelin-solidity
    ├── package-lock.json
    └── package.json

5 directories, 5 files
```

If you open vscode at the root level, you should set config like:
```json

    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "src/node_modules",

```

**Comment by aleybovich** [comment]
That fixed the issue, thank you!

**Comment by docHologram** [comment]
I have added
```
{
    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "node_modules",
}
```
to my user settings in VS code too, but...

I'm using truffle and created a project with `truffle init` so mine looks like this and my import statements aren't working for the extension (highlighting red).
```
    ├── contracts
    │   └── Hello.sol
    ├── migrations
    │   └── 1_initial_migration.js
    ├── node_modules
    │   └── openzeppelin-solidity
    ├── src
    │   └── css
    │   └── fonts
    │   └── js
    │   └── index.html
    └── test
    └── package.json
    └── bs-config.json
    └── truffle.js
```

Would the presence of the `/src` directory as a sibling of `/contracts` being confusing to the extension, such that the extension is looking for dependencies inside of `/src` and yet it only finds the front-end files? If so, wouldn't everybody using truffle have this problem? I know this issue is closed but I would greatly appreciate any advice here. On the bright side, this problem is forcing me to understand openzeppelin better 😸 .

**Comment by santanaruben** [comment]
I have the same problem related here. I'm trying every possible solution but I keep seeing that anoying red line. So, I'm givin up and importing from ../node_modules. If someone can resolve it, will be a light.

**Comment by djneely** [comment]
@santanaruben Had the same issue. No luck either so doing what you're doing.

**Comment by phillipgibb** [comment]
I am not having luck, it seems as if solidity.packageDefaultDependenciesDirectory is being ignored

**Comment by phillipgibb** [comment]
> @phillipgibb
> What OS are you using and how exactly does your setting look like? I'm on Mac and it works fine, no more highlighted imports

@aleybovich I am using a Mac as well.
```
"solidity.packageDefaultDependenciesContractsDirectory": "",
"solidity.packageDefaultDependenciesDirectory":"node_modules"
```

**Comment by aleybovich** [comment]
That seems correct. And you import from solidity like this? 
`import "openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol";`

**Comment by aleybovich** [comment]
Then we have the same setup, and mine works.. Not sure what's the problem on your end.

**Comment by sirpy** [comment]
I have the same issue on windows, on my linux it seems to work fine.

**Comment by EazyReal** [comment]
Maybe a relative path approach would be better?
if the code is at `{contract root}/A.sol`
look for `{contract root}/../{library root}/B.sol`

**Comment by VeNoM000001** [comment]
> @djneely @aleybovich
> 
> Say your repo structure looks like this (`openzeppelin-solidity` is in `node_modules`):
> 
> ```
> .
> ├── .git
> ├── .gitignore
> ├── README.md
> └── src
>     ├── contracts
>     │   └── Hello.sol
>     ├── node_modules
>     │   └── openzeppelin-solidity
>     ├── package-lock.json
>     └── package.json
> 
> 5 directories, 5 files
> ```
> 
> If you open vscode at the root level, you should config like:
> 
> ```json
>     "solidity.packageDefaultDependenciesContractsDirectory": "",
>     "solidity.packageDefaultDependenciesDirectory": "src/node_modules",
> ```

thanx bro

**Comment by sherajr** [comment]
How do you change user settings to:
{
"solidity.packageDefaultDependenciesContractsDirectory": "",
"solidity.packageDefaultDependenciesDirectory": "node_modules",
}

On WSL2 terminal?
