### ISSUE TITLE
Add jump to function definition

### ISSUE THREAD

**Issue by juanfranblanco** [juanfranblanco/vscode-solidity#71]
From vscode solidity gitter: @mspublic
"I was curious if there is a way to jump to function definition? For example in goland if you command+click on a function it will jump to its definition."

**Comment by vaibhavchellani** [comment]
i think this can be closed now @juanfranblanco

**Comment by kamisan118** [comment]
Tried goto function definition, but it's not working.
I'm trying to figure out what is missing. Need an advice. 

The way I use this feature: in solidity code file, press F12 at a function call (the function is implemented in the same file). The result: No definition found for "functionName".

I've tried to compile the code first. But it's no use.

My environment:
Windows 7 64-bit
VSCode v1.31.1
extension: solidity v0.0.49

**Comment by Jonathan-Livingston-Seagull** [comment]
I am also facing the same issue and created a new [issue](https://github.com/juanfranblanco/vscode-solidity/issues/244).
