### ISSUE TITLE
dapphub libraries are not found, but compile fine

### ISSUE THREAD

**Issue by nanexcool** [juanfranblanco/vscode-solidity#74]
Similar to #70 

This is the tree for https://github.com/dapphub/ds-thing
```
tree -d
.
├── lib
│   ├── ds-auth
│   │   ├── lib
│   │   │   └── ds-test
│   │   │       └── src
│   │   └── src
│   ├── ds-math
│   │   ├── lib
│   │   │   └── ds-test
│   │   │       └── src
│   │   └── src
│   ├── ds-note
│   │   ├── lib
│   │   │   └── ds-test
│   │   │       └── src
│   │   └── src
│   └── ds-test
│       └── src
├── out
└── src
```

It looks like it'd be correct for finding the files. For example under `src/thing.sol` there are three imports:

```
import 'ds-auth/auth.sol';
import 'ds-note/note.sol';
import 'ds-math/math.sol';
```

These libraires are under `lib/ds-auth/src/auth.sol` etc...

**Comment by juanfranblanco** [comment]
@nanexcool  you will need to add the path for "lib" in the dependencies module
and the contracts in "src". The original library was dappsys and that was the basis, so it has to work :)

I will post a sample ASAP of the settings.

**Comment by juanfranblanco** [comment]
"solidity.packageDefaultDependenciesContractsDirectory": "src",
"solidity.packageDefaultDependenciesDirectory": "lib",


![image](https://user-images.githubusercontent.com/562371/41222278-5dbab6da-6d5e-11e8-858a-a51bb9bbda6b.png)

**Comment by juanfranblanco** [comment]
And the compilation using vscode

![image](https://user-images.githubusercontent.com/562371/41222337-80af950c-6d5e-11e8-813c-04e29fbf2db6.png)

**Comment by nanexcool** [comment]
Thank you very much, that worked! I got confused because in the description I saw:

"Libraries will have the same name as their folder they are included. Solidity files will be in the 'src' folder. Libraries will be included in the 'lib' folder."

Thanks again!
