### ISSUE TITLE
Not using the solidity.packageDefaultDependenciesDirectory correctly?

### ISSUE THREAD

**Issue by Talvish** [juanfranblanco/vscode-solidity#78]
I have a project setup with Truffle (standard contracts, migrations, etc directories) and setup for NPM so I can do dependency handle (in particular grabbing Open Ethereum) I have my settings currently set to ...

    "solidity.packageDefaultDependenciesDirectory" :  "node_modules",
    "solidity.packageDefaultDependenciesContractsDirectory" : "contracts"

    (which is the default)

… but for some reason I have to write my imports like this …

    import 'node_modules/openzeppelin-solidity/contracts/ownership/Ownable.sol';

… to not have VS Code complain about my imports. If I override the settings to match the default, the error still exists. Checking online the indication seems to be that these settings should be set to ...

    "solidity.packageDefaultDependenciesDirectory" :  "",
    "solidity.packageDefaultDependenciesContractsDirectory" : ""

… to get around the issue (which I did in my user settings)… and it is true it does. Seems these settings aren't working as intended?

**Comment by juanfranblanco** [comment]
What is your directory structure? Have you got "node_modules" at root?

**Comment by Talvish** [comment]
Yup, the "node_modules" directory is off the root of the project as are the other truffle created directories (e.g. "contracts", "build", "migrations"). Also in the root are the files "package-lock.json", "package.json", "truffle.js" and "truffle-config.js".

**Comment by juanfranblanco** [comment]
You need to take into account that path.

**Comment by Talvish** [comment]
Not sure what that means? 

If you mean that I need to put in 'node_modules' on the import statement, that is getting around something that solc is trying to make sure you don't need to do. 

What I'm not understanding is how the 'solidity.packageDefaultDependenciesDirectory' is used since it defaults (and was set) to be 'node_modules' but didn't work when I thought it would have (but setting it to '' will properly not require 'node_modules').

**Comment by juanfranblanco** [comment]
what i mean the vscode compiler needs to know the full path (relative to your working folder) of the node_modules to find it.

this might be "node_modules" at root
or might be "solidity_libraries/node_modules"

**Comment by juanfranblanco** [comment]
that is your "solidity.packageDefaultDependenciesDirectory"

**Comment by saurfang** [comment]
If you are setting up a standard truffle project via `truffle init` or `truffle unbox`, you can use the following settings:

```json
  "solidity.packageDefaultDependenciesContractsDirectory": "",
  "solidity.packageDefaultDependenciesDirectory": "node_modules"
```

then import as usual like so

```solidity
import "openzeppelin-solidity/contracts/token/ERC721/ERC721Token.sol";
```

**Comment by phillipgibb** [comment]
This does not work even if I start from scratch.
solidity.packageDefaultDependenciesDirectory is not being picked up by the extension

**Comment by hswopeams** [comment]
It doesn't work for me either.

**Comment by jbroudou** [comment]
Neither does it work for me

```
    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "node_modules",
```

and my directory structure is as follows

`
- root
    - contracts
    - node_modules
`
