### ISSUE TITLE
Expected identifier, got 'LParen' linter error

### ISSUE THREAD

**Issue by andreafspeziale** [juanfranblanco/vscode-solidity#81]
Hi there,
maybe I'm doing something wrong but I've an error at this kind of implementation:

`constructor(bool status)`

The highlighted says: 
```
Expected identifier, got 'LParen'
constructor(bool status)
               ^
```

I'm using the following user settings:
`"solidity.compileUsingRemoteVersion": "latest"`

All the other settings are as default.
Thanks in advance

**Comment by juanfranblanco** [comment]
That is due to the linter, what is your full contract?

**Comment by andreafspeziale** [comment]
Sure it is the contract.

```
pragma solidity ^0.4.21;

import "./interfaces/TollBoothOperatorI.sol";
import "./Pausable.sol";
import "./Owned.sol";
import "./Regulated.sol";
import "./MultiplierHolder.sol";
import "./DepositHolder.sol";
import "./TollBoothHolder.sol";
import "./RoutePriceHolder.sol";

contract TollBoothOperator is Owned, 
    Pausable, 
    Regulated, 
    MultiplierHolder,
    DepositHolder,
    TollBoothHolder,
    RoutePriceHolder,
    TollBoothOperatorI {
    
    constructor(bool status, uint initialDepositWei, address initialRegulator)
        public 
        Pausable(status)
        DepositHolder(initialDepositWei)
        Regulated(initialRegulator)
    {

    }

    function() public {
        rever();
    }

}
```

**Comment by andreafspeziale** [comment]
Yes that was just a type error.
I got this:
![screen shot 2018-07-03 at 12 41 27](https://user-images.githubusercontent.com/7680940/42215437-b58c93ee-7ebe-11e8-8dc0-d467b61beab6.png)

**Comment by juanfranblanco** [comment]
So do you get the same error when you remove all the imports and multiple inheritances?
That was my question.

**Comment by andreafspeziale** [comment]
Yes
![screen shot 2018-07-03 at 13 33 31](https://user-images.githubusercontent.com/7680940/42217500-bc85c3a8-7ec5-11e8-827a-9e7dcf9c41a8.png)

**Comment by andreafspeziale** [comment]
OK.
I think it's all about the compiler cause in other projects I don't have such error.

if I use `function NameOfContract(...)` no error will be displayed.

But If I change the pragma to `0.4.24` the linter will display an error saying that locally I've installed `0.4.21`. 
So even I set in the settings to use `"solidity.compileUsingRemoteVersion": "latest"` without explicit anything about the local installation it will anyway looking at the local installation before using the remote version specified in the settings as above.

Could it be correct?

Thanks.

**Comment by andreafspeziale** [comment]
@juanfranblanco I think we can close it. What do you think?

Plus, is the following right?

```
Note: The order of preference when using these settings are: Local node installation will be use first, Local file second and finally remote.
```

I think a better naming in the docs would help.
The `node` word makes me confused, I usually use the `node` word speaking about the Ethereum client.

So:
- `Local node installation ` is it the machine global installation?
- `Local file` is it about (eg) the node_modules dependencies?
- `Remote` ok is the remote versioning of the compiler.

**Comment by juanfranblanco** [comment]
Ah.. I see what you mean. 

1. Local node installation, means installation on the current directory of solc using node.
2. Local file, means you downloading a solc file.

**Comment by lucribas** [comment]
I had the same problem using the Solidity extension in VSCODE and fixed that with the following steps:
- unistall "Solidity" extension in vscode;
- add to settings.json (vscode):
```
{
...
	"solidity.enableLocalNodeCompiler": false,
	"solidity.compileUsingRemoteVersion": "v0.6.12+commit.27d51765",
	"solidity.packageDefaultDependenciesContractsDirectory": "",
	"solidity.packageDefaultDependenciesDirectory": "node_modules"
...
}
```
- change the pragma in your contract file:
```
pragma solidity >=0.6.00;
```

- close all instances of your vcode;

- delete the node_modules folder;

*IMPORTANT* 
- install a clean version of nodejs. I´m using the nvm (Node Version Manager) tool to allow install and switch between versions. Currently only version 10 of node.js works.
```
nvm install 10.22.1
nvm use 10.22.1
```
- install openzeppelin-solidity:
```
npm i openzeppelin-solidity
```
- open vscode and install the "Solidity" extension;


I hope that these steps also fix your environment as fixed the mine. Good luck!
