### ISSUE TITLE
No formattting when I do Ctrl+Shift+I

### ISSUE THREAD

**Issue by Rpittrer** [juanfranblanco/vscode-solidity#83]
I just get a message saying "no document formatter for 'solidity'-files installed."

**Comment by juanfranblanco** [comment]
@Rpittrer there is none implemented.

**Comment by quezak** [comment]
@juanfranblanco Are there plans to implement a formatter? Maybe in some simple form for starters, just to fix indentation?

**Comment by juanfranblanco** [comment]
I am hoping the solium linter to provide fixing for indentation, this is rather complex, so I may do it for in vscode. @quezak
