### ISSUE TITLE
[Question] Solhint config file

### ISSUE THREAD

**Issue by JFGHT** [juanfranblanco/vscode-solidity#84]
```
{
  "solidity.linter": "solhint",
  "solidity.solhintRules": {
    "avoid-sha3": "warn",
    "indent": ["warn", 2]
  }
}
```

That is the .solhint.json I do have in the root of the project. Still, opening the .sol file shows:

> indentation: Only use indent of 4 spaces.

It only works by putting the config globally.

What am I missing here?

**Comment by fvictorio** [comment]
This is an old issue, but just in case someone ends up here: that's not a valid `.solhint.json` file. Those properties are part of the `settings.json` file of this plugin. An equivalent solhint config is:

```
{
  "rules" {
    "avoid-sha3": "warn",
    "indent": ["warn", 2]
  }
}
```

(Notice though that `indent` was removed in solhint 3.0)

**Comment by juanfranblanco** [comment]
Closing this now
