### ISSUE TITLE
Replace `any` types in the library making everything strongly typed.

### ISSUE THREAD

**Issue by joshstevens19** [juanfranblanco/vscode-solidity#92]
Throughout the library there are about 55 instances of `any`. As using typescript allows you to build a strongly typed JavaScript application I think merging these `any` into strongly typed classes or interfaces would be very beneficial. 

This will also allow writing tests for the library a lot easier as you know what you should be passing through to the function and the complier will throw a exception if passed in incorrectly.  

Having this also allows new contributors ease of understanding what each function does.

**Comment by juanfranblanco** [comment]
This is an unnecessary change, see our chat before. Refactoring things like this may be done when changing a specific feature. Mainly I wan to avoid change for the sake of change, as it will be a maintainers nightmare. For example I have to now go throught each let / const and validate correctness (obviously if using a tool to automatically refactor, this does it for you and you can rely on that and I can take the hit of any issues for this).

**Comment by joshstevens19** [comment]
Ok if you think that is best but having ‘any’ in any typescript codebase is smelly code so I do not see this as a unnecessary change. It’s like using dynamic for every type in c# you just don’t do it.

**Comment by juanfranblanco** [comment]
No my thought is that it can be refactored as needed, slightly different approach.
