### ISSUE TITLE
Is broken with openzeppelin

### ISSUE THREAD

**Issue by Gargo** [juanfranblanco/vscode-solidity#96]
https://github.com/OpenZeppelin/openzeppelin-solidity
correct instruction is mentioned here:
https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1342

everything is compiled but your extension shows errors with import. So at least how to make it ignoring `import` directives?

**Comment by juanfranblanco** [comment]
Can you post a screenshot of the warning / problem? Is this due to including truffle's test?

**Comment by Gargo** [comment]
@juanfranblanco 
![default](https://user-images.githubusercontent.com/853345/46102706-a4188580-c1d7-11e8-8de5-e7670232338a.png)

**Comment by ajhodges** [comment]
You need to add this to your settings:
```
    "solidity.packageDefaultDependenciesContractsDirectory": "",
    "solidity.packageDefaultDependenciesDirectory": "node_modules",

**Comment by sneko** [comment]
Thanks @ajhodges , it was by default ` "solidity.packageDefaultDependenciesContractsDirectory": "contracts",` . I was fighting to find the right solution 🔨
